### ISSUE TITLE
Admin cannot delete topic created by other users.

### ISSUE THREAD

**Issue by mahzilla** [rubysherpas/forem#100]
Admins can lock and hide but cannot delete topic created by other users.

**Comment by radar** [comment]
I can verify this issue. Let me look into a fix for it now.

**Comment by parndt** [comment]
Should this be a real delete or a paranoid delete (using some deleted_at column)?

**Comment by radar** [comment]
It's real delete at the moment. I've not seen a feature request for paranoid deletion yet.

**Comment by radar** [comment]
@mahzilla: Thanks for reporting this issue. It's now been fixed!
