### ISSUE TITLE
Email Subscriptions Proposed Feature List

### ISSUE THREAD

**Issue by jgadbois** [rubysherpas/forem#101]
Current feature plans (italics is @radar reply to my initial email)
### Subscription Management
- Subscribe/Unsubscribe link on topic view if logged in
  
  _I think this is fine. It should indicate clearly if a person is subscribed or not._
- Either a check box or automatic subscription when adding a post to a topic
  
  _Determining if a user should be automatically subscribed could be done with a forem_auto_subscribe field on the "users" table that defaults to true. This could then be toggled on a profile page somewhere for the user, perhaps? We don't have somewhere like that in Forem at the moment._
- Initially, an unsubscribe link in the email footer (vs a management page for subscriptions?)
  
  _That would be fine, I think._
### Subscription Emails
- Emails get sent out every reply to everyone but the person who added the new reply
  
  _That's correct. My concern with this is that it won't work at scale, but that's something to just think about for the future. There should of course be only one email per person._
- Text of post is in email?

_Not sure how you'd go about preserving the formatting here. I think just a notification of "Blah has posted in your topic called 'blah'" is fine, for now. If you want to go ahead and put the post text in the email then be my guest. I'd actually prefer it that way._

**Comment by jgadbois** [comment]
I implemented the subscribe/unsubscribe link with specs - should I open a pull request even though I am not done so you can comment on the code as I work on it?  I used a Subscriptions controller for subscribing/unsubscribing.  Actions on the topics controller might be cleaner although less RESTful.

**Comment by knewter** [comment]
@jgadbois what's the situation with this one now.  I saw you closed the old pull request, but did you ever open a new one?

**Comment by radar** [comment]
Finished afaik.
