### ISSUE TITLE
Running specs deletes all dummy migrations

### ISSUE THREAD

**Issue by jgadbois** [rubysherpas/forem#102]

**Comment by radar** [comment]
What command are you using to run them?

**Comment by jgadbois** [comment]
I think the one that seems to delete them is just running `rake` at the top level of the repo.  I also use `bundle exec rspec` to run specific specs.

**Comment by radar** [comment]
`rake` just runs `rake spec`, so I don't see how that could be doing it...

**Comment by radar** [comment]
It's the install generator spec. We should probably use fakefs or something like that for this.

**Comment by benatkin** [comment]
Can this be closed now? While I haven't seen this issue occur, it seems likely that #149 affected it.

**Comment by radar** [comment]
Yes, good point this should be closed now.
