### ISSUE TITLE
Update dummy app javascripts

### ISSUE THREAD

**Issue by jgadbois** [rubysherpas/forem#103]
The dummy app calls a couple javascript files that aren't there.  Either we need to manually add rails-jquery and rails-ujs javascripts, or update the dummy app to use the asset pipeline.

**Comment by radar** [comment]
What effect is this having on the engine at the moment?

**Comment by jgadbois** [comment]
None directly but my subscription branch has some POST and DELETE links that won't work without rails-ujs

**Comment by radar** [comment]
Rightio, that's fixed now.
