### ISSUE TITLE
Log_in by username, helpers

### ISSUE THREAD

**Issue by regedarek** [rubysherpas/forem#106]
Hi,
When I change authentication_keys to [ :username ] in devise. Forem views have trouble viewing username, it`s easy to change except one:

```
= link_to_latest_post(topic.posts.by_created_at.last)
```

How to change this helper?

**Comment by radar** [comment]
Could you explain how the `link_to_latest_post` method is broken? This will use whatever value the `User#to_s` method outputs as its output. Just define a `to_s` method in your model using the method you want (which in this case is probably `username`)

**Comment by regedarek** [comment]
Ok, but how to define to_s method in user.rb

``` ruby
def self.to_s
  self.username.to_s
end
```

Something like this?

**Comment by radar** [comment]
No, like this:

```
def to_s
  username
end
```

This is because you want to define an instance method and not a class method. No need for the `to_s` call inside the method as it's already going to be a string.

**Comment by regedarek** [comment]
Thanks Radar
