### ISSUE TITLE
Transparent avatars let icon background appear

### ISSUE THREAD

**Issue by fdutey** [rubysherpas/forem#107]
Hi.

There's a little issue with transparent avatars.
avatar img is in a div with class icon. This div has a background (set in css) wich seems to be a kitten.
When you use a transparent avatar, this kitten background appears.

You can fix it by removing background properties in application.css (above line 139)

here is a screenshot if my english is too poor:
http://img692.imageshack.us/img692/8384/capturewco.png

best regards

**Comment by knewter** [comment]
@radar don't see that this one's an issue anymore, as (a) there's no longer an application.css, and (b) you totally rewrote the styles I had in there :)  Also, meow

**Comment by knewter** [comment]
I do not believe this occurs any longer, and it's been 3 months since my previous comment with no one disputing.  Closing the issue.
