### ISSUE TITLE
Forem Should Include Default Formatter

### ISSUE THREAD

**Issue by robyurkowski** [rubysherpas/forem#110]
I think this is something that ought to be discussed. If there's consensus, I'm happy to provide a patch.

It doesn't make sense that Forem comes without a formatter. New users expect that there will be rich text editing—a standard for pretty much any online forum. Providing the option to customize is powerful, but the goal ought to be zero-config: the most standard use case should require absolutely zero admin work. To me, that means including a default {insert-templating-language-here} formatter that can be overridden.

**Comment by radar** [comment]
I can agree with this. Personally I like Markdown, but some other people may prefer something like BBCode, which is something Forem doesn't support at the moment. I wonder if @parndt or @knewter have any thoughts on this one?

**Comment by robyurkowski** [comment]
BBCode and 'the best forum system out there' are anathematic statements. :P

**Comment by knewter** [comment]
I like it.  I think you'd want to just provide a block that is passed the content of the forum post, and by default that would be Forem.default_formatter = lambda{ |content| Redcloth.new(content).to_html }

Something like that?  That seems the most flexible and simple

**Comment by knewter** [comment]
lol entirely missed that you'd already added the formatter bits in there :)  At any rate, I prefer markdown which is what you'd asked I think :)

**Comment by radar** [comment]
Hi friends,

I've thought about how we could do this.  Mainly because I've been working on forem-redcarpet today, which I think should be the default because it supports code-highlighting and nothing else does.

 We could have the default formatter be a strict dependency of Forem, meaning that it would be installed when the Forem gem is used. When the application starts, it will load the Formatter along with Forem and have it basically seamless. 

If you want to override the formatter, you just need to specify another formatter gem in your Gemfile which should be enough to override the `Forem.formatter` setting and alter it.

Good?

**Comment by knewter** [comment]
sounds good to me

**Comment by robyurkowski** [comment]
Makes sense.

**Comment by radar** [comment]
Ugh, this breaks Rubinius's build. FAIL.

**Comment by parndt** [comment]
Do you mean _this_ bbaa8f57e267f6b00d7a5ce4af7b36ab38a65cbb breaks the build?

**Comment by radar** [comment]
Yes, rubypython doesn't work on rubinius.

**Comment by parndt** [comment]
Can we make it work?

**Comment by radar** [comment]
I dunno... it seemingly needs a constant from within FFI. There be dragons.

**Comment by parndt** [comment]
FYI @brixen

**Comment by jeremyong** [comment]
Does everybody like the zero configuration approach? I'm not sure I agree.

If people wanted something that worked completely out of the box, they'd go with vBulletin or something. Personally, I think it's a lot easier to let people install whatever markup gem they want, and configure the views as they like. This is very easy and would just require minor documentation on our part.

Not everybody wants or needs code highlighting, for example. Others need to cater to an audience who is used to bbcode. In my case, for example, I may be migrating users from an older forum system where bbcode was used a lot.

**Comment by knewter** [comment]
@jeremyong I don't see why you would dislike the zero config approach tbh.  This just provides a default - you can override it easily, and I would expect there to be new formatter gems created/released as people need them.

This will result in _more_ configurability, not less, imo.

**Comment by knewter** [comment]
Why is this still open?   bbaa8f57e267f6b00d7a5ce4af7b36ab38a65cbb was merged and that took care of this, yes?

**Comment by parndt** [comment]
Allegedly, @knewter

**Comment by knewter** [comment]
@robyurkowski if this is still an issue for you, reopen?  (a) I think this is solved, and (b) the goal is to also include highlight.js for syntax highlighting so there's more work to be done on this front anyway
