### ISSUE TITLE
Cannot access path helpers created by omniauth?

### ISSUE THREAD

**Issue by dapz** [rubysherpas/forem#115]
I have an app that uses Devise for authentication, and also makes use of the omniauth-facebook plugin (so that users can sign in via Facebook.)

It looks like path helper's of the form:

``` ruby
main_app.user_omniauth_authorize_path(:facebook)
```

fails in correctly pointing to the main application's `user_omniauth_authorize_path(:facebook)` url.

The reason is because this particular path is created by Devise, and isn't included in the routes.

What is the cleanest way of accessing this path from within Forem?

More generally, how do you access paths defined in the main_app but which aren't in the routes?

**Comment by radar** [comment]
How is Devise creating this route? Do you know?

**Comment by dapz** [comment]
See this:
http://stackoverflow.com/questions/5172321/help-using-devise-with-the-built-in-omniauth-support

Devise defines the route here:
https://github.com/plataformatec/devise/blob/master/lib/devise/omniauth/url_helpers.rb
