### ISSUE TITLE
NameError in Forem/forums#index

### ISSUE THREAD

**Issue by Akram-Khan** [rubysherpas/forem#118]
Hi,

I installed forem today and was trying to get it working but am stuck at this issue. 

This problem does not occur if I login and then try to go to localhost:3000/forums. I am using devise for authentication.

I checked the demo app which is deployed on Heroku and replaced "signup_path" with "'/users/sign_up'" and did the same thing with the login path and the app works.

This causes more trouble if I am using a custom authentication method and try to call the form from multiple places.

Here are my devise routes :- 

 devise_for :users do
    get "/signup" => "devise/registrations#new"
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

Here is the details from the log file :-

ActionView::Template::Error (undefined local variable or method `signup_path' for #<#<Class:0xb8f0d94>:0xb8ea548>):
    4:          =link_to logo, root_url
    5:      .three.columns
    6:          -if current_user.blank?
    7:              =link_to "Sign Up",signup_path, :class=> "small radius nice green button"
    8:              =link_to "Login",login_path, :class=> "small radius nice blue button"
    9:      .three.columns
    10:             =form_tag "/search", :method =>"get" do
  app/views/layouts/_above_header.html.haml:7:in`_app_views_layouts__above_header_html_haml___982755214_82209660'
  app/views/layouts/application.html.erb:12:in `_app_views_layouts_application_html_erb__889993777_968552

Thanks,
Akram

**Comment by radar** [comment]
You need to specify :as => "sign_in" for that route for it to generate the right path helper:

**Comment by Akram-Khan** [comment]
I tried including :as => "sign_in" but I am still getting the same error

**Comment by radar** [comment]
Sorry, you need to put :as => "signup" on the signup route so that it defines a signup_path method.

**Comment by Akram-Khan** [comment]
Could you please provide the details of as to why this problem was coming? 

Thanks,
Akram

**Comment by radar** [comment]
Because you were defining routes without defining the routing helpers for it. The :as option does that.

**Comment by Akram-Khan** [comment]
Thanks Ryan, so for my login I could do it :as => "sign_in" and it should work for the similar error which I am getting for the login_path?

**Comment by radar** [comment]
That's right :)

**Comment by Akram-Khan** [comment]
sorry to bother you again Ryan but that error still persists and I am still getting the same error in the logs which I have mentioned  above. This time I have done both :as => "signup" and :as => "sign_in"

Ok was able to fix it for devise :)

**Comment by radar** [comment]
So is this fixed now?

**Comment by Akram-Khan** [comment]
Ya was able to use it with devise.
