### ISSUE TITLE
Cannot create New Forem Topic

### ISSUE THREAD

**Issue by abhijeetmisra** [rubysherpas/forem#121]
I have installed forem, and i can go to the Forums page. However, I cannot find anything there, and no way of creating new Forum Topic, example: whats given in the Heroku app : "Welcome to Forem".

Please help.

**Comment by browning** [comment]
Are you logged in as a user with the forem_admin flag set?
If you are, you should see a link to the admin area where you can create forums.

You can set the forem_admin flag in the users table in the database

**Comment by abhijeetmisra** [comment]
Thanks, I logged in as admin, and now i can see and manage the forums :)
