### ISSUE TITLE
testing factory issue

### ISSUE THREAD

**Issue by regedarek** [rubysherpas/forem#123]
I forked forem and run commands above but I receive error with factory_girl:
 ```/home/rege/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in`require': no such file to load -- factory_girl (LoadError)

```
http://pastie.org/3150900
```

**Comment by radar** [comment]
What was the exact command you used to run this?

**Comment by regedarek** [comment]
`bundle exec rake -f spec/dummy/Rakefile db:drop db:create db:migrate db:test:prepare` 
and `bundle exec rspec spec`

sorry I re-paste it from https://github.com/radar/forem/issues/24

**Comment by radar** [comment]
What version of factory_girl_rails do you have installed? Mine's at 1.2.0.

**Comment by regedarek** [comment]
`gem list` gives me

``` ruby
factory_girl (2.3.2, 2.1.0)
factory_girl_rails (1.4.0, 1.2.0)
```

**Comment by regedarek** [comment]
ok I removed factory_girl 2.3.2 and factory_girl_rails 1.4.0 and 130 examples pass. :)

**Comment by radar** [comment]
Ok, looks like this could be because of the factory girl bump. I'll investigate a little later today.
