### ISSUE TITLE
how to display engine

### ISSUE THREAD

**Issue by regedarek** [rubysherpas/forem#124]
I`m new with engines.
If i would like to see what i changed in my forked engine, the only way is push changes to my github repository and add to external application Gemfile something like this:

``` ruby
gem 'forem',  :git => "git@github.com:regedarek/forem.git"
```

or write tests. Is this correct?

Because when I`m starting server I see only Dummy App.

**Comment by radar** [comment]
If you go to /forem in your browser when accessing the application you should be able to see the forums there. This is because of how the engine is mounted inside the dummy app. 

See spec/dummy/config/routes.rb.

**Comment by regedarek** [comment]
ok but i dont have users table how you deal with it? I should write migration?

**Comment by radar** [comment]
It's setup inside spec/dummy's migrations.
