### ISSUE TITLE
Database seed / installation fails when no User present

### ISSUE THREAD

**Issue by robyurkowski** [rubysherpas/forem#125]
In the event of a fresh install where the administrator has not yet created a user, database seeding will fail because it expects such a user.

**Comment by browning** [comment]
Hey, sorry I just did  pull request #126 to fix this bug.
The installation couldn't see the user_class because forem.rb wasn't loaded after it was installed in the generator.
It now handles this.

**Comment by robyurkowski** [comment]
Awesome.
