### ISSUE TITLE
No route matches [POST] "/signin.user"

### ISSUE THREAD

**Issue by Akram-Khan** [rubysherpas/forem#130]
I have customized divise views to get it in a partial. The code works fine. However as soon as I install forem and try to signup I am neither able to signin nor able to signup.

I have already added main_app to signin and signup.

P.S:- Do we have a google group for forem? I am really struggling with forem implementation what should have been an easy task has already taken me three days.

Thanks,
Akram

**Comment by radar** [comment]
Do you have an application somewhere that we can take a look at to diagnose these problems? Right now we are completely in the dark as to how you have customized your Devise views.

**Comment by Akram-Khan** [comment]
Thank you so much for your reply Ryan, I have pushed the code on github, here is the link https://github.com/Akram-Khan/Forem-on-Devise

It would be great if you could have a look at it.

Thanks,
Akram

**Comment by radar** [comment]
Your `app/views/devise/shared/_links.erb` should look like this:

``` erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", main_app.new_user_password_path %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", main_app.new_user_confirmation_path %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", main_app.new_user_unlock_path %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", main_app.omniauth_user_authorize_path(provider) %><br />
  <% end -%>
<% end -%>
```

You were originally missing the `main_app.` prefixes on the routes. There's also an issue where routes such as `password_path` don't work, and so you need to use `user_password_path` instead.

The error for `POST /user.sign_in` is because you've overriden Devise's `signup_path` helper by defining one inside your routes file. Inside `app/views/devise/registrations/_new.html.haml` change where it has `signup_path` to not pass an argument to this method so it uses the correct route.

**Comment by Akram-Khan** [comment]
Thanks for looking into the issue. The password_path issue is solved by adding main_app.user_password_path. 

However even after I remove the arguments of signup_path I start getting routing error for signup "ActionController::RoutingError (No route matches [POST] "/signup"):"

In case of Sign In when I remove the arguments from sign_in_path I get this error
"ActionController::RoutingError (No route matches [GET] "/assets/null"):"

I will look into it and will post the solution if I get it. I guess it should not have been so difficult to implement it I must be doing something really stupid here

**Comment by radar** [comment]
The problem seems to be with your heavy customization of Devise, more than anything to do with Forem.
