### ISSUE TITLE
Category stats include hidden topics for non-admin users

### ISSUE THREAD

**Issue by mahzilla** [rubysherpas/forem#132]
If there is a hidden topic in a forum, the Topics, Posts, and Views statistics for ForumsController#index and ForumsController#show are different if I view the forum as a non-admin user.

To replicate this issue, create a new forum, create a new topic, and then hide the topic.  You will see that the as a non-admin user, the newly create forum in ForumsController#index shows that a topic exists, but ForumsController#show will display "There are no topics in this forum currently."

**Comment by radar** [comment]
Without looking at the code I can confirm this is an issue (seriously). Would you be able to submit a patch to fix this? It should be in `app/views/forem/forums/_forum.html.erb`. It just needs to change to `forum.topics.visible.count` or something like that. Oh, and the posts will also need to be changed.

**Comment by mahzilla** [comment]
It was pretty easy to change the statistics in the view for topic count by adding `forem_admin? ? forum.topics.count : forum.topics.visible.count`, but I'm not quite sure how to change the models for posts or views to exclude the count for hidden parent topics.

**Comment by radar** [comment]
To do that you could add a new scope to both the `Forem::Post` and the `Forem::View` model also called `visible` that did something like this for `Forem::Post`:

``` ruby
def self.visible
  joins(:topic).where("topics.hidden" => false)
end
```

And a small change for `Forem::View`

``` ruby
def self.visible
  joins(:post => :topic).where("topics.hidden" => false)
end
```

With those two scopes you could implement the same thing as you've just done for the topics count.

**Comment by suciuvlad** [comment]
is this still open ?

**Comment by parndt** [comment]
@suciuvlad  it's still open but I have no idea if it's still an issue... @radar ?

**Comment by radar** [comment]
I believe this issue to be fixed now.
