### ISSUE TITLE
t('.topics') and others in view/forums/listing do not exist

### ISSUE THREAD

**Issue by juozasg** [rubysherpas/forem#135]
The locales file defines en.forem.forums.index.topics and other related keys. Meanwhile the _listing partial uses relative scope for .topic key that rails resolves to en.forem.forums.listing.topics. That key does not exist in the locales file. This is with Rails 3.1.3

I don't know if this is a bug, but simplest fix is to update the locales files to use 'listing' instead of 'index' scope. Let me know if this is right, I can create a patch.

**Comment by juozasg** [comment]
view/forem/forums/_forum also has the same issue with t('.last_post') so maybe absolute translation keys would be better?

**Comment by juozasg** [comment]
This commit fixes it (feel free to cherry pick if it works) https://github.com/juozasg/forem/commit/6ead83ba68f8f6f29bef095d1caf18cf99725b28

**Comment by radar** [comment]
Picked + amended to be @b8da9a6 (with closes message)

Thanks for taking the time to investigate+patch this!
