### ISSUE TITLE
Issues running migrations

### ISSUE THREAD

**Issue by maxx-coffee** [rubysherpas/forem#139]
Hello,

I have been running in to issues getting the migrations to run.  If i remove Forem.user_class = User  from he forem.rb initializer i can run the migrations.  If i leave them i get these issues:

Creating default forum and topic
/Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/bundler/gems/forem-28e0a626cb74/lib/forem.rb:13:in `user_class': You can no longer set Forem.user_class to be a class. Please use a string instead. (RuntimeError)

 See https://github.com/radar/forem/issues/88 for more information.
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/bundler/gems/forem-28e0a626cb74/db/seeds.rb:1:in `<top (required)>'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in`load'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `block in load'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in`block in load_dependency'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in`load_dependency'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `load'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/engine.rb:487:in`load_seed'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/bundler/gems/forem-28e0a626cb74/lib/generators/forem/install_generator.rb:85:in`seed_database'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/invocation.rb:118:in`invoke_task'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `block in invoke_all'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`each'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `map'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`invoke_all'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/group.rb:226:in `dispatch'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/generators.rb:168:in `invoke'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/commands/generate.rb:12:in`<top (required)>'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `require'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in`block in require'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in`new_constants_in'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in`require'
    from /Users/joshuacoffee/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/commands.rb:28:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

Any help with this would be appreciated.

Thanks
-Josh

**Comment by parndt** [comment]
If you do what the error message says and put this: 

Forem.user_class = 'User'

^ note the quotes.. then it should work. 

Did you create the forem.rb initializer or did we?

Thanks!

**Comment by radar** [comment]
Thanks for pointing this out. I've now fixed this in @8838be9. You can fix your application by editing `config/initializers/forem.rb` manually and changing the `Forem.user_class` configuration to be a string instead of a class object.

**Comment by parndt** [comment]
Ah, it was _our_ fault. Thanks, Ryan.

**Comment by radar** [comment]
No worries :)
