### ISSUE TITLE
Migrations differ in db/migrate to spec/dummy/db/migrate

### ISSUE THREAD

**Issue by parndt** [rubysherpas/forem#141]
@knewter @radar do you know why?

**Comment by knewter** [comment]
My guess is because spec/dummy/db/migrate shouldn't be in the repo in the first place.  I have other engines where I've pushed them up, and it's always been a mistake then.

**Comment by parndt** [comment]
Agree, I think we should refactor it out and make it a task instead.

**Comment by radar** [comment]
Please Do Investigate

**Comment by parndt** [comment]
Oh no he didn't

**Comment by ugisozols** [comment]
Please see #149.

**Comment by radar** [comment]
This is fixed in #149.
