### ISSUE TITLE
Python dependency

### ISSUE THREAD

**Issue by atavistock** [rubysherpas/forem#142]
It appears theres a python dependency in using forem by the inclusion of forem-redcarpet.

**Comment by radar** [comment]
Confirm :( Perhaps we shouldn't make forem-redcarpet a solid dependency and just have no formatting by default?

**Comment by atavistock** [comment]
Yeah, I would go with either no formatter or very minimal formatter, and document how to add redcarpet or other formaters.

**Comment by atavistock** [comment]
Actually I would even say any default formatter is fine, as long it doesn't increase the dependency chain to much.

**Comment by radar** [comment]
As part of the 1.0 release "things to do", we're going to change this syntax highlighting over to syntax.js, and still keep forem-redcarpet as a dependency, but remove the syntax highlighting from it.

**Comment by safarista** [comment]
Yeah it really screws things up a bit @radar I will check the progress on this. Good idea to lighten up the formatting.

**Comment by knewter** [comment]
you mean highlight.js now, right?

**Comment by radar** [comment]
Uh yes. Some highlighting library in JavaScript would be good :)

**Comment by parndt** [comment]
Do we still intend to fix this with JS? :)

**Comment by radar** [comment]
Probably not. Python is a light dependency and there's really no better library out there that I've seen written in JavaScript.
