### ISSUE TITLE
Feature: Recently Updated Posts

### ISSUE THREAD

**Issue by jgadbois** [rubysherpas/forem#143]
What do you guys think of having a filter to show only topics updated in the last day/week/etc (probably on an individual forum page)? 

I could build this if you like the idea.

**Comment by radar** [comment]
We're currently tracking people's "viewing habits" in `forem_views`. We could use the information in that table to create a page where they could see all posts to a forum since their last topic view.

I think seeing topics updated in the last day / week is obvious enough from the forums screen at the moment.

**Comment by jgadbois** [comment]
How about just a little "New" superscript text? If it's been created since their last topic view?

**Comment by radar** [comment]
Sure, that'll work too.

**Comment by jgadbois** [comment]
Hmm, actually - I was thinking a New superscript would look good for new topics since last view, but looks like only last view of topics is tracked, not last view of a forum so that isn't really feasible.

For topics, it looks like a "new" icon is already displayed if new posts have been added since last view of that topic (when viewing a forum).

Maybe none of this is necessary?  If you think it would be a good idea, we could make the views have a polymorphic association with topics and forums and track both maybe.

Thoughts?

**Comment by radar** [comment]
Walk me through how people would use that feature. I think they'd want to see all newest posts for a forum. Indicating which forums have new posts seems overkill to me.

**Comment by jgadbois** [comment]
Currently it works like follows:
- User visits a forum 
- User looks at the list of topics
- Topics that have been previously visited and have new posts added to them have a "new posts" icon.

I'm proposing:
- User visits a forum
- User looks at list of topics
- New _topics_ since last visit to the forum are marked as "new"

Maybe it is overkill, but seems useful for a moderator or user to visually see which topics are new.  Of course once you visited a topic in the forum and then hit the back button they are no longer new if the cache is busted so maybe it's not useful anyway.

I'm fine with doing a separate page too if you think that is more useful, but maybe that's not all that useful either.

**Comment by radar** [comment]
Ah, I see now. That makes total sense, thank you for taking the time to explain it.

You're right with describing the problem of hitting the back button on the forum. Here's what we can do:
1. Change `forem_views` to track forums and topics by using a viewable polymorphic association.
2. Create a new record in `forem_views` when a user views a forum.
3. During the user viewing the forum, we select the first view that was performed _greater than 15 minutes ago_ and get all topics posted after that. This would allow topics to remain showing as "new" for 15 minutes.

With this solution, If I viewed a forum yesterday and came back to it today, I would see all the new topics for 15 minutes no matter how many times I refreshed the page. 

Sound good?

**Comment by jgadbois** [comment]
Makes sense - once a topic is actually viewed, then we should not show that one as new though. So new topics are all topics posted more than 15 minutes ago and not actually viewed, right?

**Comment by radar** [comment]
Yes, that's right.

**Comment by jgadbois** [comment]
Probably a dumb question, but I added a concerns directory (app/model/concerns) with a Viewable module for some shared logic between topic and forum.  How do I tell the Rails Engine to autoload that directory?

**Comment by radar** [comment]
What is the exact file path there? If you had it at `app/models/concerns/viewable.rb`, the module would need to be called `Concerns::Viewable` for it to be autoloadable by Rails. If you don't want to do that, you could always put it at `app/concerns` and that way it would only need to be called `Viewable` and placed as `app/concerns/viewable.rb`.

**Comment by jgadbois** [comment]
Currently it's at
`app/models/forem/concerns/viewable.rb` and it's called `Forem::Viewable`

I just tried adding `config.autoload_paths << "#{Forem::Engine.root}/app/models/forem/concerns"` to `engine.rb`, but I'm still getting the following error:

`uninitialized constant Forem::Viewable (NameError)`

I'm trying to include it like this:

```
module Forem
  class Topic < ActiveRecord::Base
    include Forem::Viewable
```

Suggestions?

**Comment by radar** [comment]
Right, that won't work because when you reference `Forem::Viewable` it checks the autoload paths for the application and checks for something in them at `forem/viewable`. `app/models` is in those autoload paths, and so Rails will look for a file at `app/models/forem/viewable.rb` when you reference this constant.

If it's where you're saying it is, the constant needs to be  `Forem::Concerns::Viewable`. You shouldn't need to alter `autoload_paths` to do this.

**Comment by jgadbois** [comment]
That worked - thanks.  Also turns out that `Form::Engine.root` only gets me to the lib directory - not sure if that's the desired behaviour or not.

**Comment by jgadbois** [comment]
> 1. During the user viewing the forum, we select the first view that was performed greater than 15 minutes ago and get all topics posted after that. This would allow topics to remain showing as "new" for 15 minutes.

This is a problem - views are currently stored in one row per user (so we only know the last time the forum was viewed).  Should be simple to change logic to log a row per view if you think that is best.  Not sure what the reason for the one row was originally except maybe to keep the size of the table down.

**Comment by radar** [comment]
Ah, truth that is a problem. And yes, it was to keep the size of the table down. I wonder if this would be a problem on a large install if we did it that way.

**Comment by jgadbois** [comment]
Seems like it could definitely get huge pretty quick since it tracks forums and topics.  You could always have a rake task to prune, but that's more setup for the user. 

Might also be able to handle it with a session or cookie that expires in 15 minutes and knows the old value.

**Comment by jgadbois** [comment]
Any preference (or alternative idea)? A cookie would work and keep the table size down, but doesn't seem very clean.  Possible performance issues down the road from logging every view in it's own row.

**Comment by radar** [comment]
How about switching topics + posts to have a views_count field on them that is then incremented every time somebody views a forum or a topic?

I think we would need to have two fields in the views table then, one to track when was the last time they came to visit (`past_viewed_at`) and another to track the current time (`current_viewed_at`). If the current time field is within 15 minutes, we do nothing and then once past the 15 minute mark we set that value to past_viewed_at.

We can then query `past_viewed_at` to get all forums+topics that the user hasn't seen since > 15 minutes ago.

This would reduce the complexity of the views system, keep the `forem_views` table down to just one record p.er user and topic/forum pairing and allow us to show topics/forums that have new posts since a last visit.

**Comment by jgadbois** [comment]
I think that makes sense.  So views_count is just a counter_cache for the overall topic and post, am I understanding that correctly?  I think forem_views already has the count column for the individual user.

**Comment by radar** [comment]
Well, I don't think it should be a counter cache. It should just be a field that is incremented when people view. A counter cache would require a series of `forem_views` records to work, and we're not going to be doing that.

**Comment by jgadbois** [comment]
Ok yeah, I see what your saying, it's the sum of the view counts for each user.  Ok, I'll go that route.

**Comment by radar** [comment]
Thank you! Super appreciated!

**Comment by knewter** [comment]
@jgadbois do you want to turn that into a pull request?  Does it reflect the discussion that occurred here?

**Comment by jgadbois** [comment]
This can be closed I believe.  I think it was merged as part of https://github.com/radar/forem/pull/163

**Comment by knewter** [comment]
Okie doke, closing.
