### ISSUE TITLE
User class / name change issue

### ISSUE THREAD

**Issue by railsnoob9** [rubysherpas/forem#147]
How do we fix this? (sorry, we're forem/rails noobs)

forem.rb currently has:

Forem.user_class = User 

what should this be changed to? (or does something somewhere else need to be changed?)

**Comment by radar** [comment]
It should be set as a string, not a class.

**Comment by railsnoob9** [comment]
how? (sorry--i know it's a bad question)

**Comment by radar** [comment]
This is wrong:

``` ruby
Forem.user_class = User
```

This is right:

``` ruby
Forem.user_class = "User"
```

**Comment by railsnoob9** [comment]
that solved it--thanks lol
