### ISSUE TITLE
Use Gravatar for Avatars

### ISSUE THREAD

**Issue by radar** [rubysherpas/forem#15]
If the User model has an email method, we should use it to display gravatars of those people on the posts.

**Comment by parndt** [comment]
@radar Should we store the avatar or just hotlink gravatar each time?

**Comment by radar** [comment]
I believe GitHub hotlinks them and so if it's good enough for GitHub it's good enough for us.

**Comment by parndt** [comment]
I have this setup on the http://refinerycms.com/blog already so I can whip the code in. :)

**Comment by radar** [comment]
Ship it squirrel says:

![Ship it!](http://i.imgur.com/s7MRg.jpg)

Ship it!
