### ISSUE TITLE
Feature: Forum Search

### ISSUE THREAD

**Issue by jgadbois** [rubysherpas/forem#155]
I have users requesting this on my install of Forem.  I could implement a simple solution using a gem like https://github.com/ernie/ransack, but wanted to see if there was any better implementation ideas.

**Comment by radar** [comment]
I reckon an extension (like how Spree does it) would be the best for this. You could use thinking-sphinx, which offers great full-text support. There's also elastic search which has been getting a lot of praise recently.

**Comment by jgadbois** [comment]
Is this the extension you are referring to? https://github.com/romul/spree-solr-search

Full text search seems like the best way, but would that require extra config for users just looking for basic search functionality?

**Comment by radar** [comment]
Yes, something like spree-solr-search.

Indeed, that would require some configuration. If users want basic search then you could provide that through another extension that uses a gem like Ransack.

**Comment by jgadbois** [comment]
Sounds good I'll look into it.
