### ISSUE TITLE
forem-redcarpet YAML default key issue on REE

### ISSUE THREAD

**Issue by gabrielbaez** [rubysherpas/forem#158]
I just ran bundle update to get the latest changes and when I try to precompile the assets or do a rake migrate I'm getting a dependency error with forem-redcarpet  any ideas? 

Installing forem-redcarpet (1.0.0) 
Using simple_form (2.0.0) 
Using forem (0.1) from git://github.com/radar/forem.git (at master) 
Using forem-theme-base (0.0.1) from git://github.com/radar/forem-theme-base.git (at master) 
Using friendly_id (4.0.0) 
Using gravatar_image_tag (1.0.0) 
Using hashie (1.2.0) 
Using libv8 (3.3.10.4) 
Using metaclass (0.0.1) 
Using mocha (0.10.4) 
Using mysql (2.8.1) 
Using nifty-generators (0.4.6) 
Using omniauth (1.0.2) 
Using paper_trail (2.6.0) 
Using paperclip (2.7.0) 
Using pg (0.13.2) 
Using recaptcha (0.3.4) 
Using riddle (1.5.1) 
Using rspec-core (2.8.0) 
Using rspec-expectations (2.8.0) 
Using rspec-mocks (2.8.0) 
Using rspec (2.8.0) 
Using rspec-rails (2.8.1) 
Using sanitize (2.0.3) 
Using sass-rails (3.2.4) 
Using therubyracer (0.9.10) 
Using thinking-sphinx (2.0.11) 
Using truncate_html (0.5.3) 
Using uglifier (1.2.3) 
Using yui-compressor (0.9.6) 
Your bundle is updated! Use `bundle show [gemname]` to see where a bundled gem is installed.
ami@zeus [/home/ami/bohiti]# rake assets:precompile
Invalid gemspec in [/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/specifications/forem-redcarpet-1.0.0.gemspec]: Illformed requirement ["#YAML::Syck::DefaultKey:0xdec6488 2.0.1"]
Invalid gemspec in [/opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/specifications/forem-redcarpet-1.0.0.gemspec]: Illformed requirement ["#YAML::Syck::DefaultKey:0xdec6488 2.0.1"]
Could not find forem-redcarpet-1.0.0 in any of the sources
Run `bundle install` to install missing gems.

**Comment by radar** [comment]
More descriptive ticket titles please. (I updated it just then)

**Comment by gabrielbaez** [comment]
sorry about that,  I'm now trying the latest version of REE to see if it fixes the problem.   I ran into this problem with ruby-enterprise-1.8.7-2011.03 now trying ruby-enterprise-1.8.7-2012.02

**Comment by gabrielbaez** [comment]
Upgrading to the latest REE seems to fix the problem.

**Comment by radar** [comment]
Huge success!
