### ISSUE TITLE
Bundle install fails - forem specified twice

### ISSUE THREAD

**Issue by StevenMcD** [rubysherpas/forem#16]
Hi there,

I am still quite new to rails and especially bundler. I cloned the repository and added the entries you specified in the readme. When I try execute bundle install I get the following error: 

You cannot specify the same gem twice coming from different sources. You specified that forem (>= 0) should come from git://github.com/radar/forem.git (at master) and source at /projectPath/

From other examples I have found people mention duplication within the gemspec file which I do not see. Any ideas?

Thanks.

Steve

**Comment by radar** [comment]
Could you show me your `Gemfile` please? It looks to me like you've specified it twice. Just looking to confirm.

Oh, and it's my mum's wedding + Railscamp today / this weekend so I may be sporadically available.

**Comment by StevenMcD** [comment]
Here are the contents of the GemFile:

source "http://rubygems.org"
gem 'rails', :git => "git://github.com/rails/rails.git"
gem 'arel', :git => "git://github.com/rails/arel.git"
gem 'rack', :git => "git://github.com/rack/rack.git"
gem 'sprockets', :git => "git://github.com/sstephenson/sprockets"
gem 'forem', :git => "git://github.com/radar/forem.git"
gem 'forem-theme-base', :git => "git://github.com/radar/forem-theme-base"

gemspec

I have not altered the forem.gemspec file at all, so that's the same as in your repository. Enjoy the wedding and RailsCamp :)

**Comment by radar** [comment]
The problem could be that forem theme base points to a gem version or something like that? I am at railscamp and can't check that out at the moment but seems like a likely cause

**Comment by parndt** [comment]
Wait - you cloned the forem repository and edited the forem Gemfile ? Or you added those entries to your Rails application's Gemfile?

**Comment by StevenMcD** [comment]
I added the entries to the GemFile in the root of the forem project. Like I said above, I am a complete beginner so if I have made a monumental mistake, feel free to slap me down and laugh at me ;)

**Comment by parndt** [comment]
Ah - the instructions are for integrating Forem into a Rails project so the Gemfile entries should go into your Rails project :-)

**Comment by StevenMcD** [comment]
omg I am so stupid. I thought that was to setup the project so that I could actually work on the forem project itself. Thanks so much. Everything is working fine now.
