### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by ivoreis** [rubysherpas/forem#160]
hi there, i've installed the forem engine with the social_stream gem but i've got some problems with the views. 
when i access the domain.com/forums/ the controller will also render the social_stream views but will throw the NameError because of the non existence of the main_app prefix. 
My config/routes.rb look like this :
<code>
  mount Forem::Engine, :at => "/forums"
  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}
</code>

and my routes:
<code>
                   root        /                                                  forem/forums#index
  subscribe_forum_topic GET    /forums/:forum_id/topics/:id/subscribe(.:format)   forem/topics#subscribe
unsubscribe_forum_topic GET    /forums/:forum_id/topics/:id/unsubscribe(.:format) forem/topics#unsubscribe
           forum_topics GET    /forums/:forum_id/topics(.:format)                 forem/topics#index
                        POST   /forums/:forum_id/topics(.:format)                 forem/topics#create
        new_forum_topic GET    /forums/:forum_id/topics/new(.:format)             forem/topics#new
       edit_forum_topic GET    /forums/:forum_id/topics/:id/edit(.:format)        forem/topics#edit
            forum_topic GET    /forums/:forum_id/topics/:id(.:format)             forem/topics#show
                        PUT    /forums/:forum_id/topics/:id(.:format)             forem/topics#update
                        DELETE /forums/:forum_id/topics/:id(.:format)             forem/topics#destroy
                 forums GET    /forums(.:format)                                  forem/forums#index
                  forum GET    /forums/:id(.:format)                              forem/forums#show
</code>

Is there a way to fix this? Anyone had a similar problem? 

Thank you.

**Comment by radar** [comment]
What NameError? Please explain your problem better. If this is a problem because of the social_stream views you will need to raise an issue on that project. There's absolutely nothing we can do about it here.

**Comment by ivoreis** [comment]
hi @rader, 

I installed the social_stream gem as my base app and then installed the forem engine. 
when i try to access the route of the forem in /forums i got the error <code>NameError in Forem/forums#index undefined local variable or method `search_url' for class.... </code> This method search_url is a method of the main app social_stream and is called in <code> social_stream/base/app/views/layouts/_search.html.erb </code> file.

**Comment by radar** [comment]
Right, so you will need to ask the social_steam project to fix their views or fork it and fix it yourself. There's nothing we (the Forem team) can do here.

**Comment by ivoreis** [comment]
Ok, thank you
