### ISSUE TITLE
Kaminari vs WillPaginate

### ISSUE THREAD

**Issue by glebm** [rubysherpas/forem#166]
Forem does `require "kaminari"`, which causes the following to happen:

```
Creating scope :page. Overwriting existing method Forem::Category.page.
Creating scope :page. Overwriting existing method Forem::Topic.page.
Creating scope :page. Overwriting existing method Forem::Forum.page.
Creating scope :page. Overwriting existing method Role.page.
Creating scope :page. Overwriting existing method Listing.page.
Creating scope :visible. Overwriting existing method Listing.visible.
```

I especially don't like how it overwrites an existing scope `visible` on my `Listing` model.

Since Forem supports both kaminari and will_paginate, could we remove the `require`?

**Comment by radar** [comment]
Unfortunately it's not as simple as removing the `require` statement.  The dummy app would need to require it in order for the tests to not break.

**Comment by glebm** [comment]
Just tried, removing require didn't help, my guess is that it is being automatically required because of the gemspec

**Comment by radar** [comment]
Yup, Bundler.require would do it automatically. Weeeeee.

So what would happen if we were to remove it as a dependency of Forem entirely?

**Comment by glebm** [comment]
If it is removed entirely, then we would need to specify in the documentation that kaminari/wp should be added to the application Gemfile, which is not ideal

There might be a workaround though:

```
gem 'kaminari', :require => false
```

**Comment by radar** [comment]
It's specified as a gemspec dependency. I wasn't aware that you were able to do `:require => false` with that.

**Comment by glebm** [comment]
I don't know if you can, will check bundler source now

**Comment by radar** [comment]
Ah I see what you're saying, maybe. You could do this in your Gemfile:

``` ruby
gem 'kaminari', :require => false
gem 'will_paginate'
```

That would at least tell Bundler to not require kaminari. It's a slight hack though.

**Comment by glebm** [comment]
Just tried, Bundler still requires it

**Comment by radar** [comment]
:rageface:

Sorry, I don't know how to fix this problem right now.

**Comment by glebm** [comment]
How about

```
if !defined?(Kaminari) && !defined?(WillPaginate)
   raise "Please add gem 'kaminari' or gem 'will_paginate' to your gemfile?"
end
```

**Comment by radar** [comment]
Now that I've had a couple (read: eleven) hours to think about this, I reckon your idea is a pretty good one. Let's do it.
