### ISSUE TITLE
Two typos?

### ISSUE THREAD

**Issue by shadowbrush** [rubysherpas/forem#171]
config/initializers/session_store.rb:

 -Forums::Application.config.session_store :cookie_store, key: '_forums_session' 
 +Forums::Application.config.session_store :cookie_store, :key => '_forums_session'

config/initializers/wrap_parameters.rb:

 -ActionController::Base.wrap_parameters format: [:json]
 +ActionController::Base.wrap_parameters :format => [:json]
- Holger

**Comment by parndt** [comment]
I'm sorry but I don't understand. Those are files rails generates if you use MRI Ruby 1.9.x

**Comment by shadowbrush** [comment]
OK, sorry, I'm new to this. I had to make above changes to get it to run. I'll close the issue. Thanks!

**Comment by parndt** [comment]
No problem :-) thanks!
