### ISSUE TITLE
Is there a stable commit I should be using? I get strange errors...

### ISSUE THREAD

**Issue by eivindhagen** [rubysherpas/forem#175]
I started using forem a couple of weeks ago, before the moderation feature was added. It worked.

Now, on the latest master, I get some strange problems, like this one:

A NoMethodError occurred in categories#show:

 undefined method `forem_admin_or_moderator?' for #<#<Class:0x00000104ec6378>:0x00000104ebde08>
 /Users/eivindhagen/.rvm/gems/ruby-1.9.2-p0/bundler/gems/forem-cd2d6a399420/app/helpers/forem/forums_helper.rb:4:in`topics_count'

I also get access denied for categories#show even though my access method for that one always returns true:

```
def can_read_forem_category?(category)
  puts ">>>>>>>>>> can_read_forem_category?(#{category})"
  true
end
def can_read_forem_forums?
  puts ">>>>>>>>>> can_read_forem_forums?"
  true
end
def can_read_forem_forum?(forum)
  puts ">>>>>>>>>> can_read_forem_forum?(#{forum})"
  true
end
def can_create_forem_topics?(forum)
  puts ">>>>>>>>>> can_create_forem_topics?(#{forum})"
  !new_record?
end
def can_read_forem_topic?(forum)
  puts ">>>>>>>>>> can_read_forem_topic?(#{forum})"
  true
end
def can_reply_to_forem_topic?(topic)
  puts ">>>>>>>>>> can_reply_to_forem_topic?(#{topic})"
  !new_record?
end
def can_edit_forem_posts?(forum)
  puts ">>>>>>>>>> can_edit_forem_posts?(#{forum})"
  !new_record?
end
def can_moderate_forem_forum?(forum)
  puts ">>>>>>>>>> can_moderate_forem_forum?(#{forum})"
  forem_admin?
end
```

Notice all those puts statements? I don't see those in my log, so I suspect my methods are not even called!

I am tempted to go back to the pre-moderation version, unless someone can suggest a stable commit.
Thanks!

-Eivind

**Comment by radar** [comment]
If the [tests are all green](http://travis-ci.org/#!/radar/forem), then _that commit_ is a known stable commit. 

Please show us how we can duplicate the errors that you're seeing so that we can go about seeing if it is indeed a bug in Forem that we should fix.

Thanks.

**Comment by eivindhagen** [comment]
Hmm... I seem to be having this problem only on my local development machine (Mac OSX). When I deploy my app to an Ubuntu Linux host these problems do not occur. I will have to debug my local machine now.

Thanks for the Travis link, now I know how to tell if a commit is stable.

**Comment by radar** [comment]
Further information: we are looking at providing a strictly stable branch in the future. We are aware that master can _sometimes_ be unstable. We're just looking to nail down [some features](https://github.com/radar/forem/wiki/1.0-Roadmap) before creating this branch.
