### ISSUE TITLE
Issues setting up the dummy app

### ISSUE THREAD

**Issue by yan-hoose** [rubysherpas/forem#185]
Hi,

I'm having trouble setting up the dummy app to run tests. When I run:
`bundle exec rake forem:dummy_app --trace`

I get:
```** Invoke forem:dummy_app (first_time)
** Invoke forem:setup_dummy_app (first_time)
** Execute forem:setup_dummy_app
rake aborted!
undefined method`singleton_class' for Forem:Module
/var/lib/gems/1.8/gems/railties-3.2.1/lib/rails/engine.rb:388:in `isolate_namespace'
/home/user/Projects/test/forem/lib/forem/engine.rb:3
/home/user/Projects/test/forem/lib/forem.rb:1:in`require'
/home/user/Projects/test/forem/lib/forem.rb:1
./spec/lib/tasks/forem_spec_tasks.rake:7:in `require'
./spec/lib/tasks/forem_spec_tasks.rake:7
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `execute'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `invoke_prerequisites'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in`each'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:157:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`run'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/var/lib/gems/1.8/gems/rake-0.9.2.2/bin/rake:33
/var/lib/gems/1.8/bin/rake:19:in `load'
/var/lib/gems/1.8/bin/rake:19
Tasks: TOP => forem:dummy_app => forem:setup_dummy_app

```
I'm new to Rails engines and I think I'm missing something obvious here but not sure what. I'm using Ruby 1.8.7. 
Any suggestions on what to try to get the dummy app set up?
```

**Comment by parndt** [comment]
As an aside, is there any particular reason you're using 1.8.7 over something much newer like 1.9.3? :-)

@radar might know about the singleton_class issue based on: https://gist.github.com/1879321

**Comment by yan-hoose** [comment]
@parndt I started using Ruby Enterprise Edition 1.8.7 in my production environment a few years ago to get more performance and reduce the memory footprint (1.9.2 was not released yet). I just have not felt the need to upgrade but now as I'm reading some benchmarks, it seems that upgrading makes sense. 

If this exception is a 1.8.7-only issue, it might not be reasonable to try to fix it and I'll just upgrade Ruby.

**Comment by parndt** [comment]
I'm not sure if it's 1.8.7 specific :-)

**Comment by yan-hoose** [comment]
I installed RVM and 1.9.3 and everything works! 

So, what should be done with this issue - is it something that should be fixed or is it insignificant?

**Comment by parndt** [comment]
It should totally be fixed

**Comment by radar** [comment]
It's now totally fixed by @049057a8e94e59610365b6764c733eb7876c8351.

**Comment by parndt** [comment]
@radar wow! btw, isn't REE pretty much end of life? Shouldn't we test on 1.8.7 instead?

**Comment by radar** [comment]
"wow!" as in "wow! why didn't we think of this before?" :P Solutions are simple given enough time. Was just because that particular file from AS wasn't being automatically included.

I think both REE and 1.8.7 are reaching EOL. I would still keep testing on them for now, while the Rails version that we support supports these versions. When Rails 4 comes out, Forem will also no longer support Ruby 1.8.7 variaties, mainly because _it'll be impossible_.

**Comment by parndt** [comment]
@radar as in, I did not even think that we needed to extend the kernel ;-)
I'm all in favour of testing 1.8.7 in some way so +1
