### ISSUE TITLE
Some issues with links and permissions

### ISSUE THREAD

**Issue by vizakenjack** [rubysherpas/forem#188]
I use rails 3.2.3 and ruby 1.93. 

I have User model as default, but the links to users shows as #User:0xae09660. How can I fix it? I want to display it as @user.username, not just @user

Another question - how can I give access to read all forums and topics to non-logged users? I have tried to add this to User model:

```
 can_read_forem_forums?
    true
  end

can_read_forem_topic?(forum)
  true
end

can_read_forem_category?(category)
  true
end

can_read_forem_forum?(forum)
  true
end
```

But it didnt help too -(

**Comment by knewter** [comment]
Re: your link problems - sounds like you just need to define a to_s on your User model

**Comment by radar** [comment]
Define the to_s method on your User model to return username. 

As for the anonymous permissions thing, I'm not sure what's going on there. 

## 

Ryan Bigg
