### ISSUE TITLE
Rake db:migrate fails on install

### ISSUE THREAD

**Issue by rodleg** [rubysherpas/forem#189]
I've run into an issue when trying to install forem.  

It appears that the rake task fails during the install but doesn't generate any messages.  The installation task does not report any messages but seems to fail on the create_forem_categories.forem.rb migration.  When I manually rerun the migration I get an error that you "Can't mass-assign protected attributes: name" which is line 9 in the create_forem_categories.forem.rb migration. Commenting out this line and re-running the migration succeeds and completes all subsequent migrations. 

Thanks-in-advance.

**Comment by radar** [comment]
There's probably going to be more than just this one place where it's broken... will have to take a look at it a little later. If you'd like to help out, you could run the tests and fix the mass assignable issues as they crop up and submit those fixes as a pull request.

**Comment by jeremyongplaymesh** [comment]
Just noting here that I'm encountering an isomorphic issue.

==  CreateForemCategories: migrating ==========================================
-- create_table(:forem_categories)
   -> 0.0014s
rake aborted!
An error has occurred, this and all later migrations canceled:

Can't mass-assign protected attributes: name

**Comment by jeremyongplaymesh** [comment]
Ok so an easy temporary workaround is to comment out
    config.active_record.whitelist_attributes = true
in the application.rb file.

The issue is the rake db:migrate uses mass assignment internally which is banned by default in rails 3.2. See https://github.com/rails/rails/pull/4900

You may want to update the documentation to suggest this change prior to running the initial forem install.

Cheers.

**Comment by radar** [comment]
This should be dealt with in a better manner than commenting out some code. I would recommend fixing the category one and then run the test suite to find out what else is going wrong and go from there.

**Comment by parndt** [comment]
We made things attr_accessible a while back so should no longer be an issue.
