### ISSUE TITLE
clear fix

### ISSUE THREAD

**Issue by yx** [rubysherpas/forem#198]
add "< div style="clear: both;">< /div>" to /views/forem/posts/_post.html.erb (58 Line) for clear fix.

**Comment by radar** [comment]
Please submit a pull request for this.

**Comment by parndt** [comment]
Not exactly. Clear both does not fix in all browsers

**Comment by knewter** [comment]
Also, inline styles are yucky.  I typically put a .clear{} rule in the stylesheet and apply it to a div in the view.

**Comment by radar** [comment]
Agreed.
