### ISSUE TITLE
Current_user route helper

### ISSUE THREAD

**Issue by avitus** [rubysherpas/forem#199]
I have the following route helper in my application layout:

``` erb
<%= link_to t('menu.profile'), current_user %>
```

Is there a simple way to convert this so that it isn't stomped on by Forem? I've converted all the other route helpers successfully by prepending main_app.

I'm using Devise with Rails 3.2

**Comment by parndt** [comment]
@avitus does prepending `main_app.` not work in this case?

**Comment by avitus** [comment]
No. It doesn't seem to unless I'm missing something obvious.

**Comment by avitus** [comment]
This is the error message I see:

undefined method `current_user' for #ActionDispatch::Routing::RoutesProxy:0xd401ed0

This is the only route helper that has a problem. All the others transitioned over smoothly and I have everything up an running very smoothly. Looks like a really great engine but this one has me a bit stumped.

**Comment by parndt** [comment]
Oh right.... `current_user` isn't actually a route but a resource. Would it be something like this:

``` erb
<%= link_to t('menu.profile'), main_app.user_path(current_user) %>
```

**Comment by avitus** [comment]
I could have sworn I tried that but ... yes, that's it! 

Thanks for the help ... Forem is exactly what I was looking for!

**Comment by radar** [comment]
How is this being stomped on by Forem? Could you please explain?

**Comment by parndt** [comment]
@radar issue resolved I believe

**Comment by radar** [comment]
Oh I see. Silly github sending new issue notificiations but not comments!

**Comment by parndt** [comment]
I know! What's up with that?
