### ISSUE TITLE
Please install the sqlite3 adapter. Why?

### ISSUE THREAD

**Issue by safarista** [rubysherpas/forem#200]
safarista$ rails g forem:install
/safarista/.rvm/gems/ruby-1.9.2-p136@global/gems/bundler-1.0.14/lib/bundler/rubygems_integration.rb:143:in `block in replace_gem': Please install the sqlite3 adapter:`gem install activerecord-sqlite3-adapter` (sqlite3 is not part of the bundle. Add it to Gemfile.) (LoadError)

**Comment by safarista** [comment]
why is this happening?

**Comment by radar** [comment]
Your database.yml file in your application specified sqlite3. Thats why.

**Comment by safarista** [comment]
coolio :/ thanks

**Comment by safarista** [comment]
I have been digging into this and can't understand it. @radar Why is this a problem especially when deploying on heroku Cedar? 

And how can one fix  it since I don't know what my heroku production db configs are? Except that its running a pg deployment and won't install sqlite3 for toffee.

**Comment by radar** [comment]
Don't specify sqlite3 in either your database.yml or your Gemfile. Remove all reference to it.
