### ISSUE TITLE
Mass assignment protection fails tests

### ISSUE THREAD

**Issue by safarista** [rubysherpas/forem#204]
``` ruby
"forum"=>{"category_id"=>"1", "title"=>"Buying Land", "description"=>"This is the section you will buy if you want one.", "moderator_ids"=>["3", ""]}, "commit"=>"Create Forum"}
```

ERROR

``` ruby
ActiveModel::MassAssignmentSecurity::Error (Can't mass-assign protected attributes: category_id, title, description, moderator_ids):
```

The whole thing needs testing for mass assignment.

**Comment by parndt** [comment]
Are you able to help us to come to a solution? Thanks :)

**Comment by safarista** [comment]
I've forked it. I'll do pull request when I have something to show. Thanks
though.
On 24 Apr 2012 02:38, "Philip Arndt" <
reply@reply.github.com>
wrote:

**Comment by knewter** [comment]
Yeah, I saw it all failing yesterday so I made sure my Gemfile was looked to rails 3.2.1 since I didn't have time to fix it yesterday

**Comment by safarista** [comment]
Doesn't that mean you are carrying holes?
On 24 Apr 2012 09:02, "Josh Adams" <
reply@reply.github.com>
wrote:

**Comment by parndt** [comment]
Absolutely but we don't always have time to fix them straight away :(

**Comment by knewter** [comment]
in my defense, I'm presently hospitalized.  (yeah, I went there)

**Comment by jgadbois** [comment]
@safarista - are you going to be able to work on this soon?  If not, I can look at it today.

**Comment by knewter** [comment]
This was fixed with the above pull request, closing.

**Comment by safarista** [comment]
Sorry double post just in case.

Just had a look and this comes up. This pull seams to break 
URL: `http://localhost:3000/forums/forums/1/topics/new` 
ERROR `undefined method forem_auto_subscribe?' for #<User:0x000001285548e8>`

``` ruby
{"utf8"=>"✓",
 "authenticity_token"=>"3tTj+Kj3qZi4jhISeEG7aaT7QOlb/1CgX1Q9n3LrnyQ=",
 "topic"=>{"subject"=>"wasa",
 "posts_attributes"=>{"0"=>{"text"=>"mamamama"}}},
 "commit"=>"Create Topic",
 "forum_id"=>"4"}
```

Will have a dig but if anyone has time before tomorrow go ahead and dig. Thanks
