### ISSUE TITLE
lock, pin and hide topic links cause routing errors

### ISSUE THREAD

**Issue by ghost** [rubysherpas/forem#210]
Hello,
I am working on a project using forem with devise.
It all works well except lock, pin and hide topic links cause routing errors. For instance :

"No route matches [GET] "/forums/admin/topics/8/toggle_lock""

I checked the generated source of the page and it looks like it's ok :

```
<a href="/forums/admin/topics/8/toggle_hide" data-method="put" rel="nofollow">Hide this topic</a> | 
<a href="/forums/admin/topics/8/toggle_lock" data-method="put" rel="nofollow">Lock this topic</a> |
<a href="/forums/admin/topics/8/toggle_pin" data-method="put" rel="nofollow">Pin this topic</a>
```

I added this to the routes.rb :
  mount Forem::Engine, :at => "/forums"

Everything else works well, including the admin.
Do you have any idea what could cause this?

I'm using Rails  3.1.2 and ruby 1.9.3.

**Comment by radar** [comment]
It looks to me like you could be missing the jquery_ujs include from your application.js file, which should be included into your application's layout.

**Comment by ghost** [comment]
Thanks a lot for your answer. Indeed, the application js was not included for some reason. It works perfect now.
