### ISSUE TITLE
db:migrate fails because 2 migrations have the same name

### ISSUE THREAD

**Issue by ingus-t** [rubysherpas/forem#212]
Installation fails when it tries to run rake db:migrate fails because 2 migrations have the same name - _add_forem_state.

What is your user class called? [User] 
Adding forem_admin migration...
      create  db/migrate/20120427070280_add_forem_admin.rb
Adding forem_state migration...
      create  db/migrate/20120427070281_add_forem_state.rb
Adding forem_auto_subscribe migration...
      create  db/migrate/20120427070282_add_forem_state.rb

Installation creates 2 migrations with same name and fails when running rake db:migrate

**Comment by PendragonDevelopment** [comment]
Did you ever get this working? Should be fixed in #213.

**Comment by ingus-t** [comment]
Yes. Closing the issue.
