### ISSUE TITLE
Integration with RefineryCMS generator error

### ISSUE THREAD

**Issue by PendragonDevelopment** [rubysherpas/forem#214]
I'm attempting to integrate Forem into an existing RefineryCMS installation, and I can't seem to get rails g refinery:forem to work correctly. I'm not sure if it's a Refinery error or a Forem error, but I posted here first. 

The exact error I get when I run the command in terminal is:

`$ rails g refinery:forem
c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/activesupport-3.2.3/lib/act
ive_support/dependencies.rb:251:in `require': no such file to load -- refinery/g
enerators (LoadError)
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/activesupport-
3.2.3/lib/active_support/dependencies.rb:251:in `block in require'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/activesupport-
3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/activesupport-
3.2.3/lib/active_support/dependencies.rb:251:in `require'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/bundler/gems/forem-
6702447bd1e9/lib/generators/refinery/forem_generator.rb:1:in `<top (required)>'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/activesupport-
3.2.3/lib/active_support/dependencies.rb:251:in `require'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/activesupport-
3.2.3/lib/active_support/dependencies.rb:251:in `block in require'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/activesupport-
3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/activesupport-
3.2.3/lib/active_support/dependencies.rb:251:in `require'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/railties-3.2.3
/lib/rails/generators.rb:298:in `block (2 levels) in lookup'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/railties-3.2.3
/lib/rails/generators.rb:294:in `each'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/railties-3.2.3
/lib/rails/generators.rb:294:in `block in lookup'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/railties-3.2.3
/lib/rails/generators.rb:293:in `each'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/railties-3.2.3
/lib/rails/generators.rb:293:in `lookup'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/railties-3.2.3
/lib/rails/generators.rb:151:in `find_by_namespace'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/railties-3.2.3
/lib/rails/generators.rb:168:in `invoke'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/railties-3.2.3
/lib/rails/commands/generate.rb:12:in `<top (required)>'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/activesupport-
3.2.3/lib/active_support/dependencies.rb:251:in `require'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/activesupport-
3.2.3/lib/active_support/dependencies.rb:251:in `block in require'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/activesupport-
3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/activesupport-
3.2.3/lib/active_support/dependencies.rb:251:in `require'
        from c:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/railties-3.2.3
/lib/rails/commands.rb:29:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'`

Not sure I've done something wrong.

Side note: on the wiki for the Refinery integration, it's not entirely clear when I'm supposed to run those steps. I've tried to run rails g refinery:forem after bundle install, and separately after a bundle install and rails g forem:install. I'm on my third fresh install here, just so I'm not getting conflicts (hopefully).

**Comment by parndt** [comment]
I think the generator is out of date. Cc @ugisozols

Note: refinery/generators doesn't exist anymore

**Comment by PendragonDevelopment** [comment]
I wondered if this was the issue. I'm still a beginner with Ruby/Rails, but I tried making changes akin to one of the issues that Refinery-Inquiries had with the generators, but I don't think I did it correctly.

**Comment by ugisozols** [comment]
Yes, the generator is way out of date and there's no actual use case for it.

**Comment by PendragonDevelopment** [comment]
So what's the best way to move forward? Should I look at other extensions
and hack around a bit, then get some reviews here?
On Apr 30, 2012 1:34 AM, "Uģis Ozols" <
reply@reply.github.com>
wrote:

**Comment by ugisozols** [comment]
Since Forem and Refinery are both separate engines you can use both of them in your app by just mounting them at different paths:

``` ruby
# in routes.rb
Rails.application.routes.draw do
  mount Refinery::Core::Engine, :at => "/"
  mount Forem::Engine, :at => "/forum"
end
```

**Comment by PendragonDevelopment** [comment]
Okay, cool. I'll give that a try later and see if I run into any issues.
Thanks!
On Apr 30, 2012 6:51 AM, "Uģis Ozols" <
reply@reply.github.com>
wrote:
