### ISSUE TITLE
Conditionally load jquery.autocomplete?

### ISSUE THREAD

**Issue by jgadbois** [rubysherpas/forem#216]
I'm already including jquery ui in my app so including jquery.autocomplete forces me to load extra js.  Is there a good way to remove this?  Maybe just a copy:assets task so it's easy to override on a per-app basis?

**Comment by radar** [comment]
You could simply place a blank file in your application at the same path: `vendor/assets/javascripts/jquery.autocomplete.js`. That would cause the asset pipeline to include the empty void inside that file, rather than all that JavaScript.

**Comment by jgadbois** [comment]
That works, thanks.
