### ISSUE TITLE
How to add assets to main app?

### ISSUE THREAD

**Issue by anguyen-elc** [rubysherpas/forem#217]
I tried to have `//= require forem` in the main app application.js but it seems the assets/javascripts/forem.js.erb in Forem engine does not contain `//= require_tree .`. Should it contain that line to support asset pipeline of Rails? For more info, I am running Rails 3.2 and Ruby 1.9.2.

**Comment by parndt** [comment]
@radar @knewter  what do you think about this feature?

**Comment by radar** [comment]
Not sure what @anguyen-elc is trying to do here. What's the the use case?

**Comment by radar** [comment]
Closing this issue as the user has not replied in over a month.
