### ISSUE TITLE
Using modified views in production (on Heroku)

### ISSUE THREAD

**Issue by abrambailey** [rubysherpas/forem#218]
Hello. I have modified the view files heavily and pushed my project to heroku.. However, the modified views are lost in production and the formatting returns to standard engine formatting. Have I missed a configuration option somewhere?

**Comment by radar** [comment]
No, there is no configuration option to miss. If you truly have the views inside your application and have committed them to Git and pushed them to Heroku then they will be overridden.

**Comment by abrambailey** [comment]
I did have the forem views inside my app, edited.. but it definitely did not work. I was able to fix the problem by forking the project.. changing the views.. and pointing to my fork.

**Comment by radar** [comment]
This is not the way to fix the problem. Do you have the application somewhere that we can investigate?
