### ISSUE TITLE
Formatting posts

### ISSUE THREAD

**Issue by abrambailey** [rubysherpas/forem#220]
I'm having a problem with html formatting.

Inside of _post.html.erb you will find this line: `<%= forem_format(post.text) %>`

However, when I view a post I see the html in the output.. for example if I input `<b> HI </b>` I see that exact line in the output.

I did try installing the RedCloth gem and then put `<%= RedCloth.new(post.text).to_html %>` This did not produce an error, but unfortunately I still see only `<b> HI </b>` in the output.

**Comment by parndt** [comment]
Is the output not HTML safe?

**Comment by abrambailey** [comment]
If I put `<%= forem_format(post.text).html_safe %>` I still see `<b> HI </b>` in the output =(

**Comment by parndt** [comment]
cc @radar

**Comment by abrambailey** [comment]
Hey I just fixed it with <%= RedCloth.new(post.text).html_safe %> For some reason I'd used .to_html before in my RedCloth call.

**Comment by safarista** [comment]
I just use markdown straight forward. Had problems with python dependency.
