### ISSUE TITLE
Anonymous user sees unmoderated posts.

### ISSUE THREAD

**Issue by abrambailey** [rubysherpas/forem#221]
When I view a Forem 'topic' without being logged in I can see unmoderated posts. Should this be happening?

**Comment by parndt** [comment]
No it shouldn't be happening.

**Comment by abrambailey** [comment]
When I log in the unmoderated posts disappear. I don't get it.

**Comment by parndt** [comment]
I think the logic sounds exactly backwards.

**Comment by abrambailey** [comment]
Well, the unmoderated posts disappear when they should.. 

If user A is moderater, user B is the poster, and user C is browsing the forum.. only user A and B can see the unmoderated post. User C would not see it... So this seems like normal behavior.

**Comment by parndt** [comment]
Correct, the way you just explained it sounds perfect.

**Comment by abrambailey** [comment]
What I don't get is why everything is working normally except logged out browsers seeing unmoderated posts.

**Comment by parndt** [comment]
@funkdified sounds like a bug in the logged out case. cc @radar @knewter

**Comment by abrambailey** [comment]
By the way, Hello Christchurch. Auckland here.

**Comment by parndt** [comment]
Ah, so we're both working on our Saturdays :-) Shame on us! ;)

**Comment by abrambailey** [comment]
Double shame on me: http://www.sitecam.co.nz/auckland_webcam/

**Comment by parndt** [comment]
Haha - at least it's overcast here.

**Comment by abrambailey** [comment]
By the way, I have forked the forem gem and modded to fit in with a twitter bootstrap styling. Feel free to use. git@github.com:funkdified/forem.git

**Comment by abrambailey** [comment]
Cool thanks anyway, I'll wait for @radar to have a look at the issue.

**Comment by parndt** [comment]
Oh, bootstrap couldn't be implemented using forem's theming?

**Comment by abrambailey** [comment]
Well, I personally like the look better with my mods.

**Comment by abrambailey** [comment]
Hey Philip, and idea how to make forem approve posts by default?

**Comment by artem-mindrov** [comment]
There's one more thing about this: if someone has just started a topic and the opening post is awaiting approval, the topic still shows on the forums page having the most recent post. When a user navigates to this topic, however, she gets a 'topic you're looking for could not be found'. Moreover, when the post is approved, this behavior doesn't change because even though the post is now in an approved state, its associated topic is still pending approval.

**Comment by radar** [comment]
I believe this is fixed now. Please let us know if there's any more trouble with it.
