### ISSUE TITLE
email integration

### ISSUE THREAD

**Issue by elf-pavlik** [rubysherpas/forem#222]
i don't like using forums which don't have option to post from email... i haven't tried this gem yet but maybe it could help:
https://github.com/titanous/mailman

here you can find related railscast:
http://railscasts.com/episodes/313-receiving-email-with-mailman (not freely shared!)

**Comment by safarista** [comment]
Fair enough, but most people host on heroku. Forem really needs/is undergoing a major redesign. Would you care to contribute a pull request?

**Comment by parndt** [comment]
Please open a pull request if you wish to contribute this feature :) thanks!
