### ISSUE TITLE
Any way to auto-subscribe admins and moderators to all posts?

### ISSUE THREAD

**Issue by artem-mindrov** [rubysherpas/forem#232]
I'm using Forem [here](http://www.tunxten.com). Thanks for the work done on this!
I'm wondering if there is a way for admins to receive notifications on all events by default, and for moderators to get notifications on events in the forums they moderate.
Currently I'm using Google Analytics for this kind of event reporting, but this is about as convenient as monitoring the all forums directly. This is not a big deal now when I don't have very much activity, but can become an issue when/if discussions grow.

**Comment by radar** [comment]
No, this feature is currently not supported. What I would recommend to do is to add a decorator for the `Forem::Post` model that would send out notifications every time a post has been created.
