### ISSUE TITLE
The action 'index' could not be found for Forem::TopicsController

### ISSUE THREAD

**Issue by artem-mindrov** [rubysherpas/forem#233]
Googlebot has recently started producing this exception when crawling my site. Weird thing is that I did never add the topic index route to the sitemap, but still the bot wants to fetch it. I'm wondering if something like `resources :topics, :except => :index` could fix this (probably not, haven't checked). Doesn't excluding the non-existent action from the route map seem like a good idea anyway?

**Comment by parndt** [comment]
If the action doesn't exist we shouldn't route to it cc @radar

**Comment by radar** [comment]
There's nowhere that we're routing to this action, other than in the form to create a new topic, which is only visible if you're signed in. Unless I'm missing something?

**Comment by parndt** [comment]
Thanks for doing the PDI :-) Seems like a non issue then?

**Comment by radar** [comment]
Yeah, unless it can be reliably reproduced by something other than a hearsay report.

**Comment by murtazajafferji** [comment]
After creating a topic, I got this same error.

**Comment by radar** [comment]
@murtazajafferji Please provide exact steps to reproduce this. This is a very commonly tested scenario by our test suite, which is currently passing.

**Comment by murtazajafferji** [comment]
I was not signed in, I tried to create a topic, I was redirected to the sign_in_path, I signed in, I was redirected to the index page and got this error:
<code>The action 'index' could not be found for Forem::TopicsController</code>

**Comment by radar** [comment]
> exact steps

I need to know what buttons precisely you pressed so that I can reproduce the issue myself.

**Comment by murtazajafferji** [comment]
1. I was not signed in.
2. I filled in the fields of the form for <code>forem/topics/form</code>
3. I clicked on the submit button called "Create topic" from <code>forem/topics/form</code>
4. I was redirected to <code>sign_in_path</code>
5. I signed in.
6. I was redirected to the index page.

Note that I removed <code>before_filter :authenticate_forem_user</code>

**Comment by radar** [comment]
You removed the filter from where?

**Comment by murtazajafferji** [comment]
Normally, you'd be creating a topic from <code>forem/topics/new</code> and the <code>before_filter :authenticate_forem_user</code> would happen before the new action. However, I moved <code>forem/topics/form</code> outside of the Forem engine and I did not include the filter.
