### ISSUE TITLE
Forem can't access custom variable in db

### ISSUE THREAD

**Issue by etjossem** [rubysherpas/forem#239]
My team and I introduced a new variable to the forem_forums table (called "admin_only") which - in conjunction with can_create_forem_topics?(forum) in the [authorization system](https://github.com/radar/forem/wiki/Authorization-System) - successfully prevents non-admins from creating announcements in designated announcement forums. They can, of course, still comment on these announcement threads if we choose not to lock them.

We then created a checkbox in views/admin/forem/forums/_form to set the boolean admin_only to 1, and got the following error during tests:

```
Can't mass-assign protected attributes: admin_only
```

Is there a good way to override forums_controller.rb or one of the models? We'd like to make our custom variable admin_only accessible to our installation of Forem without resorting to a full fork.

**Comment by radar** [comment]
You would need to create a decorator for the `Forem::Forum` class to add `attr_accessible` to this.

Put this code inside your application class inside `config/application.rb`:

``` ruby
config.to_prepare do
  Dir.glob(File.join(File.dirname(__FILE__), "../app/**/*_decorator*.rb")) do |c|
    Rails.configuration.cache_classes ? require(c) : load(c)
  end
end
```

And then inside `app/models/forem/forum_decorator.rb`, put this code:

``` ruby
Forem::Forum.class_eval do
  attr_accessible :admin_only
end
```

That will then add `admin_only` to the list of accessible attributes, while still preserving the initial attributes.

**Comment by parndt** [comment]
Wow, I'll disregard my fully written reply ;-) Thanks @radar 

I do wish Rails would add first class support for decorators.

**Comment by etjossem** [comment]
Thanks so much, @radar. Worked like a charm.
