### ISSUE TITLE
Issue running tests

### ISSUE THREAD

**Issue by kamarcum** [rubysherpas/forem#24]
I cloned this repo a little bit ago, but I had some trouble running the tests. Steps to reproduce:
1. New gemset
2. git clone
3. bundle
4. rake -> failures because no db tables exist
5. rake db:create -> Don't know how to build task 'app:db:create'
6. rake -T -> db:setup and db:create both exist
7. rake db:create -> failure
8. rake db:setup -> failure
9. head scratching
10. grep -r database .
11. spec/dummy/config/database.yml -> aha!
12. cd spec/dummy; rake db:create db:migrate; cd ../..; rake -> only a few failures!
13. cd spec/dummy; rake forem:install:migrations db:migrate; cd ../..; rake -> no failures!
14. post github issue so others can work though this more easily
15. await suggestions as to what I can do to help

**Comment by parndt** [comment]
I have trouble getting testing to work out of the box too!

**Comment by grigio** [comment]
me too

**Comment by parndt** [comment]
It seems the steps are:

``` bash
bundle exec rake -f spec/dummy/Rakefile db:drop db:create db:migrate
bundle exec rspec spec
```

Taken from [the travis config](https://github.com/radar/forem/blob/master/.travis.yml#L1).

It would be nice if running `rake` from the project did this for us or maybe this information could go in the README better. Would appreciate any and all patches that did this!! :-)

**Comment by radar** [comment]
The steps I use are similar to Phil's except I need to run the `db:test:prepare` task instead:

`bundle exec rake -f spec/dummy/Rakefile db:drop db:create db:migrate db:test:prepare`

This is a _one time_ run thing, and once that's done then I run `bundle exec rspec spec` or `bin/rspec spec` or just `ber spec` (that's my alias) to run the tests.
