### ISSUE TITLE
Duplicate Migrations on Install Error

### ISSUE THREAD

**Issue by GeekOnCoffee** [rubysherpas/forem#241]
If the install errors out (issue with devise or whatever) the installer generates the migrations again.

**Comment by etjossem** [comment]
[This](http://stackoverflow.com/questions/686852/rolling-back-a-failed-rails-migration) may be helpful.

**Comment by GeekOnCoffee** [comment]
@etjossem the issue is that the migration files are actually getting created a second time

**Comment by parndt** [comment]
That's bizarre - Rails should be preventing that. Is the generator using rake railties:install:migrations (or the specific one for Forem) ?

**Comment by GeekOnCoffee** [comment]
https://github.com/radar/forem/blob/master/lib/generators/forem/install_generator.rb#L39

It doesn't appear to be doing any checks on whether it exists...

**Comment by parndt** [comment]
Oh; I had assumed Forem was doing it intelligently like https://github.com/resolve/refinerycms/blob/master/core/lib/generators/refinery/cms/cms_generator.rb#L197-L202

I guess not ;-)

**Comment by parndt** [comment]
@GeekOnCoffee I believe this is no longer an issue since the changes by the wondeful @jzahnd
