### ISSUE TITLE
Please add miniand.com to "Places using Forem" list

### ISSUE THREAD

**Issue by beefsack** [rubysherpas/forem#247]
Hi,

I've implemented Forem as part of my website at miniand.com, specifically at https://www.miniand.com/forums.  I've build the site using twitter bootstrap, and I've customised the forum views to use that.  I'm using a Markdown formatter to format posts.

Cheers!

**Comment by knewter** [comment]
Holy crap, I was actually on those forums _yesterday_ and didn't recognize that it was forem.  I saw a post on HN about the device running puppy linux and another post elsewhere re: ubuntu, so I checked it out.  Coincidences are crazy.

Done...
