### ISSUE TITLE
Running migrations rollback, column "datetime" of relation "forem_views" does not exist

### ISSUE THREAD

**Issue by nebiros** [rubysherpas/forem#249]
Error running `bundle exec rake db:rollback --trace`:

```
PG::Error: ERROR:  column "datetime" of relation "forem_views" does not exist
: ALTER TABLE "forem_views" DROP "datetime"
```

Full log: http://pastie.org/private/blodkpvfiuvf5bdsumhlja

**Comment by radar** [comment]
This issue is now fixed with @7e26a786a70968975d29b63d086120f1c76bf3bb. Thanks!
