### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by jasonlfunk** [rubysherpas/forem#252]
I installed Forem and it looks great. The only issue that I am having is that none of my normal routes seem to exist inside of the Forem section of the site. I was unable to use my shared navigation bar because it said the routes didn't exist.

Is there anyway around this?

**Comment by jasonlfunk** [comment]
Never mind. I figured it out. Thanks :)

**Comment by parndt** [comment]
Prepend your routes with main_app.

**Comment by radar** [comment]
Please share some code examples. Can't debug without a way to reproduce the problem;
