### ISSUE TITLE
Segregated Groups

### ISSUE THREAD

**Issue by bryanerayner** [rubysherpas/forem#258]
Is it implemented to segregate different forum categories based on values from an Active Record model? I am trying to use this to manage a forums for people in probably 20 or so separate networks - one forum per network, each with identical categories and subthreads... It would be nice to somehow be able to have forem do this for me. How would you recommend proceeding?

**Comment by radar** [comment]
You can override the `can_read_forem_category?` method inside your `User` model to then query an ActiveRecord model to determine if the user can/can't access that category.

Is that what you mean?
