### ISSUE TITLE
Users can see moderation radio buttons on their own posts

### ISSUE THREAD

**Issue by etjossem** [rubysherpas/forem#259]
When a post is pending approval, the user who wrote it can see the radio buttons, not just the message explaining moderation. If permissions are set properly, they won't be able to use them, so these radio buttons are unnecessary. In the example below, Bob-O is the current user, a non-admin who has just made a post:

![Screencap of issue](http://imagebin.org/index.php?mode=image&id=220108)

Ideally, he should only see a "pending approval" message, not Approve, Spam, or Moderate.

**Comment by parndt** [comment]
Yes the radio buttons do seem unnecessary. Are you able to pull-request them away please? :-)

**Comment by radar** [comment]
I am unable to reproduce this issue. [The spec here](https://github.com/radar/forem/blob/e8fc464a3d732f16e61b3d019ea9daf99671d837/spec/requests/moderation/new_users_spec.rb#L23-34) should be enough to replicate this issue. You can see that the radio buttons are not output on the page  by putting a `page!` anywhere after the `click_button "Reply"` call.

Perhaps the user is a moderator?

**Comment by etjossem** [comment]
That doesn't seem right. Bob-O can't actually approve his own post (meaning he's not a mod), and I didn't change anything in his permissions from default. Is it just me or is it just radar?

**Comment by radar** [comment]
Probably Radar.

**Comment by radar** [comment]
What version of Forem are you using @etjossem? I still can't reproduce the bug this morning.

![Forums](https://img.skitch.com/20120711-p3s8cx2jdp6nihtd6ewnxpuxeb.png)

**Comment by etjossem** [comment]
Gemfile: `gem 'forem', :git => "git://github.com/radar/forem.git", :branch => "master"`
Bundle install output: "Using forem (1.0.0.beta1) from git://github.com/radar/forem.git (at master)"

**Comment by radar** [comment]
What does it say in Gemfile.lock? 

## 

Ryan Bigg

**Comment by etjossem** [comment]
Wups, should have checked there first.

```
GIT
  remote: git://github.com/radar/forem.git
  revision: 93728d5d33938a095e4453196bb5cb9992727b2a
  specs:
    forem (1.0.0.beta1)
      cancan (= 1.6.7)
      forem-redcarpet (= 1.0.0)
      rails (~> 3.1)
      simple_form
      workflow (= 0.8.0)
```

**Comment by etjossem** [comment]
In the post view:

```
    <% if post.pending_review? %>
      <div class='moderation'>
        <%= t(".pending_review") %>
        <% if local_assigns[:mass_moderation] %>
          <%= render "forem/posts/moderation_tools", :post => post %>
        <% else %>
          <%= form_tag forum_moderate_posts_path(post.topic.forum), :method => :put do %>
            <%= render "forem/posts/moderation_tools", :post => post %>
          <% end %>
        <% end %>
      </div>
    <% end %>
```

**Comment by radar** [comment]
You're using an older version of Forem, one that was "released" on July 6th. Have you tried replicating this problem with the latest commits?

**Comment by etjossem** [comment]
Looks like a change since 93728d5d addresses this issue. Thanks.

**Comment by radar** [comment]
Alright, great to hear. Thanks!
