### ISSUE TITLE
friendly_id for nice slugged urls

### ISSUE THREAD

**Issue by juozasg** [rubysherpas/forem#262]
Would there be interest in including friendly_id to make all the url human (and search engine) friendlier? I can implement this feature and create a pull request if maintainers are interested. I'm planning to include this in my own project and would prefer this was part of forem. 

Any requests/preferences for implementation? I would like to add the friendly_id dependency to forem Gemfile and add the slug column to forums, categories and topics tables. Is that a good idea? Alternatively, I could create a new gem forem-friendly_ids that monkeypatches these models and generates migrations if that is the road you prefer. I would prefer to include it in core forem to make it simpler and this is a feature I imagine pretty much everyone would like.

**Comment by juozasg** [comment]
I've seen https://github.com/radar/forem/pull/192 also, but that's 3 months ago.

**Comment by radar** [comment]
How would it work with legacy links? I would assume it would work fine, right?

**Comment by parndt** [comment]
Yes that would be wonderful @juozasg 

@radar yes legacy links still work fine - it just allows slugs to work too. You can simultaneously find things by id or by slug with FriendlyId.  Why yes I do help to maintain it.

**Comment by radar** [comment]
PDI @juozasg.

**Comment by juozasg** [comment]
Ok, here's the pull request. Specs pass and it seems to work fine with my own app. https://github.com/radar/forem/pull/264
