### ISSUE TITLE
How to use main_app cancan in layout file?

### ISSUE THREAD

**Issue by hk6500** [rubysherpas/forem#265]
Since forem uses its own ability.rb, i can't see any restricted links from my applications layout file.
Is there a way to use cancan in forem with my main_app's ability.rb?

``` haml
%ul#nav
    -if can? :manage, :all
        %li= link_to 'Admin', main_app.admin_index_path
    -elsif can? :update, current_user
        %li= link_to 'Profile', main_app.user_home_path

```

**Comment by radar** [comment]
Not right now, but we could probably add [something like the `register_ability` method that Spree has](https://github.com/spree/spree/blob/master/core/app/models/spree/ability.rb#L17-19).

That way we could then register "foreign" abilities with Forem's Ability class.

**Comment by hk6500** [comment]
sounds great for me!

**Comment by radar** [comment]
Ok then, please write a patch to add this feature into Forem if you'd like it.

**Comment by radar** [comment]
Please open a new pull request when you have the code for this fix done.
