### ISSUE TITLE
Using decorators to override actions doesn't seem to work

### ISSUE THREAD

**Issue by bdensmore** [rubysherpas/forem#266]
I'm trying to override some controller actions in the forums_controller and it doesn't seem to be picked up.

I'm trying to add a new action to display some added information but it's not working.

I've created the following:

/app/decorators/controllers/forem/forums_controller_decorator.rb

For testing purposes just to see if this was working I just added the following filter to see if I can display it in the forums show view. This is what I have in the forums_controller_decorator.rb file:

``` ruby
Forem::ForumsController.class_eval do
  before_filter :find_a_user

  protected

  def find_a_user
    @name = "ben"
  end

 end
```

The `@name` instance variable always remains nil.

Am I not using this the correct way or is this truly a bug?

**Comment by parndt** [comment]
Just to confirm - are you using the absolutely latest up to date code that has decorators support? It was only added in the last few days.

**Comment by bdensmore** [comment]
My Gem file is pointed at gem 'forem', :git => "git://github.com/radar/forem.git" and 1.0.0.beta1 is what is displayed if I do a bundle update. I believe I am using latest.

**Comment by parndt** [comment]
Support was added in #260 so maybe it's not perfect. cc @kunalchaudhari @radar

**Comment by bdensmore** [comment]
But I am extending the controller the correct way, right? 

I was questioning me more than I was questioning the code in the gem. I understand this is still a beta so things may not work as intended. I just wanted to make sure I wasn't trying to implement this incorrectly. But if it is indeed a bug, hopefully this helps a little bit.

**Comment by parndt** [comment]
Yes the code itself looks fine to me.

**Comment by radar** [comment]
The code is wrong.

**Comment by radar** [comment]
Fixed with @0fc9bae. Thanks for playing!

**Comment by parndt** [comment]
I meant the code in this ticket :p

**Comment by kunalchaudhari** [comment]
Prev was worked for me as I forgot to remove the to_prepare block from my app. My mistake :P

**Comment by kunalchaudhari** [comment]
thanks @bdensmore playing with it and @radar for fixing. cool.

**Comment by jvvlee** [comment]
Hello, I seem to be having the same problem. But I can't even get the server to run.
Here's what I have:

```
Forem::ApplicationController.class_eval do
    def setup_application_variables
        @section = Node.find_by_un(:networking_section)
        @node = @section.children.first.child(:page, "discussion_forum")
    end

    before_filter setup_application_variables
end
```

It's throwing an error saying:

`undefined local variable or method `setup_application_variables' for Forem::ApplicationController:Class (NameError)`

I placed this in app/decorators/controllers/forem/application_controller_decorator.rb, along with a base_controller_decorator.rb that contains nearly identical code except namespaced to "Forem::Admin::BaseController." I apologize if I'm missing something obvious here.

I'm using rails 4.1.8, with ruby 2.1.2

**Comment by radar** [comment]
That should be before_filter :setup_application_variables. You're missing the colon.

**Comment by radar** [comment]
In future, please file new issues instead of resurrecting old ones.
