### ISSUE TITLE
Trouble accessing Forem models

### ISSUE THREAD

**Issue by mattwd7** [rubysherpas/forem#267]
Hello!  I have been playing with Forem for a couple weeks now and learning a great deal about rails all along the way.  I am interested in generating a partial that will contain a list of the newest topics on my site's homepage outside of the forum.  In my quest, I have been having the most frustrating time generating a simple list containing all of the topic subjects that exist within all forums in my database.  I am not sure how I can access the topics model outside of Forem controllers and even in my tampering with Forem controllers I have not been able to generate this "master list" of topics within Forem.  Please help!

**Comment by radar** [comment]
Would you please provide an example of how you've been attempting to access the models? Thank you.

**Comment by mattwd7** [comment]
I have this controller that makes creates an instance variable containing all of the forum topics here:

<pre>
class NavigationController &lt; ApplicationController
def newest_topics   
@topics = Topic.all
    
respond_to do |format|
format.html
end
end
</pre>


and the view that spits out a list of the topic subjects is this basic code: 

<pre>
&lt;% @topics.each do |t| %>
&lt;%= t.subject %>&lt;/br>
&lt;% end %>
</pre>


Before I get to the view, this error craps out:

<pre>uninitialized constant NavigationController::Topic</pre>

which indicates to me that "Topic" is not recognized by my controller as a model.
I am pretty new at this with only ~150 hours experience so any advice is warmly welcomed :)

**Comment by radar** [comment]
The models within Forem are namespaced to be inside the `Forem` module. Therefore you will need to reference them with a fully-qualified name: `Forem::Topic`.

They may be referenced as simply `Topic` inside the engine itself because the references to them are already inside the `Forem` module.

**Comment by mattwd7** [comment]
Hell yes, it's working!  That's super intuitive too.  Thanks, Radar!
