### ISSUE TITLE
links to forums index using /forums/forums/

### ISSUE THREAD

**Issue by alexnesbitt** [rubysherpas/forem#276]
I'm not sure what the intended routes are but this seems to be creating a duplicate route for the forum index action.

The code in the _head.html.erb views
    <%= link_to t('forem.forum.forums'), forem.forums_path %> &raquo; <%= link_to forum.category, [forem,     forum.category] %> &raquo; <%= link_to forum.title, [forem, forum] %>

generates a link to /forums/forums/ for the first link.  I think it should link to /forums/ and route to the index.

I change forem.forums_path to forem.root_path and it seems to fix this.

**Comment by parndt** [comment]
On the face of it, this is because you have forem mounted at /forums

@radar should this behave any differently?

**Comment by alexnesbitt** [comment]
That is correct.  I think it also means that if I had forem mounted at / the views would link to /forums instead of /.

**Comment by radar** [comment]
You are right, this should be `root_path` and not `forums_path`. I've fixed this with the above commit.

**Comment by mbhnyc** [comment]
On a related note, is there a way to avoid the double-forums-route on viewing a particular forum?  Like a catch-all route that checks for a forum and displays?

It would be great to avoid this:

```
http://0.0.0.0:3000/forums/forums/default
```

Far better would be :

```
    http://0.0.0.0:3000/forums/default
```

On a side note, on the first path above is where i'm getting a current_user undefined local variable error, on this line:

```
    <div class='started-by'><%= t "started_by" %><%= relevant_posts(topic).first.user %></div>
```

changing user to provider (my custom class, set in the initializer) has no effect.

**Comment by radar** [comment]
Please explain this better and show examples of where this is happening  

## 

Ryan Bigg

AselOn Friday, 10 August 2012 at 2:04, mbhnyc wrote:

**Comment by alexnesbitt** [comment]
I'm not sure about the second part of the question, but here's a link to a page that shows the double-forums route: http://bit.ly/NbRhHM

**Comment by radar** [comment]
Right.

The way to fix that would be to define a catch-all route at the bottom of `forem`'s routes file that re-defines `forum_path` to point to that. The problem with that is that you'd need to be careful that the forum's permalink doesn't clash with any other route in forem.

**Comment by mbhnyc** [comment]
Created a new "issue" so as not to clutter this one :)

@radar : Could we adjust the permalink slug to minimize the collision chance? Like a wordpress-esque permalink that includes the post date or some such?  I can take a shot at a patch if we can agree on a format :)  I've barely research this so far, what's the current permalink format?

**Comment by parndt** [comment]
Currently it is based off the title parameterized

Hello World
hello-world
