### ISSUE TITLE
Auto_Subscribe migration looks like it's checking for the wrong column

### ISSUE THREAD

**Issue by alexnesbitt** [rubysherpas/forem#278]
Is this migration supposed to check for the existance of forem_admin or for forem_auto_subscribe?

https://github.com/radar/forem/blob/master/db/migrate/20120616193448_add_forem_auto_subscribe.rb

class AddForemAutoSubscribe < ActiveRecord::Migration
  def change
    unless column_exists?(user_class, :forem_admin)
      add_column user_class, :forem_auto_subscribe, :boolean, :default => false
    end
  end

  def user_class
    Forem.user_class.table_name.downcase.to_sym
  end
end

**Comment by radar** [comment]
You're right, it's checking for the wrong column. Could you please submit a patch to fix that?

**Comment by alexnesbitt** [comment]
I submitted a pull request with the change to the file. Hope I did it right.
