### ISSUE TITLE
Issues running migrations during upgrade of existing system

### ISSUE THREAD

**Issue by dwillett** [rubysherpas/forem#282]
I think https://github.com/radar/forem/issues/270 was just a subset of the migration issues when applying to an existing forem system.

I also experienced errors in AddCategoryIdToForums, as my Forem::Forum.count is greater than 0, but no Forem::Category objects have been created yet. My workaround was create a default category before the conditional:

``` ruby
ActiveRecord::Base.connection.execute %Q{INSERT INTO forem_categories (name, created_at, updated_at) VALUES ("Default", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)}
```

I couldn't use the model create command because the model expects 'slug' to be defined on Forem::Category

After this workaround I had an error from AddForemTopicsLastPostAt, again because 'slug' was expected to be defined on topic when issuing the update attribute. I worked around this with SQL as well, replacing the update_attribute call with:

``` ruby
ActiveRecord::Base.connection.execute %Q{UPDATE forem_topics SET last_post_at = "#{post.updated_at}" WHERE id = #{t.id} LIMIT 1}
```

Probably better ways to do this.

**Comment by radar** [comment]
I believe this is now fixed on the latest Forem.
