### ISSUE TITLE
issues installing the gem

### ISSUE THREAD

**Issue by gillesmathurin** [rubysherpas/forem#283]
Hello, i am trying to use forem into a rails 3.2.7 application with ruby-1.9.2-p320. But when i try to run bundle install after added :
gem 'forem', :git => "git://github.com/radar/forem.git"

i get this error : 

Bundler could not find compatible versions for gem "ffi":
  In Gemfile:
    forem (>= 0) ruby depends on
      ffi (~> 1.0.7) ruby

What can i do to make forem use the ffi version 1.1.4 which is used by other gems in my gem file ?

**Comment by Papipo** [comment]
Try with "bundle update" instead of "bundle install"

**Comment by gillesmathurin** [comment]
Apparently i solved my issue by commenting out the gem "capybara" mention i had in my :development and :test group, then by doing a "bundle update". As a consequence ffi passed from version 1.1.4 to version 1.0.11 (which is not a very good move i guess). I changed the cancan gem version in forem.gemspec to the latest version (1.6.8) by the way. All this has been done on a fork of this project
