### ISSUE TITLE
NameError in Forem/forums#show

### ISSUE THREAD

**Issue by mbhnyc** [rubysherpas/forem#284]
New issue from my earlier comment:

I'm getting a name error when opening the topic view here:  app/views/forem/topics/_topic.html.erb...created a sample post in the "general" category, and when I click on the "Default" link (which leads to app/views/forem/topics/_topic.html.erb) the error above is displayed.  Opening the topic itself works fine.  The URL at the non-working route is: http://0.0.0.0:3000/forums/forums/default

Full error:

```
Showing /Users/xxx/Projects/xxx/source/Main/app/views/forem/topics/_topic.html.erb where line #18 raised:
undefined local variable or method `current_user' for #<#<Class:0x007fd8e246b4b0>:0x007fd8e2409bc0>
```

Here's my initializer, nothing fancy.

```
Forem.user_class = "Provider"
Forem.avatar_user_method = :photo
Forem.per_page = 20
```

Other than that, the only customization i've done is installing the views.

**Comment by radar** [comment]
Sorry about that, my fault. I've fixed this now with @2dbb3881d2ede4c4e7fc922875058f0f21281e02.
