### ISSUE TITLE
Localization doesn't work well

### ISSUE THREAD

**Issue by gillesmathurin** [rubysherpas/forem#285]
Hi,
Even when the application "config.i18n.default_locale = :fr" is set, the forem engine doesn't followand stays in english
On the contrary i don't have the issue in development environment
Did i miss some configuration options in the forem initializer ? Is there any to enforce the choosen locale ?

Thanks

**Comment by radar** [comment]
You can set `config.i18n.default_locale = :fr` in your `config/application.rb` to default the locale for your entire app to French.

There isn't a way to do this just for the Forem engine at the moment.

**Comment by gillesmathurin** [comment]
thanks for your answer. Yes as a matter of fact, i eliminate Forem as a probable source of the localization issue i have. I just have localization issue in general in production environment
