### ISSUE TITLE
Make first post approval optional

### ISSUE THREAD

**Issue by naps62** [rubysherpas/forem#289]
Currently every new user has to have it's first post manually approved by a moderator.

I think it would be very useful for this to be just an optional behavior. For instance, i'm currently developing an app where i don't want this feature. with the current behavior, i'll have to clone the repo and disable this

I suppose this shouldn't be too hard to implement.

**Comment by parndt** [comment]
How would you feel about tackling this implementation too?

**Comment by naps62** [comment]
Yeah, though i mentioned that in the post, seems i forgot. sorry for that

i'll try to look into it, and see if i can get it done properly. But since my time right now is not really that much i might just need to skip that and simply disable the post approval for my app

but of course, i'll see what i can do in the next few of days

**Comment by sheam** [comment]
Is is possible to just alter the DB so that the default value for forem_status is 'approved'? I also need the ability to turn off this feature.

**Comment by parndt** [comment]
Sure to set it to approved by default simply:

```
rails generate migration change_default_value_for_forem_status_to_approved
```

edit the migration and put

``` ruby
change_column :forem_posts, :forem_status, :string, :default => 'approved', :null => false
```

..or very similar..

**Comment by naps62** [comment]
The approach i tried was to add a before_save filter to both Post and Topic
model's, to mark the post as valid automatically upon creation. I also
added a flag to an initializer file, so that it would at least be
configurable somehow.

In practise it works, but it made a lot of the tests fail, mostly due to
the fact that those tests were made assuming that every new post will be
pending validation. So it was more of an issue of the tests making wrong
assumptions, rather than the tests failing due to any kind of application
error

But if you don't mind about the tests failing (or you have the patience to
refactor them) it's a viable option

Later, if i find it useful for my project, i'm thinking of using something
like rails-settings-cachedhttps://github.com/huacnlee/rails-settings-cached

to make this and other behaviours configurable in the admin interface

On Thu, Sep 6, 2012 at 3:07 AM, Philip Arndt notifications@github.comwrote:

> Sure to set it to approved by default simply:
> 
> rails generate migration change_default_value_for_forem_status_to_approved
> 
> edit the migration and put
> 
> change_column :forem_posts, :forem_status, :string, :default => 'approved', :null => false
> 
> ..or very similar..
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/radar/forem/issues/289#issuecomment-8320164.

## 

Cumprimentos
Miguel Palhas

**Comment by yan-hoose** [comment]
I've managed this by just setting the forem_status in DB to "approved" by default. Works nicely.

**Comment by knewter** [comment]
is there a plan for what we want to do here?  I really do feel that this is the sort of thing that should be offered in engine configuration, rather than just a 'oh yeah, set default value in your migrations...'

**Comment by radar** [comment]
I would love to make it a configurable option but I don't have the time to do that right now.

**Comment by knewter** [comment]
Righto, just wanted to provoke minimal documentation on the hivemind/collective agreement on whether this was or wasn't a feature that forem needed to add.  Having 9 solid minutes to think about it, it occurs to me that with configurability 'thur be dragons' as edge cases asplode exponentially...

**Comment by radar** [comment]
Done. Finally.

Set `Forem.moderate_first_post = false` if you don't want the moderation.
