### ISSUE TITLE
Won't work with Refinery CMS, also other set-up errors

### ISSUE THREAD

**Issue by cobalamin** [rubysherpas/forem#29]
"Refinery CMS Integration
Requires Refinery CMS rails-3-1 branch"

There is no such branch there. Probably, it has been removed. And now, I can't get it wo work with Refinery. Using the latest thing of everything brings up loads of dependency errors (marginal note: I had to use the rack-1.3 branch of the git rack to get bundler to finish at all).
It's also possible that the reason is that my single steps were wrong or in wrong order. But yet, the "Refinery CMS Integration" entry doesn't tell much what to do.
I am now trying to set it up like the installation entry tells me to and posting everything that happens...

To get a refinery cms app:

> refinerycms blah
> (does loads of stuff, works.)
> Now to add forem, I put this in the Gemfile, as given:

gem 'rails', :git => "git://github.com/rails/rails.git"
gem 'arel', :git => "git://github.com/rails/arel.git"
gem 'rack', :git => "git://github.com/rack/rack.git", :branch => "rack-1.3"
gem 'sprockets', :git => "git://github.com/sstephenson/sprockets"
gem 'forem', :git => "git://github.com/radar/forem.git"

And change 
gem 'refinerycms',              '~> 1.0.3'
to
gem 'refinerycms', :git => "git://github.com/resolve/refinerycms.git"

and do:

> cd blah
> bundle install

It tells me:
Could not find gem 'rack (~> 1.3.2)', required by 'rails', in any of the sources

So I change the rack Gemfile entry, adding the :branch option:
gem 'rack', :git => "git://github.com/rack/rack.git", :branch => "rack-1.3"

and run

> bundle install
> again.

Output is:
Could not find gem 'refinerycms-generators (~> 1.1), required by 'refinerycms', in any of the sources

=> do this:
gem 'refinerycms-generators', :git => "git://github.com/resolve/refinerycms-generators.git"

And get this:
Bundler could not find compatible versions for gem "refinerycms-generators":
  In Gemfile:
    refinerycms depends on
      refinerycms-generators (~> 1.0.1)

```
refinerycms-generators (1.1.0)
```

So apparently, refinerycms will screw up its dependencies when it comes to using edge versions of rails etc.

And yes, I post this as a forem issue, because it apparently doesn't work what's given there in the instructions. ;)

Please fix! Great work though, I haven't seen any other forum that even tries to easily integrate with RefineryCMS, still, you outclass the other rails 3 forums in this case, guys.

Cheers!
Simon

**Comment by radar** [comment]
Wow, thanks so much for the detailed bug report! I will look into this right away.

**Comment by radar** [comment]
Looks to be an issue with refinerycms edge, I'll let @parndt know and we'll sort it out. Thanks again :)

**Comment by knewter** [comment]
simon,

it probably won't be a really painless integration until refinery 1.1 comes out because of the issues in refinery edge gemspecs currently.  I can tell you, I've got 3 sites deployed that integrate a refinerycms membership engine (not quite the default one) and forem, and it _does_ work after fiddling.  But yeah, it's not yet _quite_ drop-in easy :)  We're working on it, and thanks for the detailed bug report.

**Comment by cobalamin** [comment]
Sure, guys, I hope it's working soon! I really love RefineryCMS the way it is and would also love to easily integrate a forum, so I don't mind helping you :)
@knewter: Has your work anything to do with your fork of refinerycms which contains two versions of refinerycms 3-1 branches? I think I have tried with those, too, but it didn't bring me much further... D:

**Comment by cobalamin** [comment]
Oh, sorry, clicked on "close" accidentally.

**Comment by knewter** [comment]
@pommesgabel: You can find a gist here for a working refinery master / forem integration.  It's got stuff in it you don't need, I've tried to delete them in the most recent edit of the gist: https://gist.github.com/1116121

I think the biggest hurdle atm is refinerycms-generators and seo_meta, which should be fixed with this Gemfile.

Anyway, just so you know it's not a very tough setup right now, it's just not the sort of thing I'd want to document, rather than just waiting for refinerycms 1.1 to come out :)  If you're interested in playing with the bleeding edge, this should get you on your way :)

**Comment by parndt** [comment]
(with my refinerycms hat on) we are officially very interested in forem and will be taking great pains to ensure the next version of Refinery CMS has perfect compatibility. Having said that, it's hard to make the edge easy to install. :-) (this is pretty much what @knewter has already said, but wanted to reiterate it).

**Comment by cobalamin** [comment]
Just a small comment on the guide given how to set up forem: 
I'm not using refinery at the moment, and well, the Gemfile modifications as given won't work, but you can easily fix it by using this:

gem 'rails', :git => "git://github.com/rails/rails.git", :branch => "3-1-stable"
gem 'arel', :git => "git://github.com/rails/arel.git"
gem 'rack', :git => "git://github.com/rack/rack.git", :branch => "rack-1.3"
gem 'sprockets', :git => "git://github.com/sstephenson/sprockets"
gem 'forem', :git => "git://github.com/radar/forem.git"

so, as you see, using branches two times. the rails gem's branch because the current edge version there is already 3.2.x, and this had brought up other issues for me...
and the rack gem's branch because rails 3.1.x requires a rack 1.3.x version, apparently.

Just sayin', it really confused me at first, and I guess it's gonna change soon anyways, when a rails 3.1 rc will get the "c" removed and be the next release.

**Comment by radar** [comment]
I think this will be overcome by the release of Rails 3.1, which is _supposed_ to be next week. I wouldn't go changing it now when that release is so close. If people have trouble with it they can contact any one of us and we'll show them the way.

Thanks for reporting it though!

**Comment by frankel** [comment]
Finally Rails 3.1 is released!

If I integrate forem to RefineryCMS, what should I set to "Forem.user_class"?  "User" doesn't work.

**Comment by parndt** [comment]
::Refinery::User

**Comment by frankel** [comment]
Thanks parndt!

But I am still stuck by setting "forem_admin". Don't know where to configure this value. 

Wish one day there would be a more detailed guide for RefineryCMS integration.

**Comment by parndt** [comment]
By the time the next version of RefineryCMS that supports forem is released there will be. 

Right now I have too many things in my todo list to write one :(

**Comment by frankel** [comment]
After check this issue https://github.com/radar/forem/issues/31 , I still cannot prevent error of "undefined method `forem_admin?'" 

parndt, help!

**Comment by cobalamin** [comment]
You'll need to implement that forem_admin? function in some helper and include that helper file in all cases you use it. In my very own application, I included SessionsHelper in ApplicationHelper, so it will be available from everywhere. Then define the function returning some boolean value of whether the current user is an admin or not. IDK if this applies fully to RefineryCMS, haven't used it lately...

e.g. this would be my basic implementation:
  def signed_in?
    !current_user.nil?
  end

  def admin?
    signed_in? && current_user.admin?
  end

**Comment by frankel** [comment]
Thanks pommesgabel.

Finally, it needs to add forem_user field to Refinery::User model, and it works.

**Comment by radar** [comment]
Is this all fixed now lads?

**Comment by juozasg** [comment]
I had a some trouble getting the two of them to work together. The first issue was constant log warnings by `kaminari` (new pagination gem) about it overriding .page methods with it's own scope. I couldn't find any way at all of preventing them (might be possible by adjusting load order of things) so I ended up creating my own fork of forem that only uses `will_paginate`

A more serious problem was that pagination in forem was broken using `will_paginate` view helper (which you must use if you use Refinery anyway since that's Refinery's default and only pagination). The problem was only visible after 20 topics have been created. I had to add the following snippet to a new initializer file in my own code to overwrite `refinerycms/core/config/initializers/will_paginate_monkeypath.rb`. The commented out near the bottom is what I changed.

``` ruby
# from refinerycms/core/config/initializers/will_paginate_monkeypath.rb
module WillPaginate
  module ActionView
    class LinkRenderer < ViewHelpers::LinkRenderer
      def url(page)
        @base_url_params ||= begin
          url_params = merge_get_params(default_url_params)
          merge_optional_params(url_params)
        end

        url_params = @base_url_params.dup

        add_current_page_param(url_params, page)
        url_params.delete(:page) if url_params[:page] == 1

        # @template.main_app.url_for(url_params)
        @template.url_for(url_params)
      end
    end
  end
end 
```

It all seems to work after this.

**Comment by radar** [comment]
Sorry, could you explain what problem that monkey patch is solving? You don't go into much detail about how it's broken, so I just don't understand how that's the case. Interested to learn so that we can fix it.

**Comment by juozasg** [comment]
I have no idea why Refinery has the monkey patch there. I just took their patch and changed one line so it uses all routes for `url_for` including engines instead of just main app routes.

Also, `url_params.delete` is my own hack to not have `?page=1` param anywhere.

**Comment by radar** [comment]
Ah sorry, that's from Refinery. Right then. I will need to consult with them and figure out why that is necessary.

**Comment by radar** [comment]
About the kaminari message: You will have to speak to the kaminari maintainer for that. https://github.com/amatsuda/kaminari

**Comment by parndt** [comment]
I'm about to completely removed the will_paginate_monkeypatch from Refinery.

**Comment by knewter** [comment]
@parndt what's the rory story on this issue these days?

**Comment by parndt** [comment]
No idea, do you know?

**Comment by knewter** [comment]
I do not.  We run pretty specific versions of both projects in production at present :-\

**Comment by parndt** [comment]
Maybe @ugisozols knows

**Comment by ugisozols** [comment]
We still need that monkeypatch for will_paginate to work with refinery's url scope. There's an [open PR](https://github.com/mislav/will_paginate/pull/172) in will_paginate repo which would allow us to remove that monkeypatch but as you can see it's still not merged in.

Tbh I haven't investigated this issue well enough and maybe there's more easy way to fix this.

**Comment by parndt** [comment]
I put a patch into spreefinery in an initializer https://github.com/parndt/spreefinery that handles Kaminari plus Will Paginate

**Comment by radar** [comment]
Forem now no longer includes Kaminari. The application _must_ include one or the other. 

Would this fix get around this issue?

**Comment by ugisozols** [comment]
I was too lazy to read through all this thread but is this still an issue?

**Comment by juozasg** [comment]
Thanks for removing kaminari dependency. I'm not seeing new issues with the versions of forem and refinery I'm using. I've got a brief question related to this: what are your plans for including these changes in 1-0-stable branch or when do you plan updating 1-0-stable? Just curious cause I need to customize forem more and would like to know what branch to base my work on.
