### ISSUE TITLE
JS -> CoffeeScript

### ISSUE THREAD

**Issue by glebm** [rubysherpas/forem#292]
I, for one, would be glad to have CoffeeScript in forem.
JavaScript code leaks global variables in almost every commit, CoffeeScript would help avoid at least that.

Forem JS fixed and rewritten as CoffeeScript (this is from a 5 months old version of forem):
- https://github.com/glebm/forem/blob/stuff/app/assets/javascripts/forem_admin.js.coffee.erb
- https://github.com/glebm/forem/blob/stuff/app/assets/javascripts/forem/admin/members.js.coffee

**Comment by radar** [comment]
I'd gladly accept a patch for this. Would you be able to submit it?

**Comment by parndt** [comment]
I for one would like to see Jasmine tests in place for complete JS
changes like this..

**Comment by knewter** [comment]
@heath get on this k guy :) :) :)
