### ISSUE TITLE
Isolated namespaces and app internal links

### ISSUE THREAD

**Issue by Povkys** [rubysherpas/forem#293]
Hello,

having trouble with layouts. In current app I'm using links like: 
<%= link_to("My Items", :controller => 'items', :action => 'list') %> 
etc.

And these links are available in layouts (menu bar for example).

So, as Forem is using isolated namespaces these links does not work. Any chances them to get work without adjusting Forem gem?

**Comment by radar** [comment]
You should be using named routes instead. Hash arguments are the ancient way.

Use `main_app.items_path`. I assume here you have resources :items in your routes.
