### ISSUE TITLE
Helpers are not working

### ISSUE THREAD

**Issue by nyku** [rubysherpas/forem#298]
After installing , no one of heplers are working ,so i got routing errors on links.
I'm trying to integrate forem gem into my website.

Routing Error
No route matches {:controller=>"books", :locale=>:ru}
Try running rake routes for more information on available routes.

**Comment by radar** [comment]
You need to use `main_app` prefix:

``` ruby
main_app.books_path
```

Please read the [Engines Guide](http://guides.rubyonrails.org/engines.html) to find out more information.
