### ISSUE TITLE
Theme not applying.

### ISSUE THREAD

**Issue by prasadrails** [rubysherpas/forem#299]
I have installed as a gem "gem 'forem-theme-base', :git => "git://github.com/radar/forem-theme-base.git"

add line css fille :
= require "forem/{theme}/style"

In layout
<%= stylesheet_link_tag "forem/{theme}/style" %>

But not applying any theme, not appearing any styles.

Thanks in advance,
Prasad.

**Comment by radar** [comment]
The instructions aren't meant to be taken so literally. Sorry for any confusion there. What we mean is that in the CSS you should do this:

```
= require "forem/base/style"
```

And then in the layout, this:

``` erb
<%= stylesheet_link_tag "forem/base/style" %>
```

**Comment by 3kingsdev** [comment]
not working on my side.. just add the 

application.css
= require "forem/base/style"

application layout
<%= stylesheet_link_tag "forem/base/style" %>

**Comment by radar** [comment]
@3kingsdev: again: need a much better problem description than just what you've tried

**Comment by 3kingsdev** [comment]
i try to install 
gem 'forem-theme-twist', :git => "git://github.com/radar/forem-theme-twist.git"

i did is i put it on gemfile and bundle install 

then add 
application.css
= require "forem/base/style"

application layout
<%= stylesheet_link_tag "forem/base/style" %>

not change thanks for the help.. sorry for bad english also

**Comment by trestles** [comment]
any update on this issue ^^ The theme doesn't seem to be pulled in. Probably an issue with how I'm doing it. Maybe docs need to be more explicit about how to do this.

**Comment by radar** [comment]
Please show us the steps you used to attempt to pull in the theme. We cannot debug a problem without seeing how you got there in the first place!

**Comment by trestles** [comment]
Sure, thx in advance - I know this is probably a user (me!) error.

ok - so I followed the directions for main forem and that is working fine. Went to wiki page https://github.com/radar/forem/wiki/Theming.  To add a theme:
1.  I added to gemfile:

gem 'forem-theme-orange', :git => "git://github.com/radar/forem-theme-orange.git"
1. ran `bundle install`
2. restarted server, opened up http://localhost:3001/forums/; no css changes, checked in Chrome debugger

I suspect that there is a step here I need to do

Result:
![no-css](https://f.cloud.github.com/assets/536536/162630/4e9aee84-77c5-11e2-87ef-de21e9595f8c.png)

**Comment by pickhardt** [comment]
I suspect you have to add these lines to your application.css file:

 *= require "forem/base/style"
 *= require "forem/base/iphone"

Unfortunately, I also added these lines to my CSS file and am getting the error: couldn't find file 'forem/base/style'

When I used the "twist" theme it worked, however it also took over my existing site's style (changed my header to blue, for example), so I want to use the most basic "base" theme and then modify it on my own.

**Comment by chrismeier** [comment]
@pickhardt, I had the same issue as you. I solved it by creating a file in /app/assets/stylesheets called forem.css.scss (make the file extension(s) constant with the other files). You then can add the lines you initially put into the application.css file into that file. So it should look like:

``` js
/*
 *= require "forem/base/style"
 */
```

@radar if I want to use the forem-bootstrap theme, how would I change my application.css file and the line for the engine? `Forem.theme = :base`

@trestles I don't know if you did this but you need to follow the rest of the instructions in setting up the theme like a rails engine. I did this by making a file called forem-theme.rb within /config. I then added the lines suggested in the instructions:

``` ruby
require 'forem'
module Forem
  module Theme
    module Base
      class Engine < Rails::Engine
        Forem.theme = :base
      end
    end
  end
end
```

**Comment by radar** [comment]
@chrismeier You just need to add the forem-bootstrap gem as a dependency and then include the CSS file it provides. There should be nothing else to do after that.
