### ISSUE TITLE
how do I add members to groups?

### ISSUE THREAD

**Issue by sheam** [rubysherpas/forem#301]
when I go to admin/groups/1 the add button is disabled. If I hit enter, it seems to accept my input anyway (bug?). 

Using an email, then hitting enter, it seems to be adding the user to the group, but I then get a missing template exception:
Missing template forem/admin/members/create, forem/application/create, application/create

There doesn't seem to be any documentation around the groups feature...

**Comment by giedriusr** [comment]
:+1: I am facing with exactly the same issue and didn't get any feedback so far :/

**Comment by bodrovis** [comment]
Seems to be fixed: https://github.com/radar/forem/pull/373
