### ISSUE TITLE
haml views for forem ?

### ISSUE THREAD

**Issue by prasadrails** [rubysherpas/forem#305]
My current application using haml. Shall I get haml views for this.

Thanks in Advance,
Prasad.

**Comment by knewter** [comment]
+1 :)

**Comment by radar** [comment]
Besides a cleaner syntax, haml doesn't offer anything over using just plain ERB. Going along with what @parndt said [here](https://github.com/radar/forem/pull/297#issuecomment-8293425):

> I am in favour of not introducing more dependencies if it is just syntactic sugar.  If we need to do something that [gem] can do and [default] can't then it is a different story but I don't think this is the case.

So no, sorry.

**Comment by parndt** [comment]
Sweet statement I wrote!
