### ISSUE TITLE
postageapp-ruby setup with forem ?

### ISSUE THREAD

**Issue by prasadrails** [rubysherpas/forem#306]
I want to postageapp-ruby gem setup with this engine,  is it  possible ?, my app hosted on heroku. can you tell me the process, if possible .

Another question , I have seen gem lock file it has resque, redis , resque_mailer gems , shall I know where these gems used in application . I want implement resque in my app for forem engine.

Thanks in Advance,
Prasad.

**Comment by prasadrails** [comment]
Hi friends, I have seen "subscription_mailer.rb " here one comment is there i.e "# only pass id to make it easier to send emails using resque" , can any one explain , how to using "rescue" in forem . What parameters I have to send .

Thanks in Advance,
Prasad.

**Comment by radar** [comment]
@prasadrails Please show us what you've tried so far. Resque has great documentation which should be pretty self-explanatory in how it works.

**Comment by prasadrails** [comment]
Ok Thank you very much.
