### ISSUE TITLE
Lithuanian translation

### ISSUE THREAD

**Issue by giedriusr** [rubysherpas/forem#307]
Hello,

I am working on lithuanian translation for forem gem. I've noticed, that there are parts in forum, where are still English words, but in yml file there is no keyword to translate. What should I do?

**Comment by giedriusr** [comment]
Anyone? Or it happened just to me?

**Comment by parndt** [comment]
@giedriusr thanks - can you point to examples? Every single string should be inside YML so that it can be localised. That's the goal :-)

**Comment by giedriusr** [comment]
I've noticed that in the admin panel. I will point to it with some screenshots, later on today.

**Comment by giedriusr** [comment]
http://s10.postimage.org/ol2obx59h/admin_groups.png
http://s10.postimage.org/9dmorkdet/new_admin_group.png
http://s10.postimage.org/yxoyxzysl/new_category.png
http://s10.postimage.org/jq8zdn6xx/new_forum.png

Here are the screenshots. Maybe I am missing something, but some parts are still in English.

**Comment by radar** [comment]
These are now fixed. Please let me know if you find anything else that is broken.

**Comment by giedriusr** [comment]
Great. Thanks
