### ISSUE TITLE
No automatic subscription after posting a topic

### ISSUE THREAD

**Issue by mattwd7** [rubysherpas/forem#309]
I do not want users to be pestered by emails by default after posting a topic.  I am trying to add a decorator to the topic model to reverse the after_create :subscribe_poster method.  Here is the code in the decorator:

```
# app/decorators/models/forem/topic_decorator.rb

Forem::Topic.class_eval do  
    after_create :unsubscribe_user(self.id)
end
```

This resulted in the following error:

```
/home/Matthew/mystuff/rails/HHeroes/app/decorators/models/forem/topic_decorator.rb:4: syntax     error, unexpected '(', expecting keyword_end
    after_create :unsubscribe_user(self.id)
                               ^
/home/Matthew/mystuff/rails/HHeroes/app/decorators/models/forem/topic_decorator.rb:4: syntax     error, unexpected ')', expecting keyword_end
    after_create :unsubscribe_user(self.id)
```

This wasn't working.  I tried adding the following code to config/application.rb as advised in a similar issue, but the same error was persisting.

```
config.to_prepare do
  Dir.glob(File.join(File.dirname(__FILE__), "../app/**/*_decorator*.rb")) do |c|
    Rails.configuration.cache_classes ? require(c) : load(c)
  end
end
```

Thank you for any and all help!  Forem has made my app infinitely easier to execute :)

**Comment by parndt** [comment]
You have a syntax error.. You can't pass an argument to a symbol as it
is not a method. You need to reference another method e.g. one that
calls unsubscribe_user(self.id) that you write instead.

**Comment by mattwd7** [comment]
gooooot it.  thanks!

**Comment by giedriusr** [comment]
Please close the issue if it was fixed
