### ISSUE TITLE
Basic integration won't work?

### ISSUE THREAD

**Issue by cobalamin** [rubysherpas/forem#31]
ActionView::Template::Error (undefined local variable or method `current_user' for #Forem::ForumsController:0xb6e48d18):
    27:     <% end %>
    28:   </tbody>
    29: </table>
    30: 
    31: <% if forem_admin? %>
    32:   <%= link_to "Admin Area", admin_root_path %>
    33: <% end %>

Is what I get back. I did everything given in "Installation", except I modified the Gemfile a bit. It didn't work with the gems given; I specified the rails gem to use the 3-1-stable branch and the rack gem to use the rack-1.3 branch. Then it worked to do "bundle install", but well, the said error is what I get back when I open up localhost:3000/forums. Where to define this method, "current_user"?

It could be that it's just me being stupid, and I'm sorry if it is. If it isn't, I think this is fixable easily?
Cheers!
Simon

**Comment by cobalamin** [comment]
Ah, doing this will "fix" the issue:

  def forem_admin?
    #current_user && current_user.forem_admin?
    true
  end

inside application_controller.rb of the gem's controllers. I know this is not an actual fix. :D

**Comment by radar** [comment]
Hello,

Do you not have a gem such as Devise or Authlogic that provides the `current_user` method to instances of subclasses of ApplicationController?

**Comment by cobalamin** [comment]
Is this needed? I'm actually using my own authentication system, will it work if there will be a current_user variable that's available in controllers and views? Or do I have to do weird linking (I don't know much about mounting engines etc.)

**Comment by radar** [comment]
Yes it is necessary as it needs to know what user is logged in to provide certain features such as the admin area. As long as there is a `current_user` variable made available to `ApplicationController` and the views then it will also be available in the engine.

We can talk about this on IRC if you'd prefer? I'm on irc.freenode.net right now as Radar.

**Comment by cobalamin** [comment]
Sorry, were and am unavailable to chat on IRC, thanks for the offer though :)
I'll have a look if it works when I have integrated this into my application, and then post here again. Thank you for now!

**Comment by cobalamin** [comment]
Okay, just to make things clear, implementing that stuff fixed the issue for me. Thanks a lot! :)

abitOT,maybeifyoudidntknow?: I just thought I'd be having another issue, I had those ugly object representation strings everywhere instead of my username, and I fixed it by implementing a to_s function that will return self.username. :)
