### ISSUE TITLE
Forem breaks my app (refinery 2.1.0.dev)

### ISSUE THREAD

**Issue by alepore** [rubysherpas/forem#310]
Adding the forem gem (master, 1.0.0.beta1) to a refinerycms app (master, 2.1.0.dev) breaks refinery helpers, like:

`undefined method `render_content_page' for #<#<Class:0x000001021addf0>:0x000001020ef490>`
`undefined method `image_fu' for #<#<Class:0x000001021addf0>:0x0000012da46270>`

any idea why forem it's doing this?

thanks.

**Comment by parndt** [comment]
@alepore thanks.. so to confirm, I should be able to reproduce this with a brand new Rails application using a Refinery edge template installation `rails new test_app -m http://refinerycms.com/t/edge` and by adding `gem 'forem', github: 'radar/forem'` to its Gemfile?

**Comment by alepore** [comment]
oh no, brand new setup works, so it's my app.. strange because i'm not doing any core refinery modification.

Full trace here if anyone can help:
https://gist.github.com/3780504

p.s: first refinery installation was not performed with edge template, i started with stable refinery and then update to edge

thanks!

**Comment by parndt** [comment]
Basically remove any overridden files until the error goes away, then
you can identify what exactly is broken.

**Comment by alepore** [comment]
i solved removing app/decorators/controllers/refinery/pages/pages_controller_decorator.rb. this makes sense?

**Comment by alepore** [comment]
steps to reproduce:
- create a refinery test app as parndt said
- add forem gem
- create a refinery controller decorator (ex. app/decorators/controllers/refinery/pages/pages_controller_decorator.rb) like:

``` ruby
Refinery::PagesController.class_eval do
end
```

refinery pages will not work anymore
same thing happen with engine's controller decorator.

**Comment by parndt** [comment]
@radar is this because both Forem and Refinery are decorating? We need a common solution!

**Comment by radar** [comment]
Just a blank decorator does this?

**Comment by eostrom** [comment]
I had a similar problem on Refinery 2.0.8, without introducing any decorators. (In my case, `refinery_user?` is the method that's undefined.) I was able to resolve it by putting `forem` _after_ `refinerycms` in the Gemfile. I'm posting this comment here in case that makes a difference in the 2.1.0.dev/decorator case.

**Comment by alepore** [comment]
putting forem after refinerycms in Gemfile seems to work, thanks!
maybe this 'workaround' can be added to the README until a final solution is found.
