### ISSUE TITLE
EXTENDING FOREM CLASSES

### ISSUE THREAD

**Issue by michael-montagne** [rubysherpas/forem#311]
I have run into an issue extending Forem classes which would be exceedingly easy to resolve:

I discovered in attempting to alias controller methods for example, that if any of the underlying processes call an instance of a class by simply ClassName, that this breaks execution in our project. All such references need instead simply to refer to the instance by the full module/engine path, "Forem::ClassName." 

Some of your references follow this convention; some do not. The latter fixes aberrant execution, and eliminates downstream developers having to trace through all Forem code in order to find all the methods we need to override in order to revise the references to "Forem:ClassName."

I detailed this issue in my answer to the following StackOverflow question:

http://stackoverflow.com/questions/12558915/how-to-add-named-scopes-or-other-declarations-to-models-of-an-installed-gem-s

Please see "HOW TO ACCOUNT FOR ABERRANT EXECUTION IN DECORATORS."

Thanks so much for making Forem available. I also have a sophisticated threading scheme I'm hoping to incorporate in our installation. Perhaps you'll want to integrate its code in Forem.

**Comment by radar** [comment]
I think I fixed the locations that didn't use the fully-qualified names with the above commit. If you find any others, please let us know in the form of a pull request.

Regarding the threading scheme, it could be interesting :)
