### ISSUE TITLE
EMOJI!!!

### ISSUE THREAD

**Issue by radar** [rubysherpas/forem#313]
https://github.com/github/gemoji

**Comment by knewter** [comment]
Hot damn that was a fun email to receive :)

**Comment by radar** [comment]
I am a little excited about the prospect of having these within forem.

**Comment by knewter** [comment]
--($:~/rails/forem)(master)ruby-1.9.3-p125@forem-- 
$ git checkout -b gemoji
Switched to a new branch 'gemoji'

**Comment by radar** [comment]
:heart: so much

**Comment by knewter** [comment]
I suck at github so I https://github.com/radar/forem/pull/314

**Comment by knewter** [comment]
http://imgur.com/3Tj0J,hy7gC

**Comment by knewter** [comment]
deployed to production for @isotope11 using emoji now, happy?

**Comment by radar** [comment]
:tada:

**Comment by radar** [comment]
Needs to be supported also in:
- Forum titles
- Forum descriptions
- Topic subjects

**Comment by radar** [comment]
Is good now.
