### ISSUE TITLE
I would like to place the name of the current forum in my layout header...

### ISSUE THREAD

**Issue by sheam** [rubysherpas/forem#318]
Is there a variable that contains the name of the current forum, so that I can place it in the header of my layout?

**Comment by radar** [comment]
It'd be `@forum` if anything. You can probably access that in your layout, but beware that it's not always set. This is what it's called inside `Forem::ForumsController` and `Forem::TopicsController`. On `Forem::PostsController` actions, you will need to check for `@topic.forum`.

I think having a `current_forum` helper could be useful for situations like this. We could use it in places where we're doing `@topic.forum` inside Forem.
