### ISSUE TITLE
not using flash.now

### ISSUE THREAD

**Issue by cobalamin** [rubysherpas/forem#32]
Hey,
I recently started "working" on my own version of forem, because I had to modify the views, and also the controllers. Well, what catched my eye was that, when e.g. a forum creation failed in the admin area, the flash showed up again on the next page I opened. I heard about this issue before, it's fixable really damn easy. Just replace

flash[:blah] = "..."
with
flash.now[:blah] = "..."

in every case where this occurs. I think it has something to do with flash itself waiting for a redirection, but "receiving" none, and therefore showing up again on the next page, where it thinks a redirection has happened.

(vendor/forem/app/controllers/forem/admin/forums_controller.rb is my example controller here, it has this issue.)

Thanks for your awesome but simple engine!
Simon

**Comment by radar** [comment]
I reckon I've got all of these now. Thanks for opening the issue for it :)
