### ISSUE TITLE
Asset Precompile error

### ISSUE THREAD

**Issue by indieambassador** [rubysherpas/forem#320]
When I push to heroku, I am getting a strange issue. I am using twitter-bootstrap-rails and forem with devise in my app. 

Regardless of what I do, I get this when I push to Heroku:

```
Preparing app for Rails asset pipeline
  Running: rake assets:precompile
  rake aborted!
  undefined method `path' for nil:NilClass
  (in /tmp/build_zd811t1inisx/vendor/bundle/ruby/1.9.1/bundler/gems/forem-66686a7e618c/app/assets/javascripts/forem.js.erb)
```

If i have twitter-bootstrap-rails in the `:assets` group, then the app will crash with this error:

```
ActionView::Template::Error (couldn't find file 'twitter/bootstrap'
2012-10-18T15:27:07+00:00 app[web.1]:   (in /app/app/assets/javascripts/application.js:15)):
```

This was working before i installed forem. I have a feeling the rake task failing due to the forem.js.erb fil error is causing this.

If i remove the twitter-bootstrap-rails gem from the assets group, i still get the assets precompile error, but the app loads in heroku just fine. not sure what's going on here. 

also, somehow during the troubleshooting of this issue, the application.css.scss file stopped being parsed. the included files are parsed, but not the code in the file it self. strange.

I haven't been able to find anyone else in the 'issues' section with this issue. If any one could lend some insight to this problem, i would really appreciate it. Thanks!

I am a bit new to rails, so sorry for the n00b issue. I am looking for tips on how to troubleshoot this.

**Comment by focused** [comment]
I have the same issue.

Heroku requires this setting in config/application.rb:

``` ruby
config.assets.initialize_on_precompile = false
```

With this setting this file will not be compiled. To solve this problem you can try different compilation options like runtime compiling (I did not try), other is to patch this file. Any help is highly appreciated.

**Comment by parndt** [comment]
Ideally Forem would not get in the way of compiling on Heroku when using:

``` ruby
config.assets.initialize_on_precompile = true
```

There is a lot of misinformation around about "Heroku requiring this setting" which is not strictly true.. Heroku only requires this when you're using an application that incorrectly accesses the database before the application is initialized. It's good to avoid this on any Rails application.

Do assets fail to precompile on a default Rails application with Forem included or is this coming from something else in your Gemfile?

Thanks!

**Comment by focused** [comment]
Yes, default Rails application with Forem fails to precompile the asset _app/assets/javascripts/forem.js.erb_ with this setting set to **false**. Any suggestions?

**Comment by parndt** [comment]
Does it work when set to true? (The default)

**Comment by focused** [comment]
Yes, it is.

**Comment by oeoeaio** [comment]
I resolved this issue by using the _experimental_ user-env-compile feature of Heroku Labs.

See here for usage instructions:
https://devcenter.heroku.com/articles/labs-user-env-compile

It is also possible to run `bundle exec rake assets:precompile` locally, commit `public/assets/` and push to Heroku, but I find this annoying.

Neither of these options require `config.assets.initialize_on_precompile = false`

**Comment by willcosgrove** [comment]
I had a similar problem but none of the above solutions worked for me.  It ended up being because I set a different engine name with the mount 'as' option.  Which was making this line: https://github.com/radar/forem/blob/master/app/assets/javascripts/forem.js.erb#L4 fetch something that didn't exist.

Just something to be aware of.  If you run into this problem, remove the 'as' option on the mount call in the routes file.

**Comment by radar** [comment]
I thought we had a warning on the mount line that said something like "pretty please don't use :as", or maybe I am confusing that with spree.

**Comment by parndt** [comment]
We should have it, if we don't!

**Comment by willcosgrove** [comment]
You might, but I'm the same guy that the forem:install failed for, so I didn't get any messages :(

**Comment by eostrom** [comment]
I'm seeing this error and I'm not using :as. Is the resolution here that Forem is incompatible with `initialize_on_precompile = false`?

**Comment by parndt** [comment]
Yep please initialise the environment on precompile.

**Comment by eostrom** [comment]
OK. I added a wiki page recommending `user-env-compile` or local asset compilation. [Update: This project's wiki, not Wikipedia!]

**Comment by llexa313** [comment]
I don't use `:as`, but `user-env-compile` and `initialize_on_precompile = true` didn't help for me:

```
Preparing app for Rails asset pipeline
Running: rake assets:precompile
rake aborted!
could not connect to server: Connection refused
Is the server running on host "127.0.0.1" and accepting
TCP/IP connections on port 5432?
```

I wrote little monkey patch in application.rb and it work for me.

```
config.assets.initialize_on_precompile = false
...
routes.named_routes[:forem] ||= Journey::Route.new(nil, nil, Journey::Path::Pattern.new("\forums"), {})
```

Maybe it will help someone else

**Comment by radar** [comment]
@llexa313: That problem looks like something to do with your database setup. `initialize_on_precompile` should be _false_ if you're using Heroku.

**Comment by parndt** [comment]
@radar It doesn't have to be `false`; some applications actually require you set this to true (I thought we did?). That's why Heroku have:

```
heroku labs:enable user-env-compile
```

**Comment by pwalker** [comment]
I can't get my assets to precompile anywhere, local or heroku, with or without `user-env-compile`, and with `initialize_on_precompile` set to both true and false. I'm still erroring out at the mentioned line, any ideas or how to debug this?  There are a lot of partial solutions here, and wiki page was rather short on the subject.

**Comment by focused** [comment]
You can just override and hardcode this, thats how we solve this for Heroku then.

**Comment by austencollins** [comment]
Just getting started with Forem and I am running into this same issue.  I've tried all of the solutions above, but this gem will not allow me to deploy to Heroku.  How else has everyone been working around this?

**Comment by radar** [comment]
@ac360: Is it possible for you to give me (radarlistener@gmail.com) access to your Heroku application so that I can attempt to deploy it and see these errors for myself? That would really help me to be able to debug it. If you're not able/willing to do that, then attempt to reproduce this issue in a brand new app with the same Gemfile. If you're able to reproduce it there, then please share with us that Gemfile and I'll attempt to reproduce it myself.

Thanks!

**Comment by ghost** [comment]
I'd just like to +1 this issue and add a bit of my own experience, (not sure if this will help or just muddle the issue, but...):

I'm using Forem on two different apps, both are running Rails 3.2.13.  I was having the same issue described by everyone else, but was able to solve it in _one_ of the apps by including the initialize_on_precompile = true directive in application.rb.  I duplicated the fix on my other app -- and no joy. It seems bizarre that two apps running on the same version of rails would react differently, but that's my situation.  If it helps:

bundle list for the 'working' app:
- actionmailer (3.2.13)
- actionpack (3.2.13)
- activemodel (3.2.13)
- activerecord (3.2.13)
- activeresource (3.2.13)
- activesupport (3.2.13)
- addressable (2.3.4)
- arel (3.0.2)
- better_errors (0.9.0)
- binding_of_caller (0.7.1)
- browser (0.1.6)
- builder (3.0.4)
- bundler (1.3.5)
- cancan (1.6.10)
- capistrano (2.15.4)
- capybara (2.1.0)
- carrierwave (0.8.0)
- chunky_png (1.2.8)
- coderay (1.0.9)
- coffee-rails (3.2.2)
- coffee-script (2.2.0)
- coffee-script-source (1.6.2)
- compass (0.12.2)
- compass-rails (1.0.3)
- daemons (1.1.9)
- dalli (2.6.4)
- database_cleaner (1.0.1)
- debug_inspector (0.0.2)
- decorators (1.0.3)
- delayed_job (3.0.5)
- delayed_job_active_record (0.4.4)
- diff-lcs (1.2.4)
- erubis (2.7.0)
- eventmachine (1.0.3)
- execjs (1.4.0)
- factory_girl (4.2.0)
- ffaker (1.16.1)
- forem (1.0.0.beta1)
- friendly_id (4.0.9)
- fssm (0.2.10)
- gemoji (1.1.2)
- gli (2.5.6)
- globalize3 (0.3.0)
- haml (4.0.3)
- haml-rails (0.4)
- highline (1.6.19)
- hike (1.2.3)
- httparty (0.11.0)
- i18n (0.6.1)
- i18n-active_record (0.0.2)
- infinity_game_content (0.12.0)
- journey (1.0.4)
- jquery-rails (3.0.0)
- json (1.8.0)
- kaminari (0.14.1)
- launchy (2.3.0)
- localeapp (0.6.9)
- mail (2.5.4)
- method_source (0.8.1)
- mime-types (1.23)
- mini_magick (3.6.0)
- mini_portile (0.5.0)
- multi_json (1.7.6)
- multi_xml (0.5.4)
- mysql2 (0.3.11)
- net-scp (1.1.1)
- net-sftp (2.1.2)
- net-ssh (2.6.7)
- net-ssh-gateway (1.2.0)
- nokogiri (1.6.0)
- paper_trail (2.7.2)
- polyglot (0.3.3)
- pry (0.9.12.2)
- quiet_assets (1.0.2)
- rack (1.4.5)
- rack-cache (1.2)
- rack-ssl (1.3.3)
- rack-test (0.6.2)
- rails (3.2.13)
- railties (3.2.13)
- rake (10.0.4)
- rdoc (3.12.2)
- rest-client (1.6.7)
- rspec-core (2.13.1)
- rspec-expectations (2.13.0)
- rspec-mocks (2.13.1)
- rspec-rails (2.13.2)
- sass (3.2.9)
- sass-rails (3.2.6)
- simple_form (2.1.0)
- slim (2.0.0)
- slim-rails (2.0.1)
- slop (3.4.5)
- sprockets (2.2.2)
- subexec (0.2.3)
- temple (0.6.5)
- thin (1.5.1)
- thor (0.18.1)
- tilt (1.4.1)
- timecop (0.6.1)
- treetop (1.4.14)
- tzinfo (0.3.37)
- uglifier (2.1.1)
- vcr (2.5.0)
- workflow (0.8.0)
- xpath (2.0.0)
- ya2yaml (0.31)
- yajl-ruby (1.1.0)

bundle list for the 'broken' app:
- actionmailer (3.2.13)
- actionpack (3.2.13)
- activemodel (3.2.13)
- activerecord (3.2.13)
- activeresource (3.2.13)
- activesupport (3.2.13)
- acts_as_list (0.2.0)
- arel (3.0.2)
- awesome_nested_set (2.1.6)
- bcrypt-ruby (3.0.1)
- best_in_place (2.1.0)
- builder (3.0.4)
- bundler (1.3.5)
- cancan (1.6.10)
- carrierwave (0.8.0)
- coderay (1.0.9)
- coffee-rails (3.2.2)
- coffee-script (2.2.0)
- coffee-script-source (1.6.2)
- daemons (1.1.9)
- dalli (2.6.4)
- dbi (0.4.5)
- decorators (1.0.3)
- delayed_job (3.0.5)
- delayed_job_active_record (0.4.4)
- deprecated (2.0.1)
- diff-lcs (1.2.4)
- erubis (2.7.0)
- eventmachine (1.0.3)
- execjs (1.4.0)
- filter_it (0.0.1)
- forem (1.0.0.beta1)
- friendly_id (4.0.9)
- gemoji (1.1.2)
- gli (2.5.6)
- haml (4.0.3)
- hike (1.2.3)
- hpricot (0.8.6)
- httparty (0.11.0)
- i18n (0.6.1)
- journey (1.0.4)
- jquery-datatables-rails (1.11.2)
- jquery-rails (3.0.1)
- jquery-ui-rails (4.0.3)
- json (1.8.0)
- localeapp (0.6.9)
- mail (2.5.4)
- method_source (0.8.1)
- mime-types (1.23)
- mini_magick (3.6.0)
- mini_portile (0.5.0)
- multi_json (1.7.7)
- multi_xml (0.5.4)
- mysql2 (0.3.11)
- net-sftp (2.1.2)
- net-ssh (2.6.7)
- nokogiri (1.6.0)
- polyglot (0.3.3)
- pry (0.9.12.2)
- quiet_assets (1.0.2)
- rack (1.4.5)
- rack-cache (1.2)
- rack-ssl (1.3.3)
- rack-test (0.6.2)
- rails (3.2.13)
- railties (3.2.13)
- rake (10.0.4)
- rdoc (3.12.2)
- repeated_auto_complete (0.1.3)
- rest-client (1.6.7)
- rspec (2.13.0)
- rspec-core (2.13.1)
- rspec-expectations (2.13.0)
- rspec-mocks (2.13.1)
- rspec-rails (2.13.2)
- sanitize (2.0.4)
- sass (3.2.9)
- sass-rails (3.2.6)
- shoulda-matchers (2.2.0)
- simple_form (2.1.0)
- slim (2.0.0)
- slop (3.4.5)
- spork (0.9.2)
- sprockets (2.2.2)
- subexec (0.2.3)
- temple (0.6.5)
- thin (1.5.1)
- thor (0.18.1)
- tilt (1.4.1)
- treetop (1.4.14)
- tzinfo (0.3.37)
- uglifier (2.1.1)
- uuidtools (2.1.4)
- will_paginate (3.0.4)
- workflow (0.8.0)
- ya2yaml (0.31)

Again -- not sure this helps resolve the problem -- one other thing to note is that I am _not_ using heroku
