### ISSUE TITLE
undefined local variable or method `forum'

### ISSUE THREAD

**Issue by ghost** [rubysherpas/forem#324]
I've installed forem to my new app. I'm using devise for authentication, so my user class and current_user helper are default. Generator forem:install was finished successfully, but when I try access to /forems route I have a error (I've restart the server): 

Showing /.../.rvm/gems/ruby-1.8.7-p352/bundler/gems/forem-66e2f512d0f0/app/views/forem/forums/_head.html.erb where line #2 raised: 

ActionView::Template::Error (undefined local variable or method `forum' for #<#Class:0x10b5430d8:0x10b53c620>):

Extracted source (around line #2): 
...
2:  <%= link_to t('forem.forum.forums'), forem.root_path %> &raquo; <%= link_to forem_emojify(forum.category), [forem, forum.category] %> &raquo; <%= link_to forem_emojify(forum.title), [forem, forum] %>

....

**Comment by radar** [comment]
Hi Monika,

Please show us the stack trace for this issue

**Comment by ghost** [comment]
Hi, fortunately I've figured out my problem. But I'll try explain it briefly, because it was a little tricky.

In my project I also use the 'html5-rails' gem. This gem creates default application.html.erb layout, where includes partial named 'head' (located in views/application folder): 

= render "head"

So when I installed forem and tried access to Forem::ForumsController#index, the index view was rendered in default  application layout as well. The problem is the forem has partial named the same way - 'head' (in views/forem/forums), and app was rendering this 'head' partial instead 'head' of 'html5-rails' (because of relative path). Consequently I've got the error: undefined local variable or method `forum'.

The solution is change paths in layouts from relative to absolute, f.e.:

  = render "/application/head"

Sorry for bother. The issue could be closed.

**Comment by radar** [comment]
No worries, thanks for letting us know.
