### ISSUE TITLE
require login to access forem

### ISSUE THREAD

**Issue by eostrom** [rubysherpas/forem#326]
I'm using the Forem engine as part of a larger app, and I want the forums to be off-limits to the general public. If you visit the forum root (or any other Forem page), you should be forced to log in.

I thought I could do this by overriding `can_read_forem_forums?` in my user model, but that still shows me a forums page (with categories), just with all the individual forums hidden.

I'm sure I can find a workaround for this, but it seems like an option that others will want. I'd be happy to implement it, but does anyone have any suggestions for a configuration option or other API that will fit into Forem coding conventions, etc.? Alternatively, is there already a way to do this?

**Comment by radar** [comment]
How about adding a decorator for `Forem::ApplicationController` that calls your `authenticate_user!` before filter? Would that work?

Apologies for not replying sooner. I must've missed the email for this issue.

**Comment by eostrom** [comment]
That does work. I'll add a note to the Authorization System wiki page.

**Comment by radar** [comment]
Ok. Thanks.
