### ISSUE TITLE
custom helper

### ISSUE THREAD

**Issue by nyku** [rubysherpas/forem#328]
How can i override link_to_latest_post helper?
Because i need to change the text inside the link
from this:
text = "#{time_ago_in_words(post.created_at)} #{t("ago_by")} #{post.user}"
to this:
text = "#{time_ago_in_words(post.created_at)} #{t("ago_by")} #{post.user.person.fullname}"

**Comment by indieambassador** [comment]
I think it might be better to overwrite to_s in the user model with something that will output what you want..

```
#in your user model...

      def to_s
         "#{fullname}"
       end
```

**Comment by radar** [comment]
Confirm. Please define a to_s method in your model.
