### ISSUE TITLE
Emoji image path produces 404

### ISSUE THREAD

**Issue by andypike** [rubysherpas/forem#331]
I have an app that was using an older commit of forem. I've just upgraded and master/HEAD and it's all working fine except that when I add an emoji tag to a post, it is replaced with an image tag but in the browser the image shows a broken link and the emoji url shows as a routing error in my server log:

`ActionController::RoutingError (No route matches [GET] "/assets/emoji/smile.png")`

Do I need to do anything special to get the images to display?

By the way, this is for the website www.lag.tv where we are using forem. I monkey patched emoji before you had it in, so now would prefer to use your implementation.

Thanks in advance

Andy

**Comment by parndt** [comment]
Looks like [in the emojify gem](https://github.com/revans/emojify/tree/master/vendor/assets/images/emojis) this folder is `/assets/emojis/smile.png` @radar @knewter c/d?

**Comment by andypike** [comment]
Yeah I checked that out and I can see the images in the gem. But they are not being served up for some reason. I've probably done something odd as I expect this should just work.

**Comment by radar** [comment]
That's so weird. I've seen the emojis working within Forem with my own eyes! I've applied a fix for this now. Thanks for bringing it to our attention :)

**Comment by andypike** [comment]
Err, not sure that fixes it. I haven't pulled in the code but just changed the url to match your change and it still fails. BTW, aren't you using the gemoji-1.1.3 gem rather than emojify? Sorry to be a pain. In the gemoji gem the files are [here](https://github.com/github/gemoji/tree/master/images/emoji)

**Comment by andypike** [comment]
Does this recent commit explain it? https://github.com/github/gemoji/commit/91a5a025ca3ae519f946a68638de66e8f1933dc1

**Comment by parndt** [comment]
That commit is likely the problem!

How do we get gemoji in the assets group?

**Comment by radar** [comment]
Ugh, I got confused. Sorry. Gemoji is broken. I will submit a patch there.

**Comment by andypike** [comment]
Thx :smile:
