### ISSUE TITLE
Enable a Single Sign On by allowing authentication through an devise onmiauth provider

### ISSUE THREAD

**Issue by lukeholder** [rubysherpas/forem#333]
make compatible with

https://github.com/joshsoftware/sso-devise-omniauth-provider

see example:

http://blog.joshsoftware.com/2010/12/16/multiple-applications-with-devise-omniauth-and-single-sign-on/

**Comment by knewter** [comment]
One of the points of the way forem's built is to make it dead simple to plug in your own user class, etc.  It _is_ an engine, after all.  Consequently, I don't feel like forem itself needs to support this (though a wiki entry would be nice probably).

For an example where I'm using Devise+omniauth to support SSO, you can see code at https://github.com/isotope11/isotope-forums/blob/master/config/initializers/xrono.rb

It's really dead-simple to do this already.  Took me 10 minutes to roll that project.  Thoughts?

**Comment by radar** [comment]
I agree with @knewter. Forem doesn't need to support this. It's your _application_ that should support this.
