### ISSUE TITLE
Emoji still don't seem to be working

### ISSUE THREAD

**Issue by sfcgeorge** [rubysherpas/forem#340]
I've seen the previous issues regarding Emoji and pull requests fixing the problems. But they still aren't working for me, I just get a 404 for the assets. 

I'm using the latest version of Forem, with gemoji locked down to 1.1.2. I tried looking at some of the source but couldn't figure it out, sorry. 

I have forem mounted under /forums if that makes any difference to the asset pipeline, but I wouldn't have thought so? I only started my forum 2 days ago so I don't think I've done anything unusual to it. Let me know if there are any logs or something you need to help diagnose. Thanks

**Comment by radar** [comment]
What's the URL that it's attempting to look up the emojis under?

**Comment by sfcgeorge** [comment]
/assets/emoji/wink.png  which looks reasonable to me, but I just get the standard Rails 404 page.

I also tried  /assets/emojis/wink.png  as I saw the plural version mentioned somewhere, but no luck.

(the url does include the site's domain name properly, I just removed it here for succinctness)

**Comment by radar** [comment]
Cheers for the fast response. Do you have an example app that reproduces this problem?

**Comment by sfcgeorge** [comment]
Sorry for the delay, I was just doing a bundle update and pushing to GitHub. Sample app is Forem + Refinery based.  https://github.com/sfcgeorge/QLAQ
