### ISSUE TITLE
Forem not compatible with rake db:reset

### ISSUE THREAD

**Issue by ghost** [rubysherpas/forem#341]
Trace: http://pastie.org/5444972

`rake db:drop db:create db:migrate db:seed` works though (thanks parndt)

**Comment by radar** [comment]
As I said in IRC, I think this is just because you're not resetting the column information before db seed runs. That's all.

**Comment by parndt** [comment]
@shhhhh If you can upload a sample application that exhibits the problem I'm more than happy to take a further look for you, free of charge :-)

**Comment by ghost** [comment]
Turned out the error came from changing `title` to `name` in https://github.com/radar/forem/blob/master/db/migrate/20110214221555_create_forem_forums.rb#L4 - I didn't know the new alias didn't reach that far.
