### ISSUE TITLE
post.user

### ISSUE THREAD

**Issue by nordbit** [rubysherpas/forem#344]
Can I define somewhere "post.user" ?
Because for now  "post.users" returns in view something like "#User:0x00000003cd78e8"
It should be cool option in initializer :
 : forem_user => :post.user.name 
or
:forem_user => post.user.email

**Comment by parndt** [comment]
I'm confused - can you explain what you're after?

**Comment by radar** [comment]
Define `to_s` on your User model to fix this problem.
