### ISSUE TITLE
First post should be distinguishable from other posts

### ISSUE THREAD

**Issue by bvsatyaram** [rubysherpas/forem#348]
It would be nice if we can say if a post is the first post in the thread. It will be useful, in case we would like to have special styling to the first post.

I can submit a patch, if you feel that it's useful too. I suggest the following 2 solutions.
1. Have a boolean column 'primary' in the posts table and set it to true for the first post alone.
2. If you prefer not to touch the schema for this, a hackish way is to define the following with Forem::Post

``` ruby
def primary?
  self.reply_to_id.nil? && self.created_at == self.topic.created_at
end
```

I am using the second way in our project.

**Comment by parndt** [comment]
What about:

```
self == topic.posts.first
```

**Comment by bvsatyaram** [comment]
Yes, makes sense. I was trying to optimize too much :P
So, shall I submit a patch for this?

**Comment by parndt** [comment]
I'm not sure if it's needed. WDYT @radar @knewter

**Comment by sfcgeorge** [comment]
If all you want to do is style the first post differently, you can do it in pure css:

```
#posts > div:first-of-type {
  background: red;
}
```

This wont work in IE8 but will in most other browsers. I think this is acceptable as a progressive enhancement.

**Comment by radar** [comment]
I don't think it's needed if you can just check `topic.posts.first` as @parndt said.

**Comment by bvsatyaram** [comment]
@sfcgeorge Thanks for the suggestion. I considered that. However, that would style first post in every page differently. So, I wanted to touch the backend.

**Comment by sfcgeorge** [comment]
Doh! You are right, but I've found an even easier way, can't believe I missed this before:

```
#post_1 {
    background: red;
}
```

Hopefully this will work for you :smile:

**Comment by bvsatyaram** [comment]
The problem still is the same. The first post in page 2 also has #post_1.
The only way is to mark the first post of a topic with a special class/id. For that I just wrote a helper to check if the post is the first post of the topic.

**Comment by sfcgeorge** [comment]
Sorry, I should have tested. Right, I have tested the below CSS and it does work - only the first post on the first page is highlighted. There is an `<a>` tag before every post `<div>` with a unique `name` attribute corresponding to the post ID - which is how the browser scrolls to a specific post. The CSS below selects the `<div class="post">` after the `<a name="post-1">` in order to style it. These are CSS 2.1 selectors so should work in almost all browsers. 

```
#posts a[name=post-1] + div.post {
  background: red;
}
```

**Comment by bvsatyaram** [comment]
@sfcgeorge I truly appreciate your effort. The anchor tag has name attribute "post-x" where x is the 'id' of the post in db. And the div has id "post_y" where y is the position of the post in the page from the top.
While y is 1 for first page even in second page of a topic, x can be 1 for only one post in the db of all the posts. So, the CSS you provided does work in most of the browsers, but only if the id of the post is 1 in db.
Try creating another topic if it doesn't exist yet; x in that page won't be 1.

**Comment by sfcgeorge** [comment]
Drat, yes that makes sense. As a single table with all of the posts then the ID's must be continuous. In my local dev environment I happened to be testing this CSS in the first thread posted so it happened to work. Looks like your solution of using a helper is the only way then. Oh well, I had fun trying those CSS selectors I've almost never used before - it's remarkably powerful, though in this case you have shown the extra metadata is needed.

**Comment by bvsatyaram** [comment]
Yeah, true. I appreciate it! :-)
