### ISSUE TITLE
Version collisions with guard gem (and more)

### ISSUE THREAD

**Issue by elado** [rubysherpas/forem#358]
`forem` has one sub-dependency of `ffi` 1.0.7

(through `forem-redcarpet` > `pygments.rb` v0.2.4 (current is 0.3.3) > `rubypython` 0.5.3 > `ffi` 1.0.7

I get this error on `bundle` command:

```
Bundler could not find compatible versions for gem "ffi":
  In Gemfile:
    forem (>= 0) ruby depends on
      ffi (~> 1.0.7) ruby

    guard (>= 0) ruby depends on
      ffi (1.2.0)
```

**Comment by radar** [comment]
I've bumped both the redcarpet and pygments dependencies of forem-redcarpet. Please try this again.
