### ISSUE TITLE
Quoting posts

### ISSUE THREAD

**Issue by bodrovis** [rubysherpas/forem#359]
Hello. When i hit "Quote" in my forum, the initial post is wrapped with "blockquote" tag in the textarea, but when i click submit, the quote is being displayed in a raw format (the < blockqoute > is being displayed as plain text). I couldn't find any solution, but noticed that on the demo forum not the "blockquote" appears in the form, but the ">" symbol. Why is it so (i'm using the latest version)?

**Comment by bodrovis** [comment]
I face exactly the same problem with a brand new application.

**Comment by parndt** [comment]
Can you show us a screenshot with what you mean, please?

**Comment by bodrovis** [comment]
Of course. I find any post on the forum and click Quote button near it. Then i see the form with the content shown on the first screenshot (i just put "my reply" there). Then i click Submit and see that the blockquote tag is shown in raw format (second screenshot). Moreover, when i quote post with multiple lines, every line is being wrapped in a "p" tag (like it is shown on the third screenshot). I guess something is wrong with formatter. In the formatting_helper.rb i changed the line 

``` ruby
"<blockquote>#{(h(text))}</blockquote>\n\n".html_safe
```

and removed the blockquote tag, replacing it with just the "Quote" word, but this is not quite beafutiful  :) 

I just noticed that on the demo forum everything is OK with quoting and in the form while quoting not the "blockquote" tag, but the "> >" symbols are being shown. 

![1](https://f.cloud.github.com/assets/646942/65928/92bd9078-5e91-11e2-8e3f-e3f2d4271e2f.png)
![2](https://f.cloud.github.com/assets/646942/65930/98546246-5e91-11e2-9360-345e1de66c67.png)
![3](https://f.cloud.github.com/assets/646942/65931/999b21da-5e91-11e2-8163-9924e54424b7.png)

**Comment by aghull** [comment]
Same. Using the default formatter it mis-handles replies. Adding the gem 'forem-gfm_formatter' makes it act like the demo site.

**Comment by bodrovis** [comment]
I can approve that adding

``` ruby
gem 'forem-gfm_formatter'
```

to the Gemfile fixes the problem. Thanks a lot!

Closing the issue.

**Comment by shivanibhanwal** [comment]
We have run into this same issue. Its right if we use the `'forem-gfm_formatter'`gems then we do not run into this issue.
However by default it always has same issue. Looks like missing piece here is the `redcarpet` gem and conversion of the block_quote's as per the `redcarpet`.

Whereas as per the forem documentaion `redcarpet` is the default formatter so 
ideally it should convert the `blockquote` but it is not happening.

**Comment by radar** [comment]
@shivanibhanwal Just to confirm: you're seeing this on a new forem installation when you attempt to quote a post?

**Comment by shivanibhanwal** [comment]
@radar Yes I am using the latest forem.

**Comment by radar** [comment]
Hi @shivanibhanwal. I've taken a look at this issue today and made some tweaks to how we're doing sanitization of HTML in the post text. We are now using the [sanitize](https://github.com/rgrove/sanitize) gem to sanitize the input and show the right HTML tags. 

As far as I can tell, this has fixed the issue you reported. Please run `bundle update forem` and let me know if you run into any more problems.

Thanks for using Forem :)

**Comment by bodrovis** [comment]
After I updated forem on my site I got problems with quoting again. Now when I click on "Quote" link I see this in the textarea:

```
> Original message
```

When I click submit I see the following:

```
&gt; Original message

My message
```

So basically the > symbol is being encoded for html. You can see this issue here: http://www.la-theatre.ru/forum/forums/chetvyortyy-festival/topics/dlya-teatrov?page=1

**Comment by bodrovis** [comment]
Oh well, i removed `gem 'forem-gfm_formatter'`, run `bundle update`, restarted the server and this issue is gone. Thanks!

**Comment by bodrovis** [comment]
Though i am not sure why the empty `p` tag appears just before the `blockquote` (see the image below).

![untitled](https://f.cloud.github.com/assets/646942/1550375/58966134-4e02-11e3-8baf-b09635d6972c.png)

**Comment by radar** [comment]
@bodrovis Please provide exact steps to reproduce that issue within a new Forem application.

**Comment by bodrovis** [comment]
@radar I have just created a new rails app with the following Gemfile:

``` ruby
source 'https://rubygems.org'
gem 'rails', '3.2.15'
gem 'sqlite3'
gem 'forem', :github => "radar/forem"
gem 'will_paginate', '3.0.4'
gem 'devise'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
```

Then I followed instructions here: https://github.com/radar/forem#installation and here https://github.com/plataformatec/devise#getting-started to set up Devise. 

After that I created new forum and a new theme, added post and then replied to it. Here is the output (with no styling):
![nostyling](https://f.cloud.github.com/assets/646942/1561425/bdc1da36-5030-11e3-869d-7cab64a9ae1a.png)

And with some styling:
![styling](https://f.cloud.github.com/assets/646942/1561426/c710e71c-5030-11e3-8022-d7e7f11b2b6d.png)

The empty `p` tag before `blockquote` persists. Not sure if this is an expected behavior. Please let me know if there is any other information required.

**Comment by bodrovis** [comment]
This happens because `simple_format` wraps text with `p` tag, so this input `simple_format('<blockquote>Test</blockquote>')` produces this output: `<p><blockquote>Test</blockquote></p>`. And after `Forem::Sanitizer.sanitize` removes this wrapping and puts it at the beginning of the line, so this construction `Forem::Sanitizer.sanitize(simple_format('Test'))` provides this output: `<p></p><blockquote>Test</blockquote>`.

UPDATED: As far as I understand `blockquote` tag cannot be placed inside of the `p`, so this happens.

**Comment by bodrovis** [comment]
The source code of `simple_format`:

``` ruby
      def simple_format(text, html_options={}, options={})
        text = '' if text.nil?
        text = text.dup
        start_tag = tag('p', html_options, true)
        text = sanitize(text) unless options[:sanitize] == false
        text = text.to_str
        text.gsub!(/\r\n?/, "\n")                    # \r\n and \r -> \n
        text.gsub!(/\n\n+/, "</p>\n\n#{start_tag}")  # 2+ newline  -> paragraph
        text.gsub!(/([^\n]\n)(?=[^\n])/, '\1<br />') # 1 newline   -> br
        text.insert 0, start_tag
        text.html_safe.safe_concat("</p>")
      end
```

Probably it can be tweaked like this:

``` ruby
  def simple_format_tweaked(text)
    text = '' if text.nil?
    text = text.dup
    text = text.to_str
    text.gsub!(/\r\n?/, "\n")                    # \r\n and \r -> \n
    # text.gsub!(/\n\n+/, "</p>\n\n")  # 2+ newline  -> paragraph ???
    # text.gsub!(/\n\n+/, "<br /><br />") # just replace couple of new lines with 2 br?
    text.gsub!(/([^\n]\n)(?=[^\n])/, '\1<br />') # 1 newline   -> br
    text.html_safe
  end
```

But I am not sure what to do with `\n` being replaced with new paragraphs. What do you think about this?

**Comment by bodrovis** [comment]
Another option is to use Rails4-style simple_format, which provides a way to specify wrapper tag. I thought that `div` could be used for wrapping instead of `p`, because `blockquote` can be placed inside `div`, but Sanitize strips it when using `Sanitize::Config::BASIC`.

``` ruby
  def simple_format_tweaked(text, html_options = {}, options = {})
    wrapper_tag = options.fetch(:wrapper_tag, :p)

    # text = sanitize(text) if options.fetch(:sanitize, true)  not needed?
    paragraphs = split_paragraphs(text)

    if paragraphs.empty?
      content_tag(wrapper_tag, nil, html_options)
    else
      paragraphs.map! { |paragraph|
        content_tag(wrapper_tag, paragraph, html_options, false)
      }.join("\n\n").html_safe
    end
  end

private 

  def split_paragraphs(text)
    return [] if text.blank?

    text.to_str.gsub(/\r\n?/, "\n").split(/\n\n+/).map! do |t|
      t.gsub!(/([^\n]\n)(?=[^\n])/, '\1<br />') || t
    end
  end
```

**Comment by radar** [comment]
Hi @bodrovis, I think the best course of action is to remove the usage of `simple_format` completely and rely on the formatters for Markdown + Textile to render the paragraph tags themselves. I've added a commit to master and rails4 which has this change in it now.

Can you please check and see if that is looking any better?

Thanks!

**Comment by bodrovis** [comment]
@radar Understood. Here are the results of my experiments (the whole app was pushed here https://github.com/bodrovis/tesforem ): 
1. Quoting without any formatter and with no styling (only with normalize.css) is okay:
   ![nostyling](https://f.cloud.github.com/assets/646942/1572497/253232c2-511e-11e3-9d52-04b6cc6fa56d.png)
2. Quoting with no formatter and with styling (I used Twist theme) makes main text of the post float the `blockquote` (`blockquote` has `float: left`) and it looks pretty strange.
   ![withstyling](https://f.cloud.github.com/assets/646942/1572512/6373129a-511e-11e3-8bf9-544a1e9b5d24.png)
   I think that the main text (after the `blockquote`) should be wrapped in `p` to avoid this. Maybe the whole post with `blockquote` and text should also be wrapped in `div` with some styling applied, because as you can see the text in the first post is displayed inline with the time.
3. I also faced problems with formatters. Firstly I added `gem 'forem-gfm_formatter'` to my Gemfile and used `bundle update`. It gave me the following result:
   ![gfm](https://f.cloud.github.com/assets/646942/1572522/88118fe6-511e-11e3-9b92-b13ffe4bdb0a.png)
   So basically the `>` symbol was just encoded for html as `&gt;`. 
4. Then I replaced gfm with `gem 'forem-rdiscount'` and got the following:
   ![rdiscount](https://f.cloud.github.com/assets/646942/1572538/d8544c1e-511e-11e3-8caf-5f6bc20d7853.png)
   So `blockquote` was sanitized and wrapped with `p`. I got the same result with `gem 'forem-textile_formatter'`.
5. Lastly I used `gem 'forem-kramdown'`. `>` symbol was not encoded for html, but it was shown as is and was wrapped with `p`. By occasion I have noticed that replacing `>` with `blockquote` makes the post look absolutely right (as it is supposed to look, as I think) - note the difference between the two posts at the screenshot.
   ![kramdown](https://f.cloud.github.com/assets/646942/1572561/4e2ccff6-511f-11e3-8c26-c416cb0bd01b.png)
6. Still when using kramdown and forcing the `blockquote` there are some problems with styling because of float:
   ![kramdownstyled](https://f.cloud.github.com/assets/646942/1572589/027a6e1e-5120-11e3-8bb8-168b8aa2fc76.png)
   But that is the least problem :)

**Comment by bodrovis** [comment]
It seems like sanitization was the problem, at least when using `gem 'forem-kramdown'`. I rewrote the method `as_formatted_html` (https://github.com/radar/forem/blob/9633409b8557b35fa37d101125b6c0cfb0193978/app/helpers/forem/formatting_helper.rb#L4) like this (removed `as_sanitized_text`):

``` ruby
    def as_formatted_html(text)
      if Forem.formatter
        Forem.formatter.format(text)
      else
        Forem::Sanitizer.sanitize(text).html_safe
      end
    end
```

and quoting was formatted nicely:
![with_no_sanitize](https://f.cloud.github.com/assets/646942/1575865/c2c0b420-5153-11e3-8540-92e5693231b1.png)

Rewriting the method as: 

``` ruby
def as_formatted_html(text)
      if Forem.formatter
        as_sanitized_text(Forem.formatter.format(text)).html_safe
      else
        Forem::Sanitizer.sanitize(text).html_safe
      end
    end
```

does the trick for kramdown, but other formatters does not work :(

**Comment by radar** [comment]
Wow, that's some post you have there :) 
1. Good, so it looks fine on _something_.
2. This is just a styling issue. The `time` element needs to have `display: block` set on it and everything is fine.
3. Issue with the formatter, which I've now created [a PR](https://github.com/Miniand/forem-gfm_formatter/pull/1). No idea if they're going to merge it. Might have to use my fork for the time being if you want to use this one.
4. I don't get this problem with my forem-rdiscount gem.
5. Please file an issue on the forem-kramdown project. Probably similar to 3.
6. I don't know how to fix those styling problems.

**Comment by bodrovis** [comment]
@radar Okay, I understood what is going on; things appeared to be quite messed. The main problem seems to be sanitization. By points:
1. Yeah
2. `time` should also not have `float` attribute; there are more changes to styling to be done but it can be managed
3. Okay! By the way, do we have to sanitize text in the `format` method here: https://github.com/radar/forem-gfm_formatter/commit/81e0390336d50c07eceb653a271950ce10a62923 if we already have this line in `as_formatted_html`: `Forem.formatter.format(as_sanitized_text(text))`? It seems like double sanitization (and also there are problems with sanitization which I will point out next).
4. The `forem-rdiscount` gem seems to be outdated. I included it into my Gemfile like this: `gem 'forem-rdiscount'` and noticed that when clicking "Quote" the original text in textarea was wrapped with `blockquote` however judging by the gem's code it should be prepended with `>` symbol, which in turn should be transformed into `blockquote`. I then launched console and running `Forem.formatter.respond_to?(:blockquote)` gave `false`, however there is a method `blockquote` defined. After it I changed my Gemfile like this: `gem 'forem-rdiscount', git: 'https://github.com/radar/forem-rdiscount.git'` and things started to work as expected, but `>` was displayed as raw text (just like in point 5 when I used kramdown):
   ![rdiscount2](https://f.cloud.github.com/assets/646942/1590960/69d40d98-5299-11e3-8d8f-17fe630f064c.png)
   So after all my guess is that `forem-rdiscount` gem should be updated on the rubygems.org.
   The code for `forem-textile_formatter` is outdated: it uses `ERB::Util.h(text)` just like `forem-gfm_formatter` and has no `blockquote` method: https://github.com/radar/forem-textile_formatter/blob/master/lib/forem/formatters/redcloth.rb. I submitted a pull request: https://github.com/radar/forem-textile_formatter/pull/1
5. It appears that this is not related to point 3. I tried to apply a fix described previously and rewrited method `as_formatted_html` like this for sanitization applied after the formatter does its job, not before:

``` ruby
def as_formatted_html(text)
      if Forem.formatter
        as_sanitized_text(Forem.formatter.format(text)).html_safe
      else
        Forem::Sanitizer.sanitize(text).html_safe
      end
end
```

As I mentioned, it did the trick for kramdown. After fixing the problem with RDiscount I found out that this fix works for this formatter as well. I presume that after fixing issues with the two other formatters it should work fine with all of them. 
6. I had to make action buttons absolutely positioned. My solution can be seen here: http://www.la-theatre.ru/forum/forums/chetvyortyy-festival/topics/dlya-teatrov.

So after all something has to be done with sanitization. Don't know if my suggested fix is okay, but at least we managed to resolve problems with formatters.

**Comment by radar** [comment]
I've fixed (4) in your list today. I will need to find more time to look at the others.

**Comment by bodrovis** [comment]
@radar Okay! I am sorry, what about pull request https://github.com/radar/forem-textile_formatter/pull/1 in point 4? Is it okay or should i change something?

**Comment by radar** [comment]
Patch looks good to me. I've merged it today.

**Comment by bodrovis** [comment]
I am not sure, but probably this issue should be reopened. There is a lot going on here and new users will have problems with quoting due to sanitization.

**Comment by radar** [comment]
Rather than re-opening this issue, can we please just open a new issue per single bug? This issue is INCREDIBLY VAGUE and it's about an INCREDIBLY COMPLEX part of Forem. 

One issue per bug, thanks.

**Comment by bodrovis** [comment]
@radar It is done!
