### ISSUE TITLE
Incorrect gem dependency listed in installation instructions

### ISSUE THREAD

**Issue by supairish** [rubysherpas/forem#36]
Hello,
   Had a bit of a problem installing forem.  In the instructions it says use:

gem 'forem', :git => "git://github.com/radar/forem.git"

But doing this for me, pulled version 0.0.1, mostly likely because that's the last Git tag you guys have? maybe.  Anyways, the only way I could get the latest master was manually download it.  Then I added it to a vendor/gems directory, then referenced it like:

gem 'forem', :path => "#{File.expand_path(**FILE**)}/../vendor/gems/forem-0.1"

Is version 0.1 the latest?  Is there a newer/better way of doing this?

**Comment by radar** [comment]
The command in the instructions will pull down the latest master. Could you explain to me what the difference is between these two downloads?

**Comment by supairish** [comment]
Hmm maybe it's something else then, using; gem 'forem', :git => "git://github.com/radar/forem.git" in my Gemfile with bundle install gives me

Using simple_form (1.4.2) 
Using forem (0.1) from git://github.com/radar/forem.git (at master)

So that looks good, but when I unpack the gem, I get

irish-macbookpro:~/Projects/mww/vendor/gems(master)$ gem unpack forem
Unpacked gem: '/Users/cirish/Projects/mww/vendor/gems/forem-0.0.1'

Notice the 0.0.1 now, upon inspecting this it's the code from the 0.0.1 tag not master.  Not sure how it's 0.0.1 now as I don't even have forem installed locally.

irish-macbookpro:~/Projects/mww/vendor/gems(master)$ gem list forem

**\* LOCAL GEMS ***

irish-macbookpro:~/Projects/mww/vendor/gems(master)$ 

So does unpacking a remotely referenced gem pull the last tag, instead of master?  That's the only thing I can think of that's happening and confusing me

**Comment by radar** [comment]
`gem unpack` will read from RubyGems as far as I am aware, which is why you're getting the 0.0.1 version which is the version on RubyGems. We would recommend installing it from GitHub exclusively and not placing it in vendor/gems unless absolutely necessary.

**Comment by supairish** [comment]
Gotcha, well the only reason I was unpacking it was because I couldn't figure out how to override the layouts used by the controllers in the Forem Engine.  Is there an easy way to do that?

**Comment by radar** [comment]
The layouts used by the controllers in forem is just your own `layouts/application.html.erb`. For the actual _templates_ for the actions, you will need to override the files in your application's `app/views` directory. At the moment, this is just a matter of straight copying.

However, it would probably be good to have a `rake forem:views` Rake task to copy these over. Patches welcome :)

**Comment by supairish** [comment]
Understood, but I'm trying to get the forem controllers to use a layout file other than layouts/application.html.erb from my app, i.e. layouts/forem.html.erb

Also, in a side note, I wasn't able to get the forem helper "forem_theme_tag" to work in my application layout, without changing the forem engine.rb file to have an initializer block like so:

``` ruby
module ::Forem
  class Engine < Rails::Engine
    isolate_namespace Forem

    class << self
      attr_accessor :root
      def root
        @root ||= Pathname.new(File.expand_path('../../', __FILE__))
      end
    end

    initializer 'engine.helper' do |app|
      ActionView::Base.send :include, Forem::ApplicationHelper
    end
  end
end
```

Not sure if Engines are suppose to do this including auto-magically, but I needed it in my app.  I'll look into a patch for that rake task.

**Comment by parndt** [comment]
That doesn't seem right, we shouldn't be including our application helper that magically.

Perhaps the instructions should tell us to do this manually.. for example:

``` ruby
module ApplicationHelper
  include ::Forem::ApplicationHelper
end
```

**Comment by radar** [comment]
Could you explain what problem that is fixing? I am not sure...

**Comment by supairish** [comment]
If you try using the forem_theme_tag helper in a layout defined in your main app, it's not available.  Either of the tricks above make it available.  Perhaps there's a better way to do that but I'm not very familiar with the internal workings of Rails 3 Engines.  I'm guessing the assumption with forem was that you wouldn't embed it's views in a layout defined in the main app?

**Comment by radar** [comment]
I removed that in 8e932aa. I would recommend you manually put the directive in your own CSS files to include them or alternatively specify the theme's CSS files in your layout. Either way will require the asset pipeline to be enabled.

**Comment by radar** [comment]
To clarify: I removed it because I was encountering this issue on the demo app (http://forem.heroku.com) too. I figured it's much easier to use the features already provided by Sprockets to just implement it... rather than coding another helper ourselves.

**Comment by parndt** [comment]
+1 - that's why we retired [refinerycms-theming](https://github.com/resolve/refinerycms-theming#readme) .. it was too hard to maintain.

Using built-ins is so much better.

**Comment by supairish** [comment]
Gotcha, thanks for the clarification
