### ISSUE TITLE
"Name Error: uninitialized constant Forem" when mounting in routes.rb

### ISSUE THREAD

**Issue by notontilt09** [rubysherpas/forem#361]
Very new to rails, trying to install Forem engine.  However, when I add the line

<code> mount Forem::Engine, :at => "/" </code>

I'm getting a:

NameError
<code>uninitialized constant Forem</code>

I've run through the installation multiple times, so it should not have a problem recognizing "Forem", but it does.  

Any ideas?  Likely a very basic solution, but I'm about 1 week into rails, and have 0 experience.

**Comment by parndt** [comment]
Do you have forem in your Gemfile?

**Comment by radar** [comment]
Did you only run the installer after starting the rails server? If so, you will need to restart the server.

**Comment by notontilt09** [comment]
restarting rails server did the trick.  Thanks!

**Comment by RashmiGunasekaran** [comment]
thanks...it still helps
