### ISSUE TITLE
No Uninstall Task

### ISSUE THREAD

**Issue by ctilley83** [rubysherpas/forem#365]
How do I remove this from my application?

**Comment by radar** [comment]
Do the opposite of the install script.

**Comment by ctilley83** [comment]
rails g forem:uninstall did not work

**Comment by parndt** [comment]
As it's a rails generator just run:

```
rails destroy forem:install
```

It'll do the opposite of everything.

**Comment by radar** [comment]
There is no `rails g forem:uninstall`. And `rails destroy forem:install` won't do everything correctly. For instance, it won't delete the tables in the database.

To elaborate:

Read this first: https://github.com/radar/forem/blob/master/lib/generators/forem/install_generator.rb
1. Remove all migrations from db/migrate that have "forem" in their names.
2. Remove config/initializers/forem.rb
3. Remove the mounting line from config/routes.rb
4. Remove the line in your Gemfile.
5. Delete the forem_\* tables in your application's database.

**Comment by ctilley83** [comment]
ok

**Comment by LightbulbProductions** [comment]
Hi, I am having this issue and have followed everything to try to delete this from my app. Is there anyone that has successfully taken it out? I have to reinstall other gems and this one is not allowing them...plus, I really just need it gone.

**Comment by pickhardt** [comment]
@LightbulbProductions did you do all of these:
1. Remove all migrations from db/migrate that have "forem" in their names.
2. Remove config/initializers/forem.rb
3. Remove the mounting line from config/routes.rb
4. Remove the line in your Gemfile.
5. Delete the forem_\* tables in your application's database.

I would actually do it in this order:
1. Remove forem from your Gemfile
2. Remove forem files from your config/initializers
3. Add new migrations to drop the forem_ tables
4. Run bundle install and rake db:migrate
5. If for some reason it doesn't load or doesn't run, follow the exception to the line something is still using Forem, and fix that line.

If you did all that, post the exception that's occurring and we'll have a look.
