### ISSUE TITLE
"forem_categories" does not exist

### ISSUE THREAD

**Issue by kashiftufail** [rubysherpas/forem#368]
Hi,

i have app deployed here (metnet.herokuappp.com) and have implemented devise user model already and now i want forem feature and follow instruction here       https://github.com/radar/forem/wiki/Installing---Upgrading

After successfully bundle install when i give this command 

```
rails g forem:install
```

I have error below

```
/home/kashif/.rvm/gems/ruby-1.9.3-p327@metnet/gems/activerecord-3.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:1153:in `async_exec': 
PG::Error: ERROR:  relation "forem_categories" does not exist (ActiveRecord::StatementInvalid)
```

``` sql
LINE 5:              WHERE a.attrelid = '"forem_categories"'::regcla...
                                        ^
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = '"forem_categories"'::regclass
               AND a.attnum > 0 AND NOT a.attisdropped
             ORDER BY a.attnum
```

I don't understand why this error is occuring and no migration is copied with this command `rails g forem:install`. But i have category model already in my app. 

Is it cause of error?

**Comment by parndt** [comment]
Your model shouldn't be able to cause this due to our namespacing.. unless your model was called `Forem::Category`.

Can you please give us a full trace of `rake db:migrate --trace`?

**Comment by kashiftufail** [comment]
I can't tell about  rake db:migrate --trace , Because no migration is copied when i give this command

```
       rails g forem:install
```

So how i can figure out error?

In rake db:migrate --trace just my migration of app simply will be run.

Thanks

**Comment by parndt** [comment]
What about: 

rake forem:install:migrations

**Comment by kashiftufail** [comment]
Now migration copied successfully and 

```
          rake db:migrate --trace    give me this error
```

==  AddForemAdmin: migrating ==================================================
rake aborted!
An error has occurred, this and all later migrations canceled:

undefined method `table_name' for nil:NilClass
/home/kashif/rails/alisa/metnet_exp/metnet_before_forum/db/migrate/20130116022438_add_forem_admin.forem.rb:10:in`user_class'
/home/kashif/rails/alisa/metnet_exp/metnet_before_forum/db/migrate/20130116022438_add_forem_admin.forem.rb:4:in `change'
/home/kashif/.rvm/gems/ruby-1.9.3-p327@metnet/gems/activerecord-3.2.11/lib/active_record/migration.rb:407:in`block (2 levels) in migrate'
/home/kashif/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
/home/kashif/.rvm/gems/ruby-1.9.3-p327@metnet/gems/activerecord-3.2.11/lib/active_record/migration.rb:407:in`block in migrate'
/home/kashif/.rvm/gems/ruby-1.9.3-p327@metnet/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'

**Comment by parndt** [comment]
Right… because the installer failed and it doesn't know what is your Forem.user_class  

So unless we can get the installer to run I'm not being very helpful sorry.

Are you able to take your application back to before you included Forem and try again or give us steps to reproduce this?

**Comment by UsmanJ** [comment]
@kashiftufail Did you manage to solve this issue? I think I am having a similar issue. I am getting the following error when I try to migrate db to heroku:

```
➜  martial_nation_forem git:(master) heroku run rake db:migrate
Running rake db:migrate on martialnationforum... up, run.2185
== 20160109142235 AddForemAdmin: migrating ====================================
-- column_exists?(:users, :forem_admin)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 5:                WHERE a.attrelid = '"users"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"users"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
```
