### ISSUE TITLE
Forem dependency on railties 3.2.11

### ISSUE THREAD

**Issue by djee** [rubysherpas/forem#369]
After adding this line to my gemfile:
gem 'forem', :git => "git://github.com/radar/forem.git"

and running bundle install. I get the following bundle error:

Bundler could not find compatible versions for gem "railties":
In Gemfile:
forem (>= 0) ruby depends on
railties (>= 3.2.11) ruby

rails (= 3.1.10) ruby depends on
railties (3.1.10)

I check the gemspec and couldn't see any railties dependency to Rails 3.2.x  Am I missing something?

**Comment by radar** [comment]
Could you please show us your whole Gemfile?

**Comment by djee** [comment]
I'm not comfortable to share the gemfile in plain sight.

Is there something specific that you are searching for !?

**Comment by radar** [comment]
The Rails version specified in it, and any gems that themselves may have
dependencies on older versions of Rails.

**Comment by djee** [comment]
Rails version is 3.1.10

For each dependency I'll have a look a bit later as I'm on something else right now.

I'll get back to you.

**Comment by radar** [comment]
Rails version needs to be bumped to 3.2.11 to be compatible with Forem.

**Comment by djee** [comment]
Damn! Thanks for the quick help!

**Comment by parndt** [comment]
Why is that? The gemspec says ~> 3.1

**Comment by radar** [comment]
I'm guessing it's one of our dependencies. I don't know which one. Doesn't hurt to be on the latest Rails.

**Comment by parndt** [comment]
@djee problem solved.. please use bundle update

**Comment by djee** [comment]
@parndt Fix the problem I had installing the gem!  Thanks a lot for that!
