### ISSUE TITLE
Using Forem to Comment on Articles?

### ISSUE THREAD

**Issue by ghost** [rubysherpas/forem#370]
We recently added Forem for our discussion group and are very happy with it.

Right now, we use disqus for commenting on our articles but want to get rid of it. 

Is there any way or best practices of using Forem to comment on articles (i.e., other content outside of forem_topics)?  Basically associate a forem_topic/posts with /underneath each article.

I am aware of Rails commenting gems but it seems that it would be less repetition if we could reuse/adapt forem for our articles.

Any advice would be appreciated.

**Comment by knewter** [comment]
We did this on alabamaintel.com

Each article automatically created a forum thread with the first post
linked to the article. We then embedded that thread, sans the first post,
under the article. Added inline posting form and done.

**Comment by ipvideomarketinfo** [comment]
Thanks Josh!

Can you explain what you mean by 'first post linked to that article'? Also, did you have any issues with the referenced URLs in the email notification?

**Comment by knewter** [comment]
The post that started the thread has a link to the article. That way people
browsing that thread had a link to the article that caused it.

I don't recall problems with email links but that was long ago

**Comment by radar** [comment]
Is this issue now solved @jhonovich?

**Comment by ipvideomarketinfo** [comment]
We are going to try this. Ryan, do you have any suggestions or see any concerns of using Forem for commenting on articles?

**Comment by radar** [comment]
I can't really offer anything more than @knewter has already offered. If you link an article to an automatically generated topic on the forum, it should Just Work(tm). Let us know if there's anything that could be improved around that.

**Comment by ipvideomarketinfo** [comment]
Thanks!
