### ISSUE TITLE
Bro i'm going to disrupt your life if you push my fucking buttons

### ISSUE THREAD

**Issue by whitmanc** [rubysherpas/forem#371]
Bro i'm going to disrupt your life if you push my fucking buttons

**Comment by mlambie** [comment]
Come at me bro.

**Comment by parndt** [comment]
Excuse me?

**Comment by radar** [comment]
Not an actual issue.

**Comment by sevenseacat** [comment]
A+ would read again

**Comment by epochwolf** [comment]
Classy.

**Comment by ghost** [comment]
Oooo, slug fest! Lets get it on!

**Comment by mlambie** [comment]
![come_at_me_bro__by_straubass-d55sn4c](https://f.cloud.github.com/assets/26192/82279/7c34e334-639a-11e2-871e-240c837383c5.gif)

**Comment by ghost** [comment]
@whitmanc quit it man, you're better than this and you're needlessly burning bridges you don't need to. Take a few days off from the computer. Get your mind right and come back. All will be forgiven if you can the crap right now, don't go pushing and doing things you can't come back from. You're better than this!
