### ISSUE TITLE
Question about spanish translation

### ISSUE THREAD

**Issue by mauriciopasquier** [rubysherpas/forem#377]
I have a question to prior spanish translators (@JohanB ?). Looking at the translation file, Forum/Forums is used instead of the spanish word Foro/Foros.. and that's the only case I think. What was the reason to keep it untranslated?

**Comment by radar** [comment]
I don't think there's a reason to leave it untranslated. Could you please submit a PR to fix it?

**Comment by mauriciopasquier** [comment]
Working on it

**Comment by mauriciopasquier** [comment]
I did some general proofreading also, is it ok to commit it there or do you want a separate PR?

**Comment by mauriciopasquier** [comment]
Well, I ended up doing PR #378 for this issue only. When it's merged I'll send another with the rest of the changes.

(triple post!)

**Comment by johanb** [comment]
I had no reason for not translating it.
