### ISSUE TITLE
Transfer ownership / delete the old textile / markdown formatters?

### ISSUE THREAD

**Issue by nruth** [rubysherpas/forem#382]
Hi

I just noticed a couple of year-old pull requests on these formatters I did I'm not sure how long ago. Aside from mysteriously not receiving any notifications from github about them, I'm not actively using them, and won't be able to maintain them. 

I don't want to name-squat, so I'd like to delete or transfer the repo & gems to someone else. What do you think would be best?

**Comment by radar** [comment]
I've just forked the forem-textile_formatter project and merged that one PR it had open. As for the markdown one, we've already got forem-redcarpet which is our Markdown formatter. 

Could you please just point both projects to their respective counterparts now in their READMEs? Thanks!

**Comment by parndt** [comment]
If you'd like to transfer the gems to us you can do so. For example, for me:

``` shell
gem owner:add gemname --email parndt@gmail.com
```

I can handle it from there :smile:

**Comment by nruth** [comment]
Will do both. Thanks.
