### ISSUE TITLE
Category model class name collision

### ISSUE THREAD

**Issue by kevinelliott** [rubysherpas/forem#387]
There is a Category model that already exists for this project that forem is being attached to. The Category model is very common in many Rails applications, and the fact that forem has a Category (instead of ForemCategory) model leads to collisions.

While renaming the local Category or putting it in it's own namespace and calling it explicitly everywhere is possible sometimes, it's unreasonable to make an assumption that the host app will want to do either of these.

Please rename Category model, or provide a way to configure this.

**Comment by kevinelliott** [comment]
This only occurs when mounting to /, and is understandable. Closing this issue.

**Comment by radar** [comment]
I don't understand this problem at all :\ Was it because it was using the /categories route and you had a similar route defined within your app too? If you don't want the routes to clash, then there's nothing we can do other than advise you _not_ to mount at root.
