### ISSUE TITLE
No route matches [GET] "/forums" after installation

### ISSUE THREAD

**Issue by pickhardt** [rubysherpas/forem#388]
I just installed Forem and mounted the engine from my routes.rb file.  However, I get the following error trying to access /forums (while both signed in and signed out):

No route matches `[GET] "/forums"`

Why could this be?  "rake routes" suggests it's mounting correctly...

``` shell
$ rake routes
          root        /                                                static#index
             ...
        signup        /signup(.:format)                                users#new
        signin        /signin(.:format)                                sessions#new
       signout        /signout(.:format)                               sessions#destroy
         forem        /forums                                          Forem::Engine

Routes for Forem::Engine:
                      root        /                                                     forem/forums#index
     subscribe_forum_topic GET    /forums/:forum_id/topics/:id/subscribe(.:format)      forem/topics#subscribe
   unsubscribe_forum_topic GET    /forums/:forum_id/topics/:id/unsubscribe(.:format)    forem/topics#unsubscribe
              forum_topics GET    /forums/:forum_id/topics(.:format)                    forem/topics#index
                           POST   /forums/:forum_id/topics(.:format)                    forem/topics#create
           new_forum_topic GET    /forums/:forum_id/topics/new(.:format)                forem/topics#new
          edit_forum_topic GET    /forums/:forum_id/topics/:id/edit(.:format)           forem/topics#edit
               forum_topic GET    /forums/:forum_id/topics/:id(.:format)                forem/topics#show
                           PUT    /forums/:forum_id/topics/:id(.:format)                forem/topics#update
                           DELETE /forums/:forum_id/topics/:id(.:format)                forem/topics#destroy
                    forums GET    /forums(.:format)                                     forem/forums#index
                     forum GET    /forums/:id(.:format)                                 forem/forums#show
               topic_posts GET    /topics/:topic_id/posts(.:format)                     forem/posts#index
                           POST   /topics/:topic_id/posts(.:format)                     forem/posts#create
            new_topic_post GET    /topics/:topic_id/posts/new(.:format)                 forem/posts#new
           edit_topic_post GET    /topics/:topic_id/posts/:id/edit(.:format)            forem/posts#edit
                topic_post GET    /topics/:topic_id/posts/:id(.:format)                 forem/posts#show
                           PUT    /topics/:topic_id/posts/:id(.:format)                 forem/posts#update
                           DELETE /topics/:topic_id/posts/:id(.:format)                 forem/posts#destroy
                    topics GET    /topics(.:format)                                     forem/topics#index
                           POST   /topics(.:format)                                     forem/topics#create
                 new_topic GET    /topics/new(.:format)                                 forem/topics#new
                     topic GET    /topics/:id(.:format)                                 forem/topics#show
                           DELETE /topics/:id(.:format)                                 forem/topics#destroy
     forum_moderator_tools GET    /forums/:forum_id/moderation(.:format)                forem/moderation#index
      forum_moderate_posts PUT    /forums/:forum_id/moderate/posts(.:format)            forem/moderation#posts
      moderate_forum_topic PUT    /forums/:forum_id/topics/:topic_id/moderate(.:format) forem/moderation#topic
                categories GET    /categories(.:format)                                 forem/categories#index
                  category GET    /categories/:id(.:format)                             forem/categories#show
                admin_root        /admin(.:format)                                      forem/admin/base#index
       admin_group_members GET    /admin/groups/:group_id/members(.:format)             forem/admin/members#index
                           POST   /admin/groups/:group_id/members(.:format)             forem/admin/members#create
    new_admin_group_member GET    /admin/groups/:group_id/members/new(.:format)         forem/admin/members#new
   edit_admin_group_member GET    /admin/groups/:group_id/members/:id/edit(.:format)    forem/admin/members#edit
        admin_group_member GET    /admin/groups/:group_id/members/:id(.:format)         forem/admin/members#show
                           PUT    /admin/groups/:group_id/members/:id(.:format)         forem/admin/members#update
                           DELETE /admin/groups/:group_id/members/:id(.:format)         forem/admin/members#destroy
              admin_groups GET    /admin/groups(.:format)                               forem/admin/groups#index
                           POST   /admin/groups(.:format)                               forem/admin/groups#create
           new_admin_group GET    /admin/groups/new(.:format)                           forem/admin/groups#new
          edit_admin_group GET    /admin/groups/:id/edit(.:format)                      forem/admin/groups#edit
               admin_group GET    /admin/groups/:id(.:format)                           forem/admin/groups#show
                           PUT    /admin/groups/:id(.:format)                           forem/admin/groups#update
                           DELETE /admin/groups/:id(.:format)                           forem/admin/groups#destroy
    admin_forum_moderators GET    /admin/forums/:forum_id/moderators(.:format)          forem/admin/moderators#index
                           POST   /admin/forums/:forum_id/moderators(.:format)          forem/admin/moderators#create
 new_admin_forum_moderator GET    /admin/forums/:forum_id/moderators/new(.:format)      forem/admin/moderators#new
edit_admin_forum_moderator GET    /admin/forums/:forum_id/moderators/:id/edit(.:format) forem/admin/moderators#edit
     admin_forum_moderator GET    /admin/forums/:forum_id/moderators/:id(.:format)      forem/admin/moderators#show
                           PUT    /admin/forums/:forum_id/moderators/:id(.:format)      forem/admin/moderators#update
                           DELETE /admin/forums/:forum_id/moderators/:id(.:format)      forem/admin/moderators#destroy
              admin_forums GET    /admin/forums(.:format)                               forem/admin/forums#index
                           POST   /admin/forums(.:format)                               forem/admin/forums#create
           new_admin_forum GET    /admin/forums/new(.:format)                           forem/admin/forums#new
          edit_admin_forum GET    /admin/forums/:id/edit(.:format)                      forem/admin/forums#edit
               admin_forum GET    /admin/forums/:id(.:format)                           forem/admin/forums#show
                           PUT    /admin/forums/:id(.:format)                           forem/admin/forums#update
                           DELETE /admin/forums/:id(.:format)                           forem/admin/forums#destroy
          admin_categories GET    /admin/categories(.:format)                           forem/admin/categories#index
                           POST   /admin/categories(.:format)                           forem/admin/categories#create
        new_admin_category GET    /admin/categories/new(.:format)                       forem/admin/categories#new
       edit_admin_category GET    /admin/categories/:id/edit(.:format)                  forem/admin/categories#edit
            admin_category GET    /admin/categories/:id(.:format)                       forem/admin/categories#show
                           PUT    /admin/categories/:id(.:format)                       forem/admin/categories#update
                           DELETE /admin/categories/:id(.:format)                       forem/admin/categories#destroy
   toggle_hide_admin_topic PUT    /admin/topics/:id/toggle_hide(.:format)               forem/admin/topics#toggle_hide
   toggle_lock_admin_topic PUT    /admin/topics/:id/toggle_lock(.:format)               forem/admin/topics#toggle_lock
    toggle_pin_admin_topic PUT    /admin/topics/:id/toggle_pin(.:format)                forem/admin/topics#toggle_pin
              admin_topics GET    /admin/topics(.:format)                               forem/admin/topics#index
                           POST   /admin/topics(.:format)                               forem/admin/topics#create
           new_admin_topic GET    /admin/topics/new(.:format)                           forem/admin/topics#new
          edit_admin_topic GET    /admin/topics/:id/edit(.:format)                      forem/admin/topics#edit
               admin_topic GET    /admin/topics/:id(.:format)                           forem/admin/topics#show
                           PUT    /admin/topics/:id(.:format)                           forem/admin/topics#update
                           DELETE /admin/topics/:id(.:format)                           forem/admin/topics#destroy
  admin_users_autocomplete GET    /admin/users/autocomplete(.:format)                   forem/admin/users#autocomplete
```

**Comment by knewter** [comment]
Where is forem mounted in your app?

On Wed, Feb 27, 2013 at 12:40 PM, Jeff Pickhardt
notifications@github.comwrote:

> I just installed Forem and mounted the engine from my routes.rb file.
> However, I get the following error trying to access /forums (while both
> signed in and signed out):
> 
> No route matches [GET] "/forums"
> 
> Why could this be? "rake routes" suggests it's mounting correctly...
> 
> $ rake routes
> root / static#index
> ...
> signup /signup(.:format) users#new
> signin /signin(.:format) sessions#new
> signout /signout(.:format) sessions#destroy
> forem /forums Forem::Engine
> 
> Routes for Forem::Engine:
> root / forem/forums#index
> subscribe_forum_topic GET /forums/:forum_id/topics/:id/subscribe(.:format)
> forem/topics#subscribe
> unsubscribe_forum_topic GET
> /forums/:forum_id/topics/:id/unsubscribe(.:format) forem/topics#unsubscribe
> forum_topics GET /forums/:forum_id/topics(.:format) forem/topics#index
> POST /forums/:forum_id/topics(.:format) forem/topics#create
> new_forum_topic GET /forums/:forum_id/topics/new(.:format) forem/topics#new
> edit_forum_topic GET /forums/:forum_id/topics/:id/edit(.:format)
> forem/topics#edit
> forum_topic GET /forums/:forum_id/topics/:id(.:format) forem/topics#show
> PUT /forums/:forum_id/topics/:id(.:format) forem/topics#update
> DELETE /forums/:forum_id/topics/:id(.:format) forem/topics#destroy
> forums GET /forums(.:format) forem/forums#index
> forum GET /forums/:id(.:format) forem/forums#show
> topic_posts GET /topics/:topic_id/posts(.:format) forem/posts#index
> POST /topics/:topic_id/posts(.:format) forem/posts#create
> new_topic_post GET /topics/:topic_id/posts/new(.:format) forem/posts#new
> edit_topic_post GET /topics/:topic_id/posts/:id/edit(.:format)
> forem/posts#edit
> topic_post GET /topics/:topic_id/posts/:id(.:format) forem/posts#show
> PUT /topics/:topic_id/posts/:id(.:format) forem/posts#update
> DELETE /topics/:topic_id/posts/:id(.:format) forem/posts#destroy
> topics GET /topics(.:format) forem/topics#index
> POST /topics(.:format) forem/topics#create
> new_topic GET /topics/new(.:format) forem/topics#new
> topic GET /topics/:id(.:format) forem/topics#show
> DELETE /topics/:id(.:format) forem/topics#destroy
> forum_moderator_tools GET /forums/:forum_id/moderation(.:format)
> forem/moderation#index
> forum_moderate_posts PUT /forums/:forum_id/moderate/posts(.:format)
> forem/moderation#posts
> moderate_forum_topic PUT
> /forums/:forum_id/topics/:topic_id/moderate(.:format) forem/moderation#topic
> categories GET /categories(.:format) forem/categories#index
> category GET /categories/:id(.:format) forem/categories#show
> admin_root /admin(.:format) forem/admin/base#index
> admin_group_members GET /admin/groups/:group_id/members(.:format)
> forem/admin/members#index
> POST /admin/groups/:group_id/members(.:format) forem/admin/members#create
> new_admin_group_member GET /admin/groups/:group_id/members/new(.:format)
> forem/admin/members#new
> edit_admin_group_member GET
> /admin/groups/:group_id/members/:id/edit(.:format) forem/admin/members#edit
> admin_group_member GET /admin/groups/:group_id/members/:id(.:format)
> forem/admin/members#show
> PUT /admin/groups/:group_id/members/:id(.:format)
> forem/admin/members#update
> DELETE /admin/groups/:group_id/members/:id(.:format)
> forem/admin/members#destroy
> admin_groups GET /admin/groups(.:format) forem/admin/groups#index
> POST /admin/groups(.:format) forem/admin/groups#create
> new_admin_group GET /admin/groups/new(.:format) forem/admin/groups#new
> edit_admin_group GET /admin/groups/:id/edit(.:format)
> forem/admin/groups#edit
> admin_group GET /admin/groups/:id(.:format) forem/admin/groups#show
> PUT /admin/groups/:id(.:format) forem/admin/groups#update
> DELETE /admin/groups/:id(.:format) forem/admin/groups#destroy
> admin_forum_moderators GET /admin/forums/:forum_id/moderators(.:format)
> forem/admin/moderators#index
> POST /admin/forums/:forum_id/moderators(.:format)
> forem/admin/moderators#create
> new_admin_forum_moderator GET
> /admin/forums/:forum_id/moderators/new(.:format) forem/admin/moderators#new
> edit_admin_forum_moderator GET
> /admin/forums/:forum_id/moderators/:id/edit(.:format)
> forem/admin/moderators#edit
> admin_forum_moderator GET /admin/forums/:forum_id/moderators/:id(.:format)
> forem/admin/moderators#show
> PUT /admin/forums/:forum_id/moderators/:id(.:format)
> forem/admin/moderators#update
> DELETE /admin/forums/:forum_id/moderators/:id(.:format)
> forem/admin/moderators#destroy
> admin_forums GET /admin/forums(.:format) forem/admin/forums#index
> POST /admin/forums(.:format) forem/admin/forums#create
> new_admin_forum GET /admin/forums/new(.:format) forem/admin/forums#new
> edit_admin_forum GET /admin/forums/:id/edit(.:format)
> forem/admin/forums#edit
> admin_forum GET /admin/forums/:id(.:format) forem/admin/forums#show
> PUT /admin/forums/:id(.:format) forem/admin/forums#update
> DELETE /admin/forums/:id(.:format) forem/admin/forums#destroy
> admin_categories GET /admin/categories(.:format)
> forem/admin/categories#index
> POST /admin/categories(.:format) forem/admin/categories#create
> new_admin_category GET /admin/categories/new(.:format)
> forem/admin/categories#new
> edit_admin_category GET /admin/categories/:id/edit(.:format)
> forem/admin/categories#edit
> admin_category GET /admin/categories/:id(.:format)
> forem/admin/categories#show
> PUT /admin/categories/:id(.:format) forem/admin/categories#update
> DELETE /admin/categories/:id(.:format) forem/admin/categories#destroy
> toggle_hide_admin_topic PUT /admin/topics/:id/toggle_hide(.:format)
> forem/admin/topics#toggle_hide
> toggle_lock_admin_topic PUT /admin/topics/:id/toggle_lock(.:format)
> forem/admin/topics#toggle_lock
> toggle_pin_admin_topic PUT /admin/topics/:id/toggle_pin(.:format)
> forem/admin/topics#toggle_pin
> admin_topics GET /admin/topics(.:format) forem/admin/topics#index
> POST /admin/topics(.:format) forem/admin/topics#create
> new_admin_topic GET /admin/topics/new(.:format) forem/admin/topics#new
> edit_admin_topic GET /admin/topics/:id/edit(.:format)
> forem/admin/topics#edit
> admin_topic GET /admin/topics/:id(.:format) forem/admin/topics#show
> PUT /admin/topics/:id(.:format) forem/admin/topics#update
> DELETE /admin/topics/:id(.:format) forem/admin/topics#destroy
> admin_users_autocomplete GET /admin/users/autocomplete(.:format)
> forem/admin/users#autocomplete
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/radar/forem/issues/388
> .

## 

_Josh Adams_
CTO | isotope|eleven http://www.isotope11.com
[cell](205) 215-3957
[work](877) 476-8671 x201

**Comment by pickhardt** [comment]
It was the default:  mount Forem::Engine, :at => '/forums'

I'm closing this ticket, however, because after restarting rails, it works.  Usually you don't have to restart, don't know why that was necessary in this case, but whatever.

**Comment by parndt** [comment]
Thanks - restarting rails when working with engines fixes many issues.
