### ISSUE TITLE
Feature request: Provide a basic "forem.css" file rather than themes

### ISSUE THREAD

**Issue by pickhardt** [rubysherpas/forem#390]
It'd be really convenient to have a basic forem.css file that I can take and modify on my own, rather than using these pre-built themes.  One reason is that I don't know where I go to modify the pre-built themes.  Another reason is that I want to style the forum to match my site, but I want a basic css file to start from, too.

**Comment by pickhardt** [comment]
You can always take one of these:

https://github.com/radar/forem-theme-twist/blob/master/app/assets/stylesheets/forem/twist/style.css.scss

This should be added to the "theming" instructions.

**Comment by parndt** [comment]
Can you add it?

**Comment by parndt** [comment]
So to clarify do you want an empty forem.css file to always be included? I am not sure about doing that. It adds overhead to every request.

**Comment by pickhardt** [comment]
No, not an empty forem.css file  What I mean to say is that, as a new user implementing forem, I expected there to be some default style file that I could take and modify to suit my style.  As it is, I dug around and found the one I linked to above, then included it in my own /assets and application.css file.

The "theming forem" page should include some instructions for "creating your own style based off of a default skeleton" and then link to a base css file.

**Comment by radar** [comment]
We'll be providing a gem which provides some views and a default CSS template as part of the work on the gem release as discussed in #666
