### ISSUE TITLE
Deleting action not found?

### ISSUE THREAD

**Issue by pickhardt** [rubysherpas/forem#391]
I have a brand new install of Forem.  It appears to be more-or-less working, but the "delete" action doesn't work from the administration panel:

![forem-no-action](https://f.cloud.github.com/assets/610082/202588/9c80d450-8117-11e2-98e5-5d1ee6785693.png)
![forem-no-action2](https://f.cloud.github.com/assets/610082/202589/9c93e7fc-8117-11e2-8c33-6c5069727bba.png)

**Comment by radar** [comment]
Please show us the layout file from your app, as well as application.js. I suspect jquery_ujs isn't being included.

**Comment by pickhardt** [comment]
Yes, that was the problem.  A list of dependencies should be added to the instructions... I didn't know that jquery_ujs was needed.
