### ISSUE TITLE
uninitialized constant Forem::Engine

### ISSUE THREAD

**Issue by oceanbreeze** [rubysherpas/forem#393]
Hello, what I am doing wrong? Please help :)

[root@OceanBreeze ProjectX]# rails g forem:install
Copying over Forem migrations...
rake aborted!
Don't know how to build task 'forem:install:migrations'

(See full trace by running task with --trace)
What is your user class called? [User] [User]
What is the current_user helper called in your app? [current_user] [users_helper]
Defining forem_user method inside ApplicationController...
      insert  app/controllers/application_controller.rb
Skipping config/initializers/forem.rb creation, as file already exists!
Running rake db:migrate
Creating default forum and topic
/usr/local/rvm/gems/ruby-2.0.0-p0/bundler/gems/forem-80f44dc62d77/lib/generators/forem/install_generator.rb:67:in `seed_database': uninitialized constant Forem::Engine (NameError)
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/thor-0.17.0/lib/thor/task.rb:27:in`run'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in`block in invoke_all'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `each'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in`map'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `invoke_all'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/thor-0.17.0/lib/thor/group.rb:238:in`dispatch'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/thor-0.17.0/lib/thor/base.rb:434:in `start'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/generators.rb:171:in`invoke'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/commands/generate.rb:12:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/commands.rb:29:in`<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in`<main>'

**Comment by radar** [comment]
I _suspect_ this night be a ruby 2.0 bug. Have you tried on 1.9.3 as well?

**Comment by oceanbreeze** [comment]
Hey, thank you, sadly I haven't tried this with Ruby 1.9.3, since I don't have it installed on my main development PC right now (switched to 2.0 since official release).

Maybe this is 'kaminari' gem bug? Will try with will-paginate a bit later.

**Comment by radar** [comment]
Howdy @oceanbreeze. I wasn't able to reproduce this issue on my computer tonight.

Do you have a list of steps you could use to reproduce it?
