### ISSUE TITLE
user object shown instead of user name

### ISSUE THREAD

**Issue by gmrubin** [rubysherpas/forem#394]
anytime user name should be shown, user object is being displayed instead.
on ruby 1.9.3p194

see this screenshot

https://www.evernote.com/shard/s197/sh/67464b18-e2b8-4a49-9090-3a9bfa6a1294/ad4661bd0af534f9b37ef2eca7d58146

**Comment by parndt** [comment]
Hmm.. can you write a failing test for this please that reproduces this in Forem's default codebase?

**Comment by radar** [comment]
This is because you've not defined the `to_s` method in your `User` model. Please do this, like so:

``` ruby
def to_s
  name
end
```

**Comment by gmrubin** [comment]
Thanks Ryan! The to_s method did fix this.

**Comment by parndt** [comment]
Or

```
alias_attribute :to_s, :name
```

**Comment by radar** [comment]
Yay. High fives all round.
