### ISSUE TITLE
quick css changes

### ISSUE THREAD

**Issue by JoeGH** [rubysherpas/forem#397]
I can live with it but it's not perfect ;)

All I want to do is change these two css statements (in the twist theme) because my admin post action buttons are overlapping: 

```
posts .post .contents {
  min-height: 125px;
}

#posts .post .contents .actions {
  top: 0px;
}
```

Is there any simple way to do this?
I already tried to override in app/assets/styelsheets/custom.css.scss but that didn't work.

**Comment by llecram** [comment]
Try using the !important rule in css to override any rule. For example with the code above try the code below and it should override any changes.

```
posts .post .contents {
  min-height: 125px !important;
}

#posts .post .contents .actions {
  top: 0px !important;
}
```

**Comment by JoeGH** [comment]
It worked!
Thank you mpurham.

Is this a best practice? I'm not so sure, but it does work.

**Comment by llecram** [comment]
Yes by using the !important rule you're telling you're css file to override for that specific argument which is considered best practice. Happy coding!
