### ISSUE TITLE
Unable to even start a new 'forem'.

### ISSUE THREAD

**Issue by mahlooo** [rubysherpas/forem#398]
I have tried various things and I keep getting this error:

_After editing Gemfile and putting the following:_

```
gem 'forem', :git => "git://github.com/radar/forem.git"
gem 'kaminari', '0.13.0'
```

_I then get this error:_

```
$ bundle install
```

Updating git://github.com/radar/forem.git
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using rake (10.0.3) 
Using i18n (0.6.4) 
Using multi_json (1.6.1) 
Using activesupport (3.2.12) 
Using builder (3.0.4) 
Using activemodel (3.2.12) 
Using erubis (2.7.0) 
Using journey (1.0.4) 
Using rack (1.4.5) 
Using rack-cache (1.2) 
Using rack-test (0.6.2) 
Using hike (1.2.1) 
Using tilt (1.3.5) 
Using sprockets (2.2.2) 
Using actionpack (3.2.12) 
Using mime-types (1.21) 
Using polyglot (0.3.3) 
Using treetop (1.4.12) 
Using mail (2.4.4) 
Using actionmailer (3.2.12) 
Using arel (3.0.2) 
Using tzinfo (0.3.37) 
Using activerecord (3.2.12) 
Using activerecord-jdbc-adapter (1.2.8) 
Using jdbc-sqlite3 (3.7.2.1) 
Using activerecord-jdbcsqlite3-adapter (1.2.7) 
Using activeresource (3.2.12) 
Using blankslate (3.1.2) 
Using bouncy-castle-java (1.5.0147) 
Using bundler (1.2.4) 
Using cancan (1.6.8) 
Using coffee-script-source (1.6.1) 
Using execjs (1.4.0) 
Using coffee-script (2.2.0) 
Using rack-ssl (1.3.3) 
Using json (1.7.7) 
Using rdoc (3.12.2) 
Using thor (0.17.0) 
Using railties (3.2.12) 
Using coffee-rails (3.2.2) 
Using decorators (1.0.3) 
Using ffi (1.0.11) 
Using rubypython (0.5.3) 
Using pygments.rb (0.2.4) 
Installing redcarpet (2.0.1) with native extensions 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

   /Users/username/.rvm/rubies/jruby-1.7.2/bin/jruby extconf.rb 
NotImplementedError: C extension support is not enabled. Pass -Xcext.enabled=true to JRuby or set JRUBY_OPTS or modify .jrubyrc to enable.

   (root) at /Users/username/.rvm/rubies/jruby-1.7.2/lib/ruby/shared/mkmf.rb:8
  require at org/jruby/RubyKernel.java:1027
   (root) at /Users/username/.rvm/rubies/jruby-1.7.2/lib/ruby/shared/rubygems/custom_require.rb:1
   (root) at extconf.rb:1

Gem files will remain installed in /Users/username/.rvm/gems/jruby-1.7.2/gems/redcarpet-2.0.1 for inspection.
Results logged to /Users/username/.rvm/gems/jruby-1.7.2/gems/redcarpet-2.0.1/ext/redcarpet/gem_make.out
An error occurred while installing redcarpet (2.0.1), and Bundler cannot continue.
Make sure that `gem install redcarpet -v '2.0.1'` succeeds before bundling.

**Comment by radar** [comment]
Sorry, we do not currently support JRuby.
