### ISSUE TITLE
Adding images to a forem post.

### ISSUE THREAD

**Issue by JoeGH** [rubysherpas/forem#399]
Just curious if there's any way to allow users to add an image to a forem post.

If not a regular user at least maybe a moderator could do it if he had access to the app/assets folder of the project in combination with the kramdown formatter gem.

Any thoughts?

**Comment by radar** [comment]
There isn't a file upload feature built into Forem to do that.

What you would typically do is upload the image to some other site and then link from there.

If you would like file upload functionality built into Forem, please write a pull request for this.

Thanks!

**Comment by JoeGH** [comment]
Using some other formatter than the default?

**Comment by radar** [comment]
Yes. Both the textile and markdown formatters support images.

**Comment by JoeGH** [comment]
Thanks. :+1:
