### ISSUE TITLE
Refinery 0.9.9.12 require 3.0.5 rails

### ISSUE THREAD

**Issue by artemk** [rubysherpas/forem#4]
your Gemfile.lock requires rails 3.1.0beta while RefineryCMS itself 3.0.5

**Comment by radar** [comment]
This is intentional. Forem will only work with refinery and Rails 3.1 at the moment. It should be considered an experimental release until 3.1 is out:

**Comment by parndt** [comment]
Hopefully RefineryCMS will have 3.1 support sometime soon so that we can relax the requirement. Unfortunately we've been bitten by even Rails' minor point releases in the past so we're being careful.
