### ISSUE TITLE
Add project to localeapp

### ISSUE THREAD

**Issue by cyrill62** [rubysherpas/forem#401]
It could be fine to have Forem locales on http://www.localeapp.com

**Comment by parndt** [comment]
What would this involve? Does it cost? If not, can you open a pull
request that does this please?

**Comment by cyrill62** [comment]
I think it's free for open source projets.
Only github repo owner can init the project on localeapp.

**Comment by radar** [comment]
I am in favour of this change and will look into it when I am more awake and alert.

**Comment by radar** [comment]
I've added Forem to LocaleApp now:

http://www.localeapp.com/projects/4021

I just arrived on the train in town on peak hour, so the internet
connection's a bit too shit to upload yaml files. Will try again tomorrow
morning.

**Comment by cyrill62** [comment]
Just change my status on this projet from "translator" to "developper" and I can import existing locales from yaml files.

Then make a pull request with new locales files.

**Comment by radar** [comment]
I've added all the existing translations via the import feature.

Could you now please do the PR @cyrill62?

**Comment by parndt** [comment]
English is only 93% translated. We should reconcile that before proceeding.

**Comment by radar** [comment]
I've updated the English locales with the correct translations.

**Comment by parndt** [comment]
I have [tweeted for help](https://twitter.com/parndt/status/318849841625194496) :-)
