### ISSUE TITLE
Adding ordering to Categories

### ISSUE THREAD

**Issue by osman-masood** [rubysherpas/forem#403]
I need to reorder some Categories, and I figure one way would be to change created_at, but of course that's extremely sloppy. I can submit a pull request to add in an 'order' (integer) column? 

Thanks!

**Comment by parndt** [comment]
What's the purpose (use case) of reordering categories?

**Comment by radar** [comment]
Displaying more prominent categories up front. For instance, railsforum.com has 'News and Rules' first: http://railsforum.com/

**Comment by osman-masood** [comment]
@radar  Yep, exactly.
