### ISSUE TITLE
bundler could not find compatible versions for gem "rails":

### ISSUE THREAD

**Issue by forsberg1** [rubysherpas/forem#404]
Dont know if this have already been up here, if so iam sorry.

Error on bundler.
Bundler could not find compatible versions for gem "rails":
  In Gemfile:

```
forem (>= 0) ruby depends on
  rails (!= 3.2.0, != 3.2.1, != 3.2.10, != 3.2.2, != 3.2.3, != 3.2.4, != 3.2.5, != 3.2.6, != 3.2.7, != 3.2.8, != 3.2.9, < 3.3, >= 3.1.10) ruby

  rails (3.2.9)
```

Any idea?

**Comment by forsberg1** [comment]
Did find a solution if any others out here have the same problems:

in gem file:

``` ruby
gem 'kaminari'
gem 'forem', :git => "https://github.com/radar/forem.git", :branch => "1-0-stable"
```

now working for me.

**Comment by radar** [comment]
Please use Rails 3.2.13, as that is the most secure version of rails released.

**Comment by radar** [comment]
1-0-stable lags significantly behind master. Please use master branch and a proper version of Rails.

**Comment by parndt** [comment]
Agreed, use the `master` branch and run ensure in your Gemfile you have:

``` ruby
gem rails, '~> 3.2.13'
```

Then run:

``` shell
bundle update rails
```

@radar @knewter should we even keep 1-0-stable around? What's it for?

**Comment by radar** [comment]
It was originally going to be a stable branch while we dev'd on master, but since master IS stable, we should delete it.

**Comment by parndt** [comment]
It has been thusly deleted.
