### ISSUE TITLE
Changing 'Forums' header to 'Topics' and 'Topics' to 'Threads'

### ISSUE THREAD

**Issue by s26mehta** [rubysherpas/forem#405]
I have been able to change 'Forums' to 'Topics' in the header and 'Topics' to 'Threads' on the home page of the forum in the header, underneath the category name. However, my problem is that in the url ../forums/forums/id doesn't change to ../forums/topics/id.

I have tried going to config/routes and adding
match "match "/forums/:id", :to => "forem/forums#show", :as => "/forums/topics/:id"
but it still doesn't work.

**Comment by parndt** [comment]
This doesn't strike me as an issue with Forem but a Rails routing
question. I think you will get a better answer if you should ask this
question on Stackoverflow :-)

**Comment by s26mehta** [comment]
It might actually be a forem issue because if you change the header from 'Forums' to 'Topics' it should automatically change in the url. I mean isn't that the reason we see /forums/forums/id when we click on any specific forum.

**Comment by parndt** [comment]
No that's the controller named forums under the mounted engine of the same name

**Comment by radar** [comment]
Controller names have nothing to do at all with the titles which are displayed on the page.

**Comment by s26mehta** [comment]
do u guys know how i can customize the url? Could it possibly be linked with namespace.

**Comment by radar** [comment]
Could you please show the code that you tried within `config/routes.rb` please? I need to know the whole context, so just showing the whole file would be a good idea.

**Comment by radar** [comment]
See also: http://stackoverflow.com/questions/5997527/overriding-named-routes-provided-by-rails-3-engines/14967741#14967741

**Comment by s26mehta** [comment]
Do u know how i can avoid the double /forums/forums in the url?

**Comment by radar** [comment]
You can change the mount point of forem within config/routes.rb
