### ISSUE TITLE
rails 4?

### ISSUE THREAD

**Issue by mauriciopasquier** [rubysherpas/forem#421]
Are there plans for rails 4 support? Can't find anything in the issues or anywhere. That said, I haven't tested if forem already works with it :P 

[This roadmap](https://github.com/radar/forem/wiki/1.0-Roadmap) seems old.. or is it still valid? I mean, version has been 1.0.0beta for a year, still no tag, no release. I asume something like "1.0 stable" is close, right?

**Comment by parndt** [comment]
There are plans to support it - want to help?

**Comment by mauriciopasquier** [comment]
I don't know what could be needed, and I have little to none experience with engines, but yeah, why not? :P

**Comment by parndt** [comment]
Only one way to get experienced :) Thanks!

**Comment by namiwang** [comment]
Since I'm currently using rails 4 rc1, is there any way I can integrate forem into my app now?

**Comment by radar** [comment]
@namiheike No, not yet. But:

> There are plans to support it - want to help?

**Comment by namiwang** [comment]
@radar 
Always. Anything I can do?

**Comment by radar** [comment]
@namiheike Sure! The best thing to do would be to create a new branch, upgrade the rails version to Rails 4, run the tests and fix what breaks.

**Comment by achru** [comment]
hi, 
i am working on upgrading it to rails 4 on this fork:
https://github.com/achru/forem ,
7 tests to go right now

**Comment by parndt** [comment]
:heart: :heart: :heart: :+1:

**Comment by achru** [comment]
i am pretty new to the stuff, solution is mostly hacky, becouse of friendly_id changes for rails4,
i have these errors if somebody can take a look:

```
Failures:
  1) Forem::Topic helper methods #register_view_by doesn't update the view time if less than 15 minutes ago
     Failure/Error: topic.view_for(view_user).current_viewed_at.to_i.should eq(frozen_time.to_i)

       expected: 1373399996
            got: 1373400056

       (compared using ==)
     # ./spec/models/topic_spec.rb:103:in `block (4 levels) in <top (required)>'

  2) Forem::Topic helper methods #register_view_by increments the users view count for the topic
     Failure/Error: }.to change { topic.view_for(view_user).count }.from(1).to(2)
     NoMethodError:
       undefined method `count' for nil:NilClass
     # ./spec/models/topic_spec.rb:92:in `block (5 levels) in <top (required)>'
     # ./spec/models/topic_spec.rb:90:in `block (4 levels) in <top (required)>'

  3) Forem::TopicsController attempting to subscribe to a hidden topic 
     Failure/Error: get :subscribe, :forum_id => 1, :id => 1
     ActiveRecord::RecordNotFound:
       Couldn't find Forem::Forum with id=1
     # ./app/controllers/forem/topics_controller.rb:90:in `find_forum'
     # ./spec/support/controller_hacks.rb:27:in `process_forem_action'
     # ./spec/support/controller_hacks.rb:5:in `get'
     # ./spec/controllers/topics_controller_spec.rb:20:in `block (3 levels) in <top (required)>'

  4) topics viewing a topic should have an autodiscover link tag
     Failure/Error: page.should have_selector("link[title='ATOM']")
     Capybara::ExpectationNotMet:
       expected to find css "link[title='ATOM']" but there were no matches. Also found "", which matched the selector but not all filters.
     # ./spec/features/topics_spec.rb:163:in `block (3 levels) in <top (required)>'
```

also, generator does not inject method to  application controller and routes.

**Comment by radar** [comment]
@achru Are you still having these difficulties?

**Comment by achru** [comment]
@radar  yep, any hints ?:)

**Comment by radar** [comment]
Looking into this now. Will create a rails4 branch when I'm done :)

**Comment by radar** [comment]
There is now a rails4 branch for Forem. Please try this out.

**Comment by radar** [comment]
Can you please include your Gemfile? That issue should not be happening in Rails 4.

**Comment by achru** [comment]
hi, its working fine, thank you,
the problem was of course protected_attributes in gemfile :)

**Comment by radar** [comment]
Good to hear, @achru. Thank you for replying.
