### ISSUE TITLE
Configure URLs into another language

### ISSUE THREAD

**Issue by GeoffTidey** [rubysherpas/forem#426]
Would like to have the ability to redefine the URLs so that they are specific to the language of the site.

e..g/  We have a Spanish site.

Rather than 

/forums/coche/topics/recomendados

we would like

/foro/coche/mensaje/recomendados

Is this possible already?  If not, what would be the best approach to update the code?

**Comment by radar** [comment]
Other than completely redefining the routes for forem, by doing something like this:

Forem::Engine.routes.draw do
  resources :foro, controller: "forums" ...
end

No, there isn't a way to do it right now. I wonder if we could at all use i18n to do this. It's a pretty commonly requested feature. I think i18n is loaded before routes, so it should be possible.

**Comment by GeoffTidey** [comment]
Thanks @radar.  I've been trying to get https://github.com/enriclluelles/route_translator to work with forem, but I've had to go with your initial suggestion for now.  Which is here: https://github.com/GeoffTidey/forem/commit/71f94e3ab6ef54c58adc58e00a1305c294b5f457

**Comment by radar** [comment]
Happy to accept a PR which does this in a neat fashion.
