### ISSUE TITLE
Deleted users and stranded posts/topics

### ISSUE THREAD

**Issue by avitus** [rubysherpas/forem#427]
Looking through the documentation I can't seem to find anything about how to handle deleted users. Currently, forem throws an exception when trying to display the link and avatar for a user that no longer exists.

How are other users handling this? Is it best practice to delete all associated posts/topics. It seems as though removing entire topics created by deleted users is unnecessary but the fact that the Forem engine seems to think that should be the default is making us wonder.

**Comment by parndt** [comment]
Interesting. Probably our users would have to be soft deleted through something like paranoia. What do you think, everyone else? @knewter @radar

**Comment by knewter** [comment]
I would suggest soft deletion

**Comment by radar** [comment]
Soft deletion also gets my vote.
