### ISSUE TITLE
Feature request: image uploads/attachments

### ISSUE THREAD

**Issue by createthis** [rubysherpas/forem#428]
This would be a super nice feature.

**Comment by parndt** [comment]
How would you like this to operate?

**Comment by createthis** [comment]
Hey Parndt. I mostly meant this as a place holder for discussion, so thanks for the interest. I hadn't put much thought into it, but I think it should operate like most other forum software.

Two types come to mind:
1.) When the forum has a rich text editor built in, there is often an "Add Image" icon. Some forums only allow adding links to other sites, but many allow upload from localhost via this dialog. The image is usually inline, but depending on the rich text editor it might be resizable and moveable. The example I'm thinking of is vBulletin based systems.

2.) Sometimes there is an "add attachment" button. It presents the ubiquitous "Browse" multi-part form upload button and often a text field for entering a description of the image. This type of system can be separate from a formal rich text editor. Often the "add attachment" button is at the bottom of the forum post text box, instead of the top. The image shows at the bottom of the post unless a fancy "inline photo" tag is added. An example of this would be phpBB systems.

Of the two, I think phpBB would be the easiest to implement, and vBulletin is the more intuitive. I personally prefer the rich text editor solution, but that adds dependencies. Either way, paperclip can handle the image resizing and processing on the backend.

What do you think?

**Comment by parndt** [comment]
I woud like the rich text editor solution which allows you to put a picture anywhere. This may be best achieved with an extension to Forem. I would like to avoid using paperclip in favour of something more dynamic like Dragonfly.

Thoughts?

**Comment by createthis** [comment]
Well, I'm an INTJ, so I have a certain way I go about doing things.

You'd have to sell me on Dragonfly before I'd stop reaching for Paperclip (my initial look didn't do a great job convincing me I needed it). Paperclip has always worked well for me in the past. I tend not to change something unless I have a reason to.

Also, I already have extensions for my extensions. I'm using spree as a shopping cart and forem as a forum for spree. I have seven other extensions installed. I'm starting to think the whole Engine idea is some kind of revolt against what makes Rails so beautiful in the first place, "convention over configuration". I think it's all getting a little out of hand. I'd much rather just see a rich text editor as the default and everyone who doesn't like it can go fork themselves. <--- see what I did there?

Anyway, I think our methods might differ, but we're basically on the same page as far as the end result. I think the guy writing the code will ultimately make the decisions. I haven't yet had a need for images in my forums, so in the foreseeable future it won't be me. Of course, that could change anytime.

**Comment by dongxf** [comment]
I would suggest to operate in the exact way same as commenting this issue on github.com: 

![fooway_icon_blue](https://f.cloud.github.com/assets/309921/990569/d407e21e-0935-11e3-9c2b-7ed1eae5b1cf.png)

I'm seriously considering adding an image attachment feature in my Forem.

**Comment by radar** [comment]
I wouldn't mind that, either. The issue is to get it to upload it somewhere and include the correct syntax for displaying the image. That last part could be solved by removing formatter support from Forem and only supporting Markdown.

**Comment by radar** [comment]
Happy to accept a PR which adds this feature.
