### ISSUE TITLE
Moderation Queue Notifications?

### ISSUE THREAD

**Issue by createthis** [rubysherpas/forem#429]
Hey,

Are Admins notified when a new message hits the moderation queue? I'm not seeing any emails coming from my new installation on this event.

Thanks,

Jesse

**Comment by radar** [comment]
There are currently no email notifications for this. I agree that it would be a good idea to email admins regarding these events.

**Comment by createthis** [comment]
Yeah, I've already had a few days slip by while I had messages in the queue unawares. I think this needs to happen. Seems like it would be a really easy feature to implement too. If you can point me to the most likely trigger point real quick, I can probably scratch my own itch and give you a pull request.

**Comment by parndt** [comment]
We'd welcome a pull request with open arms. The logic in `skip_pending_review` could probably be extended to handle the notification case too.

https://github.com/radar/forem/blob/master/app/models/forem/post.rb#L113-L115

**Comment by createthis** [comment]
Well, that was certainly a starting point, but after another hour of digging, I think what I was looking for was Forem::TopicsController#create using @topic.user.forem_moderate_posts? as a filter. I'll see what I can do.

**Comment by createthis** [comment]
One problem I'm seeing is the lack of a clear way to iterate moderators. There is a has_many :moderators in the Forem::Forum model that may be intended to fill this need, but I'm not sure it is working or complete. Instead, I decided to build a list of administrators.

**Comment by createthis** [comment]
Scratch that pull request. The post code is firing on update as well as create. I'll have to move it.

**Comment by createthis** [comment]
Alright. I apparently don't have a clue how these pull requests work. I added a commit to fix the code on my end, and it seems to have automatically updated the pull request. Fancy. We should be good to go now.
