### ISSUE TITLE
Route helpers in parent application layout raise NameError

### ISSUE THREAD

**Issue by jayroh** [rubysherpas/forem#435]
**Problem:** If you have a route helper in a parent app's layout it'll reference a method not available to the engine.

**Solution:** Pass along that method to `main_app` with method missing. This works well if I place it into `app/helpers/forem/application_helper.rb`:

``` ruby
def method_missing(method, *args, &block)
  main_app.send(method, *args, &block)
rescue NoMethodError
  super
end
```

In terms of the approach I just figured I'd throw this out as a possibility. I'm on the fence on how I would go about testing this for now but figured I would put it here for discussion in case you guys had any thoughts or opinions.

**Comment by jayroh** [comment]
Just noticed this: https://github.com/radar/forem/wiki/Installing---Upgrading#application-route-helpers

Curious as to whether you guys think this could be mitigated with the approach above.

**Comment by radar** [comment]
I'd rather people be explicit about where routes they're calling are defined.
