### ISSUE TITLE
`User#to_s` dependency not documented

### ISSUE THREAD

**Issue by jayroh** [rubysherpas/forem#436]
Realize I might be a little gun-shy to just go and update the wiki buuuuuut...

After setup there's one more thing that needs to happen on the parent application side. The user class needs to have a `.to_s` method implemented in order for the users to be displayed inside of forem.

The sample app I have didn't have that so all spots my user was being spit out looked like `Started by #<User:0x007faa7055f100>`

Did I miss something in the docs, maybe?

thanks guys.

**Comment by ascendbruce** [comment]
Hi! It is already in wiki > [Configuration](https://github.com/radar/forem/wiki/Configuration) > User class:

> The user class's instances should respond to 'to_s' for the user's name, and 'email' for use by Gravatar.

Maybe it's a good idea to highlight it? (I missed it too, on my first time setup)

**Comment by jayroh** [comment]
Ah-ha! I suspected as much!  Thank you @ascendbruce 

I feel like that's something a little more important to be tucked away in the wiki. For someone who knows ruby well enough it's not a big deal but for a relative novice it might not be as obvious.

**Comment by radar** [comment]
I agree that highlighting it is a good idea. I've added it to the installation instructions in the README now, and hopefully people won't miss it there.
