### ISSUE TITLE
Can not create new topic

### ISSUE THREAD

**Issue by frankel** [rubysherpas/forem#44]
When i want to create a new topic (e.g. http://localhost:3000/forem/forums/1/topics/new ), with user logged in, it redirects to the home page. The console displays this message: 

```
  Started GET "/forem/forums/1/topics/new" for 127.0.0.1 at 2011-09-11 17:34:00 +0800
  Creating scope :page. Overwriting existing method Forem::Topic.page.
  Processing by Forem::TopicsController#new as HTML
  Parameters: {"forum_id"=>"1"}
  Refinery::Page Load (0.3ms)  SELECT .......
```

I googled and found it is caused by kaminari, see this issue: https://github.com/amatsuda/kaminari/issues/57 While i use the kaminari's master branch in my rails project, the error still exists. I wonder if this belongs to kaminari's bug.

My gem file is the same as this one: https://github.com/radar/forem/issues/38#issuecomment-2025575

Thanks.

**Comment by radar** [comment]
I don't understand what's going wrong here. I've got it working for me on my application. Can you add some steps to reproduce this?

**Comment by frankel** [comment]
I set up a stand alone rails project with forem but without RefineryCMS, this bug disappears. But with the latest RefineryCMS gem, it occurs. Although I think it is totally a Kaminari bug which is fixed in Kaminari's master branch. But when I included Kaminari's master branch as gem, it still doesn't work. So I have no idea what to do next.

**Comment by parndt** [comment]
@frankel still happening?

**Comment by frankel** [comment]
@parndt Haven't tested yet, but i found a solution to fix the conflict between Kaminari and will_paginate, https://github.com/sferik/rails_admin/issues/816
