### ISSUE TITLE
refinerycms forem generate error

### ISSUE THREAD

**Issue by RamakrishnanK** [rubysherpas/forem#441]
rails generate refinery:forem

/home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/activesupport-3.2.13/lib/active_support/inflector/methods.rb:230:in `block in constantize': uninitialized constant Helpers::Forem::ApplicationHelper (NameError)
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/activesupport-3.2.13/lib/active_support/inflector/methods.rb:229:in`each'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/activesupport-3.2.13/lib/active_support/inflector/methods.rb:229:in `constantize'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/activesupport-3.2.13/lib/active_support/core_ext/string/inflections.rb:54:in`constantize'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/actionpack-3.2.13/lib/abstract_controller/helpers.rb:136:in `block in modules_for_helpers'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/actionpack-3.2.13/lib/abstract_controller/helpers.rb:131:in`map!'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/actionpack-3.2.13/lib/abstract_controller/helpers.rb:131:in `modules_for_helpers'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/actionpack-3.2.13/lib/action_controller/metal/helpers.rb:92:in`modules_for_helpers'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/actionpack-3.2.13/lib/abstract_controller/helpers.rb:95:in `helper'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/actionpack-3.2.13/lib/action_controller/railties/paths.rb:18:in`block (2 levels) in with'
    from /home/sysadmin/rails_projects/ram/samplerefinery/app/controllers/application_controller.rb:3:in `<top (required)>'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/bundler/gems/refinerycms-46a3f3bf85f7/pages/lib/refinery/pages/engine.rb:12:in`block in class:Engine'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/bundler/gems/refinerycms-46a3f3bf85f7/core/lib/refinery/core/engine.rb:25:in `call'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/bundler/gems/refinerycms-46a3f3bf85f7/core/lib/refinery/core/engine.rb:25:in`each'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/bundler/gems/refinerycms-46a3f3bf85f7/core/lib/refinery/core/engine.rb:25:in `refinery_inclusion!'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:429:in`_run__1195258207145520409__prepare__2085424989752758179__callbacks'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in`_run_prepare_callbacks'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:74:in`prepare!'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/railties-3.2.13/lib/rails/application/finisher.rb:47:in`block in module:Finisher'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `instance_exec'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/railties-3.2.13/lib/rails/initializable.rb:30:in`run'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/railties-3.2.13/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/railties-3.2.13/lib/rails/initializable.rb:54:in`each'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `run_initializers'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/railties-3.2.13/lib/rails/application.rb:136:in`initialize!'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/sysadmin/rails_projects/ram/samplerefinery/config/environment.rb:5:in`<top (required)>'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/railties-3.2.13/lib/rails/application.rb:103:in `require_environment!'
    from /home/sysadmin/.rvm/gems/ruby-1.9.3-p385@rails3tutorial2ndEd/gems/railties-3.2.13/lib/rails/commands.rb:25:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by radar** [comment]
Closing due to age.
