### ISSUE TITLE
Should users be able to reply without having read permissions on forum?

### ISSUE THREAD

**Issue by daniely** [rubysherpas/forem#445]
https://github.com/radar/forem/blob/master/app/models/forem/ability.rb#L44

How come there is no check to see if a user has read permissions on a forum before allowing them to reply to a topic? Is this not a use case to worry about?

For example, say a user at one point has access to a forum (and thus topics). Eventually they get banned for bad behavior. If they are clever enough I believe they'd be able to assemble an http POST request to reply to an existing topic, even though they are banned.

If this is something that needs to be fixed I'd be happy to write a test and submit a patch.

**Comment by parndt** [comment]
Could this be achieved by overriding this method in your user's class? https://github.com/radar/forem/blob/master/lib/forem/default_permissions.rb#L32-L36

``` ruby
def can_reply_to_forem_topic?(topic)
  can_read_forem_forum?(topic.forum) && true # or some condition in place of true
end
```

**Comment by daniely** [comment]
Yes. But what I was wondering is, should this be the default behavior in forem?

**Comment by parndt** [comment]
What alternative are you proposing?

**Comment by daniely** [comment]
https://github.com/radar/forem/blob/master/app/models/forem/ability.rb#L44

change from

``` ruby
user.can_reply_to_forem_topic?(topic)
```

to this

``` ruby
can?(:read, topic.forum) && user.can_reply_to_forem_topic?(topic)
```

then it would be similar to the permissions for creating topics

**Comment by parndt** [comment]
Can you send this as a pull request please?

**Comment by daniely** [comment]
yes of course, just wanted to first make sure it was something you guys wanted :)

i'll write and test and submit after work today.

**Comment by parndt** [comment]
@radar confirm?

**Comment by radar** [comment]
Yes. A user should only be able to reply to a topic if they have read permission on the forum. Please do submit a PR for that today.
