### ISSUE TITLE
There is no locale data for 'forem.admin.forums.index.no_category'

### ISSUE THREAD

**Issue by jugyo** [rubysherpas/forem#448]
It's needed at here: https://github.com/radar/forem/blob/master/app/views/forem/admin/forums/index.html.erb#L7

To reproduce:
- create a category
- create topic in the category
- delete the category
- go to /admin/forums
- "en forem.admin.forums.index.no_category" is shown

**Comment by radar** [comment]
@jugyo Thank you for pointing this out. Could you please submit a patch to fix this problem? That would be awesome.

**Comment by jugyo** [comment]
BTW, Is it OK that we can delete category which still have topic?

**Comment by radar** [comment]
Forums are the container that contain topics, not categories. Deleting categories should not delete topics.

**Comment by jugyo** [comment]
Sorry, I meant forum, not topic.

**Comment by radar** [comment]
Forums can be reassigned to categories, so no they won't be deleted when a category is deleted.

**Comment by jugyo** [comment]
That makes sense. Thanks.

**Comment by daniely** [comment]
close?

**Comment by jugyo** [comment]
LGTM, thanks!
