### ISSUE TITLE
Using User#to_s seems bad idea.

### ISSUE THREAD

**Issue by jugyo** [rubysherpas/forem#451]
Because the method `to_s` is used for many purpose. Why you use `name` in the views instead?

**Comment by radar** [comment]
Please be more specific when posting issues.

**Comment by parndt** [comment]
Instead of using 

``` erb
<%= @user %>
```

We should use 

``` erb
<%= @user.name %>
```

**Comment by jugyo** [comment]
Exactly, thanks.

**Comment by parndt** [comment]
The problem we're trying to solve is that we're using your user model and decorating it with particular methods but we don't know if you even have a `name` field on your user. So, we'd need to have a method particular to Forem that gets us something meaningful to display in place of a user. We decided on `to_s` but is there a better option that we could adopt instead?

**Comment by jugyo** [comment]
I think using `name` field directly is not bad as well as you expect user model has the `email` field.
Anyway it seems trivial so feel free to ignore this opinion.

**Comment by x3qt** [comment]
Upvote for keep using `to_s`

**Comment by mauriciopasquier** [comment]
What about using a forem specific method, like it is done in [`decorate_user_class!`](https://github.com/radar/forem/blob/master/lib/forem.rb#L26) with other methods?

```
def forem_name
  to_s
end

def forem_email
  email
end
```

In this way they can be overridden, and you keep backwards compatibility using `to_s` and `email` by default. Or maybe configured like `avatar_user_method`. I could tackle a PR with these changes if this approach is welcome and there isn't any problem I'm not seeing :P

**Comment by radar** [comment]
@mauriciopasquier That's one way to do it. I am in favour of using `forem_name` and `forem_email` when we want to reference a user's name or email address. Can you please submit a patch that switches Forem to do that?

**Comment by mauriciopasquier** [comment]
ok, working on it :)

**Comment by radar** [comment]
@mauriciopasquier Any updates?

**Comment by mauriciopasquier** [comment]
No, sorry, I really couldn't find the time! But I'll do it this week (promise) if no one else does

**Comment by radar** [comment]
No particular hurry. I was just going through the issues the other day and saw that this one was still open. I'll check back in 2 weeks unless you ping this thread before then.
