### ISSUE TITLE
Autocomplete [select2] feature not working.

### ISSUE THREAD

**Issue by Rishi91991** [rubysherpas/forem#454]
Hi,

Well while integrating forem in my app. I saw that forem.js.erb and base.css was not included by default [as per pipe-lining it should be] and so as it is  required by views in forem itself I am presuming that it should be included within gem. so is this missing in your scenario or the way I have coded is correct [procedure is below given].

I have included [I mean had required] above files in my app/assets/javascript/application.js and app/assets/sytlesheets/application.css so it is working fine now.

Problem was encountered when I tried to add a new moderator in a group and so select2 method was failing.

I am just a newbie in rails world so pardon me if you think it is not relevant or my concepts are still not clear.

Thank you.

**Comment by radar** [comment]
Hi @Rishi91991. Can you please put this application on GitHub so that I can investigate this problem?

Thank you.

**Comment by link-er** [comment]
Have the same problem with select2
I see in source files, that it's required in application.js of forem app, but I don't see that it's loaded when my app is running

**Comment by radar** [comment]
@link-er As I asked @Rishi91991 to do, can you please put an example application on GitHub so I can take a look at it? Thanks.

**Comment by link-er** [comment]
https://github.com/link-er/check_project
Here are you

**Comment by Rishi91991** [comment]
Hi All,

Sorry for the delay. Well I am released from that project so I don't have code-base access. I solved that problem by including all JS files and CSS files of `forem` gem in my app's app/assets.

Thanks.

**Comment by radar** [comment]
I think all the problem here is that you're not including Forem's assets in your `application.js` file:

``` js
//= require forem
```
