### ISSUE TITLE
Localeapp for forum gem?

### ISSUE THREAD

**Issue by pluff** [rubysherpas/forem#457]
Hi. Recently I updated to latest forem master and I'm wondering why there is new localeapp dependency. Is it really necessary to use specific 3rd party service in a forum gem? Don't you think stuff like that should be added on application level?
This not critical dependency provides additional threat to private content leak + dependency on specific service.

**Comment by parndt** [comment]
Honestly I tend to agree. Localeapp hasn't been that helpful and it isn't the smoothest integration.

**Comment by radar** [comment]
I agree. Moving to localeapp was ridiculous (I feel the same way about Spree doing it, too). We should remove this feature from Forem and just go back to managing the locale files ourselves.

**Comment by parndt** [comment]
Yes please. However, we did get some improved translations out of it so hopefully we can export those or whatever.

**Comment by bodrovis** [comment]
Seems like this is not an issue anymore
