### ISSUE TITLE
Path names (Feature Request?)

### ISSUE THREAD

**Issue by tomkrus** [rubysherpas/forem#458]
Any tricks how to make your own name for resources in routes app?

For example:

``` ruby
resources :categories, :as => "/kategorien", :only => [:index, :show]
```

**Comment by radar** [comment]
Other than forking Forem, I don't think there is a way to do this. This is pretty commonly requested. Maybe we could use I18n for this? Could you please investigate a patch to allow us to do this?

**Comment by parndt** [comment]
We did this in Refinery but with a setting but we only had one route `/refinery`.. I think i18n would be the best way for this stuff.

**Comment by tomkrus** [comment]
In this point I tried add some my name to the categories:

`resources :categories, :as => "/kategorien", :only => [:index, :show]`

Result:

`undefined method `category_path' for #<ActionDispatch::Routing::RoutesProxy:0x513c930>`

`<%= link_to forem_emojify(category.name), [forem, category] %>`

(rails4)

Any tips?

**Comment by radar** [comment]
Hi @tomkrus,

the `:as` option changes the name of the routing helper, i.e. `category_path` would be `kategorien_path` now. I think that's not what you want.

What you want instead is the `path` option:

``` ruby
resources :categories, :path => "/kategorien"
```
