### ISSUE TITLE
Theming issues

### ISSUE THREAD

**Issue by stanl3y** [rubysherpas/forem#460]
I have followed the guide here https://github.com/radar/forem/wiki/Theming, I am trying to apply the bootstrap theme - this is what I have so far (ruby 2.0 @ rails 4.0)

here's Gemfile

```
gem 'forem-bootstrap', :github => "radar/forem-bootstrap"
```

this is my lib/forem.rb

```
require 'forem'
module Forem
  module Theme
    module Base
      class Engine < Rails::Engine
        Forem.theme = :bootstrap
      end
     end
  end
end
```

and the application.css

```
*= require "forem/bootstrap/style"
```

application.html

```
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
```

and this is what I obtain 

```
Sprockets::FileNotFound in Forem::Forums#index

Showing /.../app/views/layouts/application.html.erb where line #5 raised:
couldn't find file 'forem/bootstrap/style'
```

**Comment by caseydierking** [comment]
I could be wrong in this, but have you tried not requiring *= require "forem/bootstrap/style", updating the forem gem, and then trying again?

If memory serves me right, I think thats all I had to end up doing. Forem should come with bootstrap theme already if I'm not mistaken.

**Comment by radar** [comment]
I think the guide might be incorrect. The correct line is this:

```
*= require "forem-bootstrap"
```
