### ISSUE TITLE
One user cannot see other users post

### ISSUE THREAD

**Issue by mohanraj23** [rubysherpas/forem#461]
I just up the forum I created two users one users posts are not visible to the others. How to approve the post ?
Also I can find the General Tab three times.

I am using devise authentication system in my app

**Comment by radar** [comment]
You will need to be signed in as an admin user or a moderator of the group and then approve these posts. Posts by users are by default hidden from other users. If you want this setting disabled, then you should change the `moderate_first_post` setting to `false`:

```
Forem.moderate_first_post = false
```
