### ISSUE TITLE
 Localeapp::MissingApiKey in Forem::ForumsController#index

### ISSUE THREAD

**Issue by marionzumbado** [rubysherpas/forem#476]
I follow the steps in this page https://github.com/radar/forem/wiki/Integration-with-Refinery-CMS but when i access to http://localhost:3000/forums have the next error:          Localeapp::MissingApiKey in Forem::ForumsController#index

somebody can help me please

**Comment by parndt** [comment]
@radar how can we get rid of LocaleApp?

**Comment by radar** [comment]
Removed localeapp from master and rails4 branches. @marionzumbado: Please run `bundle update forem` and try again. Sorry for the difficulties.
