### ISSUE TITLE
Problem approving pending posts

### ISSUE THREAD

**Issue by dlip** [rubysherpas/forem#479]
I'm using ruby 2.0 with Rails 4.0, and when I go the administration area to approve a post I get the following error:

```
Showing /home/vagrant/.bundler/ruby/2.0.0/forem-dba2e783d48e/app/views/forem/subscription_mailer/topic_reply.text.erb where line #3 raised:

Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
```

**Comment by radar** [comment]
Have you set up ActionMailer::Base settings yet?

**Comment by dlip** [comment]
Ah yes that was it. Even though I had this in the config:
`config.action_mailer.raise_delivery_errors = false`

I still needed this
`config.action_mailer.default_url_options = { :host => "example.com" }`

Thanks!
