### ISSUE TITLE
Followed instructions - Forem files not created

### ISSUE THREAD

**Issue by johnbpetersen** [rubysherpas/forem#48]
I am very new to Rails and coding in general, so this may be a stupid question. I followed the instructions to for the installation. I created the user, current_user, admin, all that good stuff.

The files were never created in my app directory. For example, my app/views only has layouts, sessions, and users -- no forem files.

What am I doing wrong? How do I fix this? Do I have to create all those pages and files manually?

Thanks for your help

**Comment by parndt** [comment]
That is correct, forem files are kept inside the forem gem.

**Comment by johnbpetersen** [comment]
Ok. So when go to local host and then go to /forem the only thing that appears is the Forums header and then the table headers forum, topics, posts, and views. How do I make it functional?

**Comment by parndt** [comment]
cc @Radar

**Comment by johnbpetersen** [comment]
Sorry if it is not making any sense. Here is the github for what I've tried to build today -- https://github.com/johnbpetersen/forum_sample

Only been at this for a few weeks now. Any help is greatly appreciated.

**Comment by radar** [comment]
John, I am not sure what you are trying to do. I've added the `forem:views` generator which you can run using `rails g forem:views` in your application (after you `bundle update forem`) and that will copy over forem's views into your application.

Is that what you want?

**Comment by johnbpetersen** [comment]
Ok. Thanks man. I just forked the forem.heroku.com and am going to work with that. That's what I was trying to do in the first place.
