### ISSUE TITLE
Rails4 Admin Forum Delete button showing weird stuff

### ISSUE THREAD

**Issue by amaximia** [rubysherpas/forem#483]
This is what I get inside the Delete button for a Forum:

``` html
"Delete Confirm" data-method="delete" href="/forums/admin/forums/default" rel="nofollow" scope="forem.admin.forums">Delete
```

When I click the button, I get: `<span class=`
and below the two buttons "Cancel" and "OK"

It is similar with deleting a category.  Inside the button:

``` html
Delete Confirm" data-method="delete" href="/forums/admin/categories/general" rel="no follow">Delete
```

When I click the button, again I get:

``` html
<span class=
```

**Comment by radar** [comment]
Hi @amaximia, thanks for pointing this out. I've fixed this up in some new commits to the rails4 branch this morning. Please run `bundle update forem` and try again.
