### ISSUE TITLE
Override forem's routes

### ISSUE THREAD

**Issue by borisdamato** [rubysherpas/forem#489]
Hello, how can I override forem's routes in order to avoid the /forums/forums problem?

Thank you

**Comment by radar** [comment]
Maybe we should look at making the default something like `/<mountpoint>/:forum_id/topics/:topic_id`? WDYT, @parndt and @knewter?

**Comment by borisdamato** [comment]
@radar Any update? Is there a way I can do this even if you decide not to make it the default route?

Thank you.

**Comment by parndt** [comment]
In your `config/routes.rb` file just put (before your main routes):

``` ruby
Forem::Engine.routes.draw do
  # your route here
end
```

**Comment by radar** [comment]
@parndt Do you think we should change the default routes to accommodate this?

**Comment by parndt** [comment]
I don't love it because if you mount it at the root then you're `site.com/1/topics/5`

**Comment by radar** [comment]
If you don't like then mount it at '/forums' or whatever instead. I think having Forem draw the routes at the root is the best of both worlds.

**Comment by parndt** [comment]
@radar OK then

**Comment by x3qt** [comment]
@radar :+1:

**Comment by borisdamato** [comment]
@parndt It says there are duplicated routes. Could you be more specific please?
Thank you :)

**Comment by parndt** [comment]
@Aselox what exactly does it say?

**Comment by borisdamato** [comment]
@parndt 

```
/Users/Aselox/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:409:in `add_route': Invalid route name, already in use: 'root'  (ArgumentError)
```

And it says this with every forem's route I try to change

**Comment by parndt** [comment]
Full stack trace, please

**Comment by borisdamato** [comment]
@parndt Here it is: http://pastebin.com/UVwzLy07

**Comment by borisdamato** [comment]
Any update?

**Comment by radar** [comment]
@Aselox If there were any updates, you can be sure that they would be posted here. Please keep in mind that we all have day jobs and lives outside of Forem and that we only work on Forem in our spare time. This means that sometimes we take a long time to get around to doing things.

We appreciate your patience from this moment forward.

**Comment by radar** [comment]
@Aselox This is now fixed in master and rails4. Thank you for your patience.

**Comment by x3qt** [comment]
:+1:
