### ISSUE TITLE
undefined local variable or method `new_user_session_path' (application.html.haml)

### ISSUE THREAD

**Issue by philiprhoades** [rubysherpas/forem#494]
People,

I am trying to use forem with:

https://github.com/mwlang/lazy_registration_demos
- which is working OK by itself but after going through the forem gem adding process, I get the above error when I try to go to:

http://localhost:3000/forums

From the dev log it seems that Rails is going through the forem stuff OK until it needs to check about user login status (I get a different error if I am already logged in: undefined local variable or method `edit_user_registration_path') but I don't know how to fix the problem . . guidance about how fix this would be much appreciated!

Regards,
Phil.

**Comment by radar** [comment]
Hi @philiprhoades,

You probably need to reference it like `main_app.edit_user_regsitration_path`. If the view/partial/template/whatever is being rendered within the context of the engine, then the engine isn't going to know about the application's routes (and vice versa). You need to be explicit about where that route can be found.
