### ISSUE TITLE
WYSIWYG editing

### ISSUE THREAD

**Issue by juozasg** [rubysherpas/forem#50]
Would it take a lot of work to include WYSIWYG posting in Forem? I'm thinking about using it with Refinery CMS, which has WYSIWYG tools and HTML formatted content - it would make a ton of sense to have it work the same with Forem too? Would it be a lot of work or just a matter of disabling markdown marshaling code so it works directly with HTML and adding some javascript or partials to include the editor controls?

**Comment by radar** [comment]
Hey, cool suggestion :)

I think the easiest way would be to create a patch that would move the textarea for Forem's posts out into its own partial. This partial then could be overriden in the application to provide whatever functionality you wished. As for the markdown processing, you could potentially do the same thing here: move the post text processing out into a partial which could then again be overriden in the application.

What do you think?

**Comment by juozasg** [comment]
That makes sense. I'll try and see if I can figure out how to patch Forem to do this. The forum looks very nice, but I need this feature.

**Comment by gabrielbaez** [comment]
You could modify one of the  views  and use something like ckeditor.

**Comment by radar** [comment]
I've discussed this further on #55. Please see my responses there also.

**Comment by LegendSzymon-P** [comment]
This one seems also nice: http://www.wymeditor.org/

For example Refinery, Rails CMS, is using this editor.

**Comment by parndt** [comment]
Well, Refinery uses a heavily customised version, but yes.

**Comment by browning** [comment]
I would like it if we had a wysiwyg editor by default instead of markdown.
Haven't tried it yet, but ckeditor looks good , there is also a gem that would set us up nicely with file uploads: https://github.com/galetahub/ckeditor

I realize that wysiwyg v markdown is somewhat of a religious topic haha, but is there support for wysiyg here?

We could possibly provide support for both via configuration, but it would be pretty messy I think.

**Comment by parndt** [comment]
I'm going to close this in favour of #55 because they're too similar :-)
