### ISSUE TITLE
Not being able to run tests

### ISSUE THREAD

**Issue by bodrovis** [rubysherpas/forem#500]
I tried to run tests when adding some functionality, but no luck. Running

``` ruby
bundle exec rake forem:dummy_app
bundle exec rspec spec
```

gives me these errors: http://pastebin.com/CCLpY993

I have ruby 1.9.3 on my machine.

**Comment by radar** [comment]
Can you please show me the `Gemfile` that you're using? According to the error message, you don't have the sqlite3 adapter installed. This is peculiar.

**Comment by bodrovis** [comment]
``` ruby
source "https://rubygems.org"

gem 'forem-theme-base', :git => "git://github.com/radar/forem-theme-base", :branch => "master"

gemspec

gem 'pry-rails'
gem 'pry-nav'

platforms :jruby do
  gem "activerecord-jdbc-adapter", :require => false
end

group :test do
  platforms :ruby do
    gem "forem-redcarpet", :github => "radar/forem-redcarpet", :branch => "master"
    gem "mysql2"
    gem "pg"
    gem "sqlite3"
  end

  platforms :jruby do
    gem "activerecord-jdbcmysql-adapter", :require => false
    gem "activerecord-jdbcpostgresql-adapter", :require => false
    gem "activerecord-jdbcsqlite3-adapter", :require => false
    gem "forem-kramdown", :github => "phlipper/forem-kramdown", :branch => "master"
  end
end

if RUBY_VERSION < '1.9.2'
  gem 'nokogiri', '~> 1.5.9'
end
```

Maybe I know what is causing this problem. It is because we have `platforms :ruby do` where `sqlite3` is present, but I am currently on Windows and so gems from this group are not being loaded.

**Comment by bodrovis** [comment]
I changed that line to `platforms :ruby, :mswin do`, but now when trying to run tests I keep getting 

```
git://github.com/radar/forem-redcarpet.git (at master) is not checked out. Please run bundle install
```

Running `bundle install` or `bundle install --no-deployment` does not help :(

Updated:

```
bundle pack
bundle install --path vendor/cache
```

didn't help either.

**Comment by radar** [comment]
I don't know how this could be happening :( I would need a way to reproduce this exactly on my computer if I was going to debug it.

**Comment by bodrovis** [comment]
@radar Wouldn't cloning the repo to your PC and modifying the line to `platforms :ruby, :mswin do` do the trick? I will try to research more today on this issue.

**Comment by bodrovis** [comment]
@radar I managed to fix it at last. Will submit a pull request.

**Comment by bodrovis** [comment]
PR: https://github.com/radar/forem/pull/507

**Comment by radar** [comment]
I don't think #507 fixes this. Please provide me with an exact way I can reproduce it. Does it only happen on Windows computers? I guess I could try running the stuff there.

**Comment by bodrovis** [comment]
@radar I will do that in the evening, but for now i will put the following link: http://bundler.io/v1.2/man/gemfile.5.html

Please scroll to the middle of the file, section PLATFORMS (:platforms):
- ruby - C Ruby (MRI) or Rubinius, but NOT Windows
- mingw - Windows 'mingw32' platform (aka RubyInstaller)

My PR (https://github.com/radar/forem/pull/507) fixes this issue for me on Windows and I managed to run tests. I do not know if this happens anywhere else, because currently i do not have any other platforms. `platforms :ruby, :mingw do` means that following gems will be installed on all 'ruby' platforms (Linux, Mac and friends) AND on Windows. Specifying only `platforms :ruby` means that these gems will NOT be installed on Windows and indeed any DB adapters will not be loaded. For example, in one my project i specify this:

``` ruby
gem 'therubyracer', :platform => :ruby
gem 'execjs'
```

because on the production server i should use `gem 'therubyracer'` (there is a Linux OS), but on my development machine with Windows this gem does not install as it is not supported by this OS, so instead i should specify `gem 'execjs'`.

**Comment by bodrovis** [comment]
@radar To reproduce it simply clone Forem from the master branch on Windows machine and run:

```
bundle exec rake forem:dummy_app
bundle exec rspec spec
```

After that you could try my fix in the Gemfile: `platforms :ruby, :mingw do`, run `bundle install` and those commands again.

**Comment by bodrovis** [comment]
I will close this issue as my PR was merged and tests are running fine now.
