### ISSUE TITLE
NilClass error: undefined method `new' for nil:NilClass

### ISSUE THREAD

**Issue by hfoxy** [rubysherpas/forem#510]
I've been setting up my Forem installation with devise, I first had the `forem_user` error, then I got some error with `forem_group_ids`. But when I went to report that error; this one came up instead.

Showing /var/www/athena/app/views/forem/categories/_category.html.erb where line #1 raised:

`undefined method `new' for nil:NilClass`

I have tried this with Rails server and normal Apache, both throw the error.

**Comment by radar** [comment]
Can you please show us the full stacktrace for this issue?

**Comment by hfoxy** [comment]
@radar: Here you go http://pastebin.com/rsXnEM1W

**Comment by hfoxy** [comment]
Oh and I forgot to mention, I am running this on Rails 4 from the rails4 branch

**Comment by radar** [comment]
Your stacktrace is [pointing directly here](https://github.com/radar/forem/blob/19a0c50428bb2221a743067b5f2ed51a9ff17762/app/models/forem/ability.rb#L23)

I would guess by your error that you do not have `Forem.user_class` set in `config/initializers/forem.rb`. Please set it.
