### ISSUE TITLE
forem-gfm_formatter and sanitization

### ISSUE THREAD

**Issue by bodrovis** [rubysherpas/forem#511]
As per this discussion: https://github.com/radar/forem/issues/359#issuecomment-28974346

One of the formatter that are used in Forem is `forem-gfm_formatter`. However it uses `ERB::Util.h()` to sanitize input which currently breaks quoting. A pull request was sent to the author (https://github.com/Miniand/forem-gfm_formatter/pull/1) but no response after 18 days. 

So either we should clone author's repo, make some modifications there and suggest users to specify this forked version in Gemfile or just not use this formatter.

I also have to notice that this fix https://github.com/radar/forem-gfm_formatter/commit/81e0390336d50c07eceb653a271950ce10a62923 introduces `Forem::Sanitizer.sanitize` instead of `ERB::Util.h()`, but should it be used here as we already have sanitization in Forem's method: https://github.com/radar/forem/blob/9633409b8557b35fa37d101125b6c0cfb0193978/app/helpers/forem/formatting_helper.rb#L6 It seems like double sanitization.

**Comment by radar** [comment]
@bodrovis I don't understand what problem is happening here. Please explain this better :\

**Comment by bodrovis** [comment]
Sorry @radar I was in a hurry when writing it and it was a bad idea... On the second thought this issue is not related to Forem directly, but to gfm itself, so I will rather open an issue in your fork rather then here. Closing this one.

**Comment by bodrovis** [comment]
But I will not be able to open an issue in your fork basically because it is a fork and there is no such option. :(

Okay. So basically I wanted to say that we should probably instruct users to reference your forked version of `forem-gfm_formatter` (https://github.com/radar/forem-gfm_formatter) rather than this https://github.com/Miniand/forem-gfm_formatter because this PR https://github.com/Miniand/forem-gfm_formatter/pull/1 still wasn't merged.

However I don't understand why sanitization is used inside formatter (https://github.com/radar/forem-gfm_formatter/commit/81e0390336d50c07eceb653a271950ce10a62923#diff-3274363927d6044e057e125e9d1595e0R10) if it is already being used inside Forem engine (https://github.com/radar/forem/blob/9633409b8557b35fa37d101125b6c0cfb0193978/app/helpers/forem/formatting_helper.rb#L6)? Should it be used twice? For example, inside `forem-textfile_formatter` there is no sanitization: https://github.com/radar/forem-textile_formatter/blob/master/lib/forem/formatters/redcloth.rb#L7

**Comment by radar** [comment]
@bodrovis No, the sanitization should not be happening twice. Could you please submit a patch to forem-gfm_formatter for that, and a patch to wherever it is that we're recommending to use @Miniand's gfm_formatter, since clearly that is no longer being maintained.

Thank you.

**Comment by bodrovis** [comment]
https://github.com/radar/forem-gfm_formatter/pull/1 Done!
