### ISSUE TITLE
Quoting and sanitization

### ISSUE THREAD

**Issue by bodrovis** [rubysherpas/forem#512]
As per this discussion: https://github.com/radar/forem/issues/359#issuecomment-28974346

There is a serious problem with quoting that breaks because of sanitization. Inside `as_formatted_html`: https://github.com/radar/forem/blob/9633409b8557b35fa37d101125b6c0cfb0193978/app/helpers/forem/formatting_helper.rb#L6 there is a line `Forem.formatter.format(as_sanitized_text(text))`. This makes the text to appear as raw rather than formatted like this (with `kramdown` formatter; other formatters behave similarly): 
![4e2ccff6-511f-11e3-8c26-c416cb0bd01b](https://f.cloud.github.com/assets/646942/1700383/4e7489d2-600f-11e3-9787-b350ac02a214.png)

After re-writing this method:

``` ruby
def as_formatted_html(text)
      if Forem.formatter
        as_sanitized_text(Forem.formatter.format(text)).html_safe
      else
        Forem::Sanitizer.sanitize(text).html_safe
      end
end
```

Quoting works as expected. Can this fix be applied or should it be done in some other way?

**Comment by radar** [comment]
@bodrovis Please provide steps to reproduce this issue.

**Comment by bodrovis** [comment]
@radar Sure thing. I have created a repo with a new app that uses the latest version of Forem: https://github.com/bodrovis/forem_quoting You can clone it, run all migrations and stuff, then create a new topic and try to quote uncommenting lines here one by one: https://github.com/bodrovis/forem_quoting/blob/master/Gemfile#L13

Observe the results. I was NOT able to make quoting work with `forem-kramdown`:
![kramdown](https://f.cloud.github.com/assets/646942/1732070/be79ef56-6316-11e3-8d51-c63b9c71d9b5.png)

and `forem-rdiscount`:
![rdiscount](https://f.cloud.github.com/assets/646942/1732073/c82bfda0-6316-11e3-8ee1-9c10f2c307a5.png)

Other formatters work nice (I did not try to use `gfm` formatter because there is unmerged pull request).

So this seems like sanitization being applied and `>` displayed as raw symbol and not being formatted as blockquote.

**Comment by bodrovis** [comment]
I have also tried to implement the workaround described earlier and it does work for all formatters present in my Gemfile.

**Comment by bodrovis** [comment]
By the way shouldn't we stick with one formatter? And stop using `forem-redcarpet` as it requires Python (as it is described here https://github.com/radar/forem/wiki/1.0-Roadmap)?

**Comment by radar** [comment]
`forem-redcarpet` is the least worse formatter out there. I would rather we did not stop using it.

**Comment by bodrovis** [comment]
@radar But it relies on `pygments.rb` which requires Python to be installed and as far as I remember we had a small discussion that this is no good. And as I see the mention about this fact is gone from the roadmap. So you do not think that switching to a JavaScript-based code highlighter is a good idea?

**Comment by bodrovis** [comment]
@radar Btw what about https://github.com/rubychan/coderay ? What do you think about that https://github.com/radar/forem-redcarpet/pull/6 ?
