### ISSUE TITLE
Dual Language Posting

### ISSUE THREAD

**Issue by bobbdelsol** [rubysherpas/forem#516]
I'm setting of a forum for a bi-lingual community.

It would be nice to be able to have an automatic area in the post for the translation and the ability of the user to enter in their language in the correct area.

  It would be real nice to automatically create a translation for a post.  Something like use Google-translate to fill in the other language.  Then the bi-lingual moderator would just have to fix egregious errors  instead of translating the whole post.

**Comment by radar** [comment]
Hi @bobbdelsol,

That sounds like a cool idea. Forem does not support that by default, and so you would need to probably fork this gem and add it in yourself.
