### ISSUE TITLE
Edit just one config in the locale (en.yml file)

### ISSUE THREAD

**Issue by pickhardt** [rubysherpas/forem#520]
Is it possible to override just one value in the en.yml file in a simple way? I want to change "edit: Editing post" to "edit: Edit" (it takes less space and matches the one word values of Reply, Quote, Delete)

Is there a way to change this from my initializer forem.rb?

**Comment by radar** [comment]
@pickhardt If you override the translation within your application's translations files, I believe it would use that:

``` yml
en:
  forem:
    post:
      edit: "Edit"
```
