### ISSUE TITLE
Things look bad/incorrect in Bootstrap 3

### ISSUE THREAD

**Issue by yanismydj** [rubysherpas/forem#527]
If you are using bootstrap 3, a lot of the styling is off(they changed a lot of the class naming in bootstrap 3).

Here's a screenshot of what it looks like for me:
![screen shot 2014-02-02 at 12 08 56 pm](https://f.cloud.github.com/assets/575015/2061186/f236a192-8c45-11e3-88f5-03760d3019cf.png)

I did my best to make things look better and fix the bugs I could find, and put it in a branch in my fork.  Here is the commit with the changes:
https://github.com/yanismydj/forem/commit/cc6bb16177030a27255f0bce70f8418dd522c4c5

Here's an after screenshot, using the styling in the commit above:
![screen shot 2014-02-02 at 12 11 12 pm](https://f.cloud.github.com/assets/575015/2061192/3f2e5fd0-8c46-11e3-8ee6-68eafc2d5f55.png)

I thought about submitting a pull request, but I realized you'd probably want it on a new branch.  Also, it'll need some further love before it's really ready/polished, but I figure my commit is a good start.

Regards!
Forem :+1:

**Comment by mauriciopasquier** [comment]
About this and other view related issues: I've been using forem for a while now, and I think it would be better if the Forem gem didn't depend or include any views by default. I know it sounds extreme, but.. it causes a lot of complications like
- kaminari vs will_paginate
- unused dependencies (I rewrote the views in my site's style without using `simple_form`, for example)
- bootstrap 2 vs bootstrap 3 :P 

Forem could focus on making the forum infrastructure even better, and the view gems could be developed independently. I know there are independent view gems, but I think this view coupling slows forem development a little (I want a `gem 'forem', '1.0.0'` in my Gemfile :) )

Sorry if it seems too off-topic, or if it's something already discarded for reasons I don't know!

**Comment by yanismydj** [comment]
@mauriciopasquier sure, but I think for the time being, the bootstrap 3 issue needs some lovin

**Comment by radar** [comment]
@mauriciopasquier I think having a default set of views is worthwhile. Overriding of those views can be done within the application, and so it's no particular big deal.

I don't have the time at the moment to go through all of Forem and correct the Bootstrap stylings. Does anyone else want to take this on?

**Comment by yanismydj** [comment]
@radar hey dude, don't know if you saw it in my original message, but I actually got a head start on this.  It still needs more work but it's at least usable.  I may spend more time on polishing it when I've got more free time.  If someone else wants to pick up where I left off, that would be sweet too!

yanismydj@cc6bb16

**Comment by radar** [comment]
Ah, my bad. It is super early in the morning and I have not remembered that I should read everything within a thread before posting :)

Thanks for beginning the work @yanismydj. Could you open a PR for this anyway? We can have a branch for these changes based off the PR and then I can make some commits to that branch. Anyone else who wants to submit fixes for it would then be able to submit PRs for that new branch.

Make sense?

**Comment by yanismydj** [comment]
No worries amigo!

I'll send a PR when I'm back at my computer ☺

**Comment by radar** [comment]
@yanismydj I've got some fixes up on rails4 and master now. Can you please check these and let me know if they look OK?

A screenshot of any other problems would be great, thanks :)

**Comment by yanismydj** [comment]
@radar looking good my man, I'm closing this out for now.  Sorry about the hacky fixes earlier, I was just throwing stuff together quickly to try and get past some of the bigger issues I was having.

**Comment by radar** [comment]
No worries :)
