### ISSUE TITLE
Forem::Forum default_scope is prone to ambiguous column errors

### ISSUE THREAD

**Issue by Domenoth** [rubysherpas/forem#529]
`default_scope { order('name ASC') }`

Might be better as:

`default_scope { order("#{table_name}.name ASC") }`

**Comment by radar** [comment]
Hi @Domenoth. Does `order(:name)` do this correctly? Can you please submit a patch for this?

**Comment by Domenoth** [comment]
`order(:name)` seems to work fine (I've confirmed it in Rails 4).

pull request: https://github.com/radar/forem/pull/532
