### ISSUE TITLE
Authorization system

### ISSUE THREAD

**Issue by radar** [rubysherpas/forem#53]
Last week, I spoke with somebody was interested to know if Forem had any kind of authorization system. I told him it didn't, because I didn't know how to build one for it as applications can have their own authorization system.

So I spent some time thinking about this on the plane ride back from Chicago. Here are my thoughts in no particular order. It would be great if I could get some feedback on this issue:
### Permission system for forem

In many other forum systems out there, there are permission systems built into them. Forem is unique in that it's an engine and supposed to be pluggable into other applications, rather than being something standalone such as (my understanding) how phpBB and vBulletin work.

Of course, Forem can be "standalone" by just mounting it inside an empty Rails application. I don't think there will ever be  a case where we have a true standalone version.

Anyway...

This complicates things. By creating our own permission system we would limit those people who may have their own permissions systems within their applications. This is definitely not ideal. Forem is already able to adapt to different _authentication_ systems, so why not _authorization_ also?

I propose that we build a flexible authorization system into Forem so that people can set up permissions on their forem installs in the easiest way possible using their own authorization if that's what they have, or suggesting to use CanCan instead.
#### How it works

I think that we should have methods on the `User` class which define the permissions that people have. For example, there would be a `can_read_forum?` method which would take one argument and do something like this:

```
def can_read_forum?(forum)
  permissions.where(:object => forum, :permission_type => "read")
end
```

The code inside the `can_read_forum?` method will be application-specific, but the API for the permissions is something that we should provide.

There could even be a possibility that we provide a `Forem::Permissions::Default` module which, when included into a `User`-like class, would then provide defaults for these permission methods, which then can be overridden in the model as the application designers wish. I think it would be best to have a blacklist-by-default, but I am open to ideas on this one on why it's a bad idea if anybody thinks so.
#### Alternative API

Alternatively we get them to include a module called `Forem::Permissions` which then provides the following API:

   can_read_forum do
     permissions.where(:object => forum, :permission_type => "read")
   end

This then will store the given block which will be executed (using `instance_eval`) on the `current_user` object.
#### Caveats

With this kind of permission system I cannot think of a clean way that you could allow anonymous access to forums (for example). How could we fix that?

Thanks lads!

**Comment by nruth** [comment]
Sounds cool.

I think it'd be convenient to have blacklist and whitelist defaults available for default permissions.

For anonymous access, what about a non-persisted object to represent anonymous visitors? 
It could have permissions set in the class def.

**Comment by tanraya** [comment]
I develop an engine that similar to forem and I need authorization system too. I think we need a special gem that can give us convenient way to organize authorization in mountable engines.

**Comment by radar** [comment]
I was talking with someone today about this and realised that we could probably pull it off with just CanCan now. i.e. do what Rails does and choose one default authorization system _for us_ and make people conform to it. If other people want to use other permissions systems they can, they'll just need to submit a pull request implementing it before hand.

The permissions system is very simple. You can see the beginnings of it here: https://github.com/radar/forem/commit/8ebefd09c334b9593c40404883727c4a139ac47c.

What happens is that we will provide a `DefaultPermissions` module which needs to be included into the `User` class. You can then override the methods of this module in your class as you see fit. So far the only method that is implemented is `can_read_forums?` which defaults to `true`.

By overriding the method, you would then put in _your own code_ that would tell the application what criteria is necessary to perform that action. The calculation for permission is entirely up to the application itself, as different applications are going to have different criteria.

The whole point of this idea is to make it flexible enough that Forem has a basic permissions system so that you can do things like hide _some_ forums from certain people and show them to others. You know the drill. Permissions systems in forums is nothing revolutionary.

Is this a worthwhile way of doing it? Does anyone foresee any problems with this? I think it's clean enough that we could pull it off.

**Comment by radar** [comment]
I've done more work on the `permissions` branch today. I've written up all that a user needs to know about the Authorization System here: https://github.com/radar/forem/wiki/Authorization-System

I think other permissions we need to have are very few:
- Viewing categories
- Creating topics
- Creating posts
- Editing own posts

Can anyone think of any others?

**Comment by gabrielbaez** [comment]
What about allowing users to edit their own post and admin to edit user post  and a moderator option to allow them to edit post and move them to a different  forum.

**Comment by radar** [comment]
Editing their own post would be another one. I'll add that to the list.

A moderator option would require some way of flagging certain users as moderators in the system. This is not something Forem currently supports.

Moving topics is something only an admin can do right now. If there are moderators I think that they too should be able to move topics to different forums, but _only_ if they are a moderator of both forums. Just food for thought.

**Comment by radar** [comment]
I've merged this branch to master now, the permissions are live. 

If you have any problems with them please open a new issue.
