### ISSUE TITLE
I have done something wrong (I guess)

### ISSUE THREAD

**Issue by rJoshy** [rubysherpas/forem#531]
Hello,
I am not sure what I may have done wrong, but when i go to localhost:3000/forums it shows up but this is what shows up:

http://prntscr.com/2r8ggr

Are you able to tell me what I have done wrong, if you need me to present any documents just ask

**Comment by bodrovis** [comment]
I do not see any errors on this screenshot. Everything shows up nice, you just have to apply styling and maybe tweak the views.

**Comment by radar** [comment]
This is due to changes in Bootstrap 3. Please see #527.
