### ISSUE TITLE
Forem, Rails 4 -> Cancan or Pundit?

### ISSUE THREAD

**Issue by yas375** [rubysherpas/forem#533]
Recently I've started rewriting my old project from a scratch on Rails 4. Luckily it's open sourced so I can provide the link to it and you could see everything I have: https://github.com/BSUIR-Helper/helper-web/pull/7

In my project I don't use CanCan. I use pundit instead. The reason of such choice was that http://www.ready4rails4.net/ reports that CanCan is not ready for rails 4 without some workarounds. And also I like the api of pundit more.

So the first issue I've noticed and would like to report is that looks like there is no dependency on cancan specified in `forem.gemspec`. As a result after the installation of forem I was getting errors on loading cancan. I've fixed the issue by specifying cancan dependency in my Gemfile:

``` ruby
gem 'cancan', git: 'https://github.com/nukturnal/cancan.git'
```

I used the same fork as [specified](https://github.com/radar/forem/blob/c48dd3bba33329f04ac93b663bfe74a997cc4ed9/Gemfile#L9) in forem's Gemfile. Should this dependency be placed in gem spec file instead?

---

Another question I'd like to ask: how safe it is to use Forem + Cancan with Rails 4? (I didn't go deeper on investigation what problems cancan has with the rails 4). Do you recommend to do that?

Would be nice to be able to use Pundit and to remove the dependency on cancan... Do you have such plans?

Thanks for the awesome forum engine!

**Comment by radar** [comment]
My bad, I tagged the wrong issue in a commit.

**Comment by radar** [comment]
@yas375 I am extremely disappointed that nobody has been left in charge of the cancan project. It seems that pundit is winning favour in the community and therefore we should switch to that.

Can you please cook up a PR that accomplishes this?

**Comment by yas375** [comment]
@radar would be happy to :)

**Comment by yas375** [comment]
@radar I've just started working on this (don't have a lot progress yet), but have noticed ryanb/cancan#994 issue opened less than a day ago. Looks like `cancancan` comes for the rescue. At least that issues says it. So before I went deeply in switching Forem from cancan to pundit, I'd like to confirm if we still prefer this direction. 

Personally my opinion - let's switch to pundit. I like its api more.

**Comment by radar** [comment]
Pundit has the backing of @jnicklas (and elabs), and I like what they've done with Capybara. Please do work on switching to Pundit.

**Comment by yas375** [comment]
@radar ok :)

**Comment by radar** [comment]
@yas375 How goes the work on Pundit?

**Comment by yas375** [comment]
@radar I'm sorry. Don't have a lot of progress (I need this for my project which is not my primary job). Last time I've tried to work on this again tests were failing again in different places so I've started looking into those issues, but didn't spent a lot of time on this.

If you don't mind about the time I would be glad to keep this assigned on me and _hope_ to get to this on next weekend. Thanks and sorry for the delay.

**Comment by radar** [comment]
@yas375 That's ok, I was just checking. If you can do it this weekend then that would be fantastic.

**Comment by michielboekhoff** [comment]
Any news on this issue? I would love to see Forem use Pundit instead of Cancan, too.

**Comment by radar** [comment]
If there was news it would probably be posted here.

 If you would like Forem to use Pundit instead of CanCan then I would be happy to review a PR from you.

Thanks!

**Comment by radar** [comment]
Closing due to age. I like pundit better than cancan, but since Forem is using CanCanCan with no obvious detriment, it's going to stay that way until someone does something about it.
