### ISSUE TITLE
forem routes

### ISSUE THREAD

**Issue by bobbdelsol** [rubysherpas/forem#534]
It would be nice if you included this in the setup instructions

http://stackoverflow.com/questions/18366091/rails-forem-engine-routes-not-working

I have not used Forem but I had this same issue with Monologue. I think it will help if the links in your header specify that they are part of the main_app. Example:

Original link to root path might have been:

root_path
and now should be:

main_app.root_path
The reason for this is that the Forem Rails engine is a separate Rails application and the links without the prefix only work within the current Rails app (the main app, in this case).

**Comment by bodrovis** [comment]
Not sure that this should be specified in Readme because this info is provided in the guides http://guides.rubyonrails.org/engines.html

**Comment by radar** [comment]
I am not sure why we should include in the README what should be common knowledge when working with engines? Especially when it's mentioned in the [engines guide](https://guides.rubyonrails.org/engines.html) that @bodrovis already linked to.
