### ISSUE TITLE
issue with mounting forem in a nested block 

### ISSUE THREAD

**Issue by hardywu** [rubysherpas/forem#539]
I found that forem cannot be associated with other models due to the routing disaster. A simple case

``` ruby
resources :cities do 
  mount Forem::Engine => '/forums'
end
```

An error returns 

```
# From Better Errors
>> forem.forums_path
!! #<NoMethodError: undefined method `segment_keys' for nil:NilClass>
```

And
There is a commit from rails/rails dealing with this problem.
https://github.com/rails/rails/pull/12699

Any idea how to work around this problem?

**Comment by radar** [comment]
@hardywu If it's fixed within Rails, wouldn't the logical "work around" for this problem be to use a more modern version of Rails which contains the fix?

**Comment by hardywu** [comment]
@radar that means one has to fork a new clone and reconfig the `Gemfile` and `.gemspec` to support new version of Rails, which seems not a safe way to go. All `forem` variable in the view files would have to be changed to `city_forem`.

**Comment by radar** [comment]
@hardywu There's no magical silver bullet that would fix this problem without you having to put in some hard work. Forking is your only option.
