### ISSUE TITLE
rails 4 app getting: WARNING: Can't mass-assign protected attributes

### ISSUE THREAD

**Issue by nrankin** [rubysherpas/forem#541]
Hi
I'm a newbie to RoR working on a rails 4 app that has protected_attributes installed. I've installed forem from the rails4 branch and have tried to create a category through the UI. I'm getting:
'''
Started POST "/forums/admin/categories" for ::1 at 2014-03-07 08:38:13 +1300
Processing by Forem::Admin::CategoriesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"Fd40UlTen1UHtcxe1Q/lbHoil+KhpP9AUfecOod30Go=", "category"=>{"name"=>"Fine Tuning"}, "commit"=>"Create Category"}
  [1m[35mUser Load (0.2ms)[0m  SELECT "users".\* FROM "users" WHERE "users"."remember_token" = 'uvUbekuI5eTSn3C__z832A' LIMIT 1
  [1m[36mCACHE (0.0ms)[0m  [1mSELECT "users".\* FROM "users" WHERE "users"."remember_token" = 'uvUbekuI5eTSn3C__z832A' LIMIT 1[0m
WARNING: Can't mass-assign protected attributes for Forem::Category: name
'''
I understand that strong_parameters are the way to go in Rails 4, wondering if this error is because forem uses that and we are using protected_attributes, or if there is another issue. We will migrate to strong_parameters if need be.
Thanks for any pointers you can give :)

**Comment by radar** [comment]
Yes, it is because you're using `protected_attributes`. Please remove this gem.
