### ISSUE TITLE
Feature Request: Support HTML in posts

### ISSUE THREAD

**Issue by yanismydj** [rubysherpas/forem#542]
A lot of forum engines allow at least some basic html tags in posts.  I'm in the process of moving a bunch of data from a drupal advanced forum install over to forem, and I'd prefer to preserve the HTML in posts as opposed to converting everything to Markdown.

**Comment by radar** [comment]
Hi @yanismydj, I believe you can support this by telling Forem to use your own custom formatter within `config/initializers/forem.rb`:

``` ruby
Forem.formatter = YourCustomFormatter
```

This class will need to implement the [methods used within Forem::FormattingHelper](https://github.com/radar/forem/blob/rails4/app/helpers/forem/formatting_helper.rb).
