### ISSUE TITLE
Installer not found on Rails 4.1rc1?

### ISSUE THREAD

**Issue by mbhnyc** [rubysherpas/forem#547]
Not sure what's going on here, but when I try to install Forem on a new rails app I'm gettng:

`Could not find generator forem:install`

Anyone else seeing this?  Sure I can run the template steps manually, but that's a bit of a pain. :)

Also on ruby 2.1.1 if relevant!

**Comment by radar** [comment]
@mbhnyc We've not tested Forem against Rails 4.1 yet. Here Be Dragons.

**Comment by mbhnyc** [comment]
Heh indeed, to be complete I tried this on 4.0.3 as well, and the same "generator not found" issue is occurring. Could this be something with my local environment?  Seems very odd.

**Comment by radar** [comment]
@mbhnyc https://github.com/radar/forem/blob/rails4/CONTRIBUTING.md please :)

**Comment by mbhnyc** [comment]
Eeeyup didn't follow instructions.  Didn't know the github reference in the Gemfile was actually required.  Are you waiting for a final release to update the version on rubygems.org?

**Comment by radar** [comment]
Not really waiting on anything to do a proper gem release. It's just easier having people use the latest from GitHub. For now, anyway.

For posterity's sake we should probably just update that gem.

**Comment by mbhnyc** [comment]
Yeah, at least so far as the instructions work out of the box, maybe just tag a recent milestone commit as 0.9?
