### ISSUE TITLE
Changing to application layout causes routing error

### ISSUE THREAD

**Issue by steve-abrams** [rubysherpas/forem#548]
I installed forem and it seems to be working correctly.  I have a navbar, header, and footer in /app/views/layouts/application.html.erb that I'd like to use as the layout for all of the forem views as well.  I went into /config/initializers/forem.rb and uncommented the following, changing "forem" to "application":

`Rails.application.config.to_prepare do
    Forem::ForumsController.layout "application"
  end`

When I restart my application, and navigate to .../forums, the following error comes up:

`Routing Error
No route matches {:controller=>"forem/home", :class=>"active"}`

The forum was working before I changed the initializer file, and if I change it back, it works fine again.  How can I correctly use my pre-existing layout?  I'm using rails 3.2.13, and the rails3 branch of forem.

**Comment by bodrovis** [comment]
Full stack trace for this error would be helpful.

**Comment by bodrovis** [comment]
At this point it is hard to say what causes this problem, but just in case wanted to remind that all your routes inside the app should be written like this:

``` ruby
link_to main_app.posts_url
```

provided that in your `routes.rb` you have 

``` ruby
resources :posts
```

and Forem's routes should be specified like

```
link_to forem.root_path
```

**Comment by steve-abrams** [comment]
Something else I've noticed is that my administrator link still works and I can access the Forem admin menu, but I can't access the actual forums.

**Comment by steve-abrams** [comment]
This is the error listed in the log file:

``` ruby
ActionController::RoutingError (No route matches {:controller=>"forem/home", :class=>"active"}):
  app/views/layouts/application.html.erb:23:in `_app_views_layouts_application_html_erb___66823223_31344312'


  Rendered c:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/templates/rescues/routing_error.erb within rescues/layou
t (1.0ms)
```

It mentions line 23 in my application layout, which is:

``` ruby
<li><%= link_to 'Home', controller: 'home', action: 'index', class: 'active' %></li>
```

It's just the home link on my navbar.

**Comment by bodrovis** [comment]
@sabrams86 Take a look at my previous post, I think that was the cause. Try to add this route (or something link this):

``` ruby
get '/home', to: 'home#index', as: 'home'
```

and modify this Home link as follows:

``` ruby
<li><%= link_to 'Home', main_app.home_path, class: 'active' %></li>
```

**Comment by steve-abrams** [comment]
That seems to have solved that problem, but all of my menu links are set up that way, so it just throws the same error on the next link, I'm fairly new to rails, and this is the first gem I'm trying to integrate into my app.  Is the way I have all of my links set up considered incorrect form then?

**Comment by bodrovis** [comment]
@sabrams86 Yes, it is so as soon as those links will be rendered at Forem's pages. You can read more about that here: http://guides.rubyonrails.org/engines.html#routes As far as Forem is an engine, it has its own routes, so we have to tell Rails which routes to use: Forem's or main_app's.

**Comment by steve-abrams** [comment]
Fantastic, that did the trick.  One more problem now.  My layout is present for the main forums page, as well as when I enter a forum.  However, when I click on a topic, or go to make a new topic, it reverts to the default away from my layout.

**Comment by steve-abrams** [comment]
Never mind, I changed the forem.rb file to just have the single line:

```
Forem.layout = 'application'
```

I'm not sure what the difference is between this and what I have listed above but it worked.

**Comment by bodrovis** [comment]
That is strange. What did contents did you have there prior to that?

**Comment by radar** [comment]
@sabrams86 This all depends on the context which is rendering the request. If Forem is rendering the request but the routes are for the main application, then the routes referenced in the controllers & views of that request will need to be written like `main_app.home_path`. If it's being rendered within the context of your application but the routes point to forem, then they'll need to be `forem.root_path` and the like.

For more information, please read the [Engines guide](https://guides.rubyonrails.org/engines.html).
