### ISSUE TITLE
I deployed my updated site with forem and it's not loading correctly

### ISSUE THREAD

**Issue by steve-abrams** [rubysherpas/forem#549]
I installed forem and got it working on my local development computer.  I pushed it to github, then pulled it down to my server.  I ran bundle install to update the gem file (I had to upgrade from rails 3.2.1 to 3.2.13 in order to get forem to work on my dev computer).  But now it's coming up with the error:

``` ruby
forem at /home/steve/.rvm/gems/ruby-2.1.0/bundler/gems/forem-c14ec9588b57 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  duplicate dependency on rails (!= 3.2.0, != 3.2.1, != 3.2.10, != 3.2.2, != 3.2.3, != 3.2.4, != 3.2.5, != 3.2.6, != 3.2.7, != 3.2.8, != 3.2.9, < 3.3, >= 3.1.10), (~> 3.1) use:
    add_runtime_dependency 'rails', '!= 3.2.0, != 3.2.1, != 3.2.10, != 3.2.2, != 3.2.3, != 3.2.4, != 3.2.5, != 3.2.6, != 3.2.7, != 3.2.8, != 3.2.9, < 3.3, >= 3.1.10', '~> 3.1'
```

One difference I've noticed is that if I run `bundle show forem`, on my development computer I'm using ruby 1.9.3, and on the server, it's running ruby 2.1.0

**Comment by steve-abrams** [comment]
I've changed my RVM to 1.9.3 and it has no effect.  When I was getting this error on my development computer, all I had to do was upgrade to rails 3.2.13 from 3.2.1.  I've checked the version, and it's now running 3.2.13.  What else could be causing this error?

**Comment by steve-abrams** [comment]
my gemfile looks like this:

``` ruby
source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
 gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

gem 'delayed_job_active_record'

gem 'handles_sortable_columns'

gem 'will_paginate', '~> 3.0.5'

gem 'forem', :github => "radar/forem", :branch => "rails3"

gem 'forem-bootstrap', :github => "radar/forem-bootstrap"
```

**Comment by radar** [comment]
That is not an error message, it is only a warning and can be safely ignored.

**Comment by radar** [comment]
@sabrams86 Please use Rails 3.2.17. There have been four rails releases since 3.2.13 and you really have no excuse to not be using the latest.

**Comment by steve-abrams** [comment]
Isee it is just an error, however the app is just showing the passenger error page suggesting that I run bundle install to fix any issues, and the forem gem is the only gem that is actually different.

**Comment by radar** [comment]
That could be a deployment error on your server. Since we can't see the error nor what is causing it, I would suggest you hire someone who can help you debug it.
