### ISSUE TITLE
Textile / pluggable post formatting

### ISSUE THREAD

**Issue by nruth** [rubysherpas/forem#55]
We'd like to use textile rather than markdown for post formatting (for consistency with our cms).

Does anyone have suggestions for how this could be architected / an appropriate pattern for having plain text, or markdown, as default, but the possibility to change to something else?

**Comment by radar** [comment]
This is a very similar problem to #50, where the users would like to use WYSIWYG formatting. I suggested there that they split the part of the post partial that renders the text using the `forem_markdown` helper out into its own partial, which could then be over-written in the application (by simply having a partial called the same) which would allow you to format it using Textile.

But I think this solution may be a bit hacky. Do you have any other ideas on how you would do this?

**Comment by nruth** [comment]
That's a good point. We've already used the generate views stuff so I'll look at this as a quick-fix.

I was thinking of the adapter pattern, having a (forum) post processing adapter, which we could plug in and out as wanted.
The interface seems pretty simple, one method which takes the post text and returns HTML.

This would probably allow someone to extend markup to be a user preference, if the controller and user model were made smart enough. This isn't something I need right now but it could be attractive.

A residual problem would be the default gem dependency for markdown. This doesn't bother me much, but it does give me another idea. If no formatting was the default, then markdown, textile, or whatever, could be installed by adding a gem, like for loading themes.

**Comment by radar** [comment]
The adapter idea is a pretty good idea. 

The `forem_markdown` helper should be renamed to `forem_format`, which would simply call `Forem::Post#format`. This method then should be defined as just returning the post text, i.e. a no-op.

The markdown / textile / wysiwyg functionality then would be provided by a gem that has a module which is included into `Forem::Post` which would override this method, causing the text to be formatted correctly. As for the form, you could probably also override that in the engine, but I am not confident that would work as well as having it in the application.

Please do investigate :)

**Comment by nruth** [comment]
I've made the initial core changes, and put together a [gem for RedCloth/Textile formatting](https://github.com/nruth/forem-textile_formatter). It's also possible to just override the helper in the app which is loading forem.

https://github.com/nruth/forem/commit/486c1e54e834c8f2622ccdba255a9c4918aa5381

I'm not sure returning plain text is a good idea though; people will expect (safe) html to come back, which they can just insert into their template. Do you think it's sensible to make the default behaviour to wrap plain text in a pre tag? 
Or a p tag? More than that gets into re-implementing markdown territory.

**Comment by nruth** [comment]
Also, anyone who's used the forem view generator will get a method missing template error after this change.
It may be better to add a deprecation message to forem_markdown rather than simply removing it?

**Comment by radar** [comment]
I think deprecating it would be a much better alternative. Could you submit a patch for this?
