### ISSUE TITLE
Assets in vendor directory

### ISSUE THREAD

**Issue by bodrovis** [rubysherpas/forem#550]
Why `vendor/assets/stylesheets/forem.css.scss` is empty by default? Shouldn't it include `base.css` (https://github.com/radar/forem/blob/rails4/app/assets/stylesheets/forem/base.css) which requires `select2` styles? The same is with the `vendor/assets/stylesheets/forem.js.coffee` - it does not require `base`.

**Comment by bodrovis** [comment]
I think that inside `forem.css.scss` (in `vendor` directory) we should add:

```
@import 'forem/base';
```

and inside `forem.js.coffee`:

```
#= require forem.js.erb
```

(Btw why does this file has `.erb` extension?)

Or probably it would be even better to remove these files from the `app/assets` and place their contents inside `vendor`.

Also maybe we have to remind users to remove `#= require jquery` from `forem.js.coffee` if jQuery was required in some other place.

Also I think that it would be better to instruct user here https://github.com/radar/forem/wiki/Theming not to add these lines:

```
<%= stylesheet_link_tag "forem" %>
<%= javascript_include_tag "forem" %>
```

but to add 

```
@import 'forem.css.scss';
```

to their `application.css.scss`

and 

```
//= require forem
```

to the `application.js`. Otherwise when deploying to Heroku (and maybe not only to Heroku) I get this error: 

```
2014-03-26T11:29:28.337498+00:00 app[web.1]: ActionView::Template::Error (forem.
css isn't precompiled):
```

Which means that I have to manually specify it to be precompiled inside `application.rb`.

What do you think about that?

**Comment by radar** [comment]
The assets will remain in `app/assets` as much as possible because that way it's easier to roll out updates to those assets. All the assets in an application's `vendor/assets` should be responsible for is requiring those files and any extra things people want for their forem install.

Requires for the Forem assets do not belong in the application assets because they may conflict with styles for the application. For instance, someone may want their application and forem to be styled slightly different. Conflicting styles are no fun at all to debug, thus this decision.

**Comment by bodrovis** [comment]
Okay. 

I again tried to create a brand new app with Forem. I made absolutely no modifications to the config file, launched the server and opened `/forums`. I got this error:

```
Sprockets::Rails::Helper::AssetFilteredError in Forem::Forums#index 
Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( forem.css )` to `config/initializers/assets.rb` and restart your server
```

Also the same error appears stating that `forem.js` should also be added like this: `%w( forem.js )`. Adding this line fixes the problem.

Using Rails 4.1.1 and Devise, server was started in development environment.

**Comment by defaye** [comment]
Yeah I'm using Devise as well. But adding the line didn't do it for me. Can you show me your `config/initializers/assets.rb` ?

**Comment by bodrovis** [comment]
@defaye Well, actually that was the demo app for my article on Sitepoint http://www.sitepoint.com/forem-rails-forum-engine/ that explains how to set up Forem (you might want to read that - maybe this well help) and its source code can be found here https://github.com/bodrovis/sitepoint-forem

**Comment by defaye** [comment]
@bodrovis many thanks, I'll check it out :)
