### ISSUE TITLE
Forem layout reverts to default in production

### ISSUE THREAD

**Issue by bodrovis** [rubysherpas/forem#552]
I'm experiencing the same issue https://github.com/radar/forem/issues/548#issuecomment-38598855 with brand new app and only in production enviroment (on Heroku).

I got this in my `initializers/forem.rb`:

``` ruby
Forem.user_class = "User"
Forem.email_from_address = "please-change-me@example.com"
# If you do not want to use gravatar for avatars then specify the method to use here:
# Forem.avatar_user_method = :custom_avatar_url
Forem.per_page = 20

Rails.application.config.to_prepare do
#   If you want to change the layout that Forem uses, uncomment and customize the next line:
  Forem::ApplicationController.layout "application"
#
#   If you want to add your own cancan Abilities to Forem, uncomment and customize the next line:
#   Forem::Ability.register_ability(Ability)
end

```

When I open `/forums` everything is okay, but when I navigate to administration I keep getting this one (see this https://github.com/radar/forem/issues/550#issuecomment-38673933 for more info):

```
2014-03-26T12:12:10.642192+00:00 app[web.1]: Started GET "/forums/admin" for 194
.54.176.238 at 2014-03-26 12:12:10 +0000
2014-03-26T12:12:10.832918+00:00 app[web.1]: [deprecated] I18n.enforce_available
_locales will default to true in the future. If you really want to skip validati
on of your locale you can set I18n.enforce_available_locales = false to avoid th
is message.
2014-03-26T12:12:10.729574+00:00 app[web.1]: Processing by Forem::Admin::BaseCon
troller#index as HTML
2014-03-26T12:12:11.132588+00:00 app[web.1]:     2: <html>
2014-03-26T12:12:11.132581+00:00 app[web.1]:
2014-03-26T12:12:11.125218+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.0.0
/bundler/gems/forem-35f44591d530/app/views/forem/admin/base/index.html.erb withi
n layouts/forem/default (294.4ms)
2014-03-26T12:12:11.132596+00:00 app[web.1]:     6:     <%= javascript_include_t
ag "forem", "data-turbolinks-track" => true %>
2014-03-26T12:12:11.132597+00:00 app[web.1]:     7:     <%= csrf_meta_tags %>
2014-03-26T12:12:11.132609+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/act
ionpack-3.2.17/lib/sprockets/helpers/rails_helper.rb:49:in `block in stylesheet_
link_tag'
2014-03-26T12:12:11.132590+00:00 app[web.1]:     3:   <head>
2014-03-26T12:12:11.132592+00:00 app[web.1]:     4:     <title>Forem</title>
2014-03-26T12:12:11.132594+00:00 app[web.1]:     5:     <%= stylesheet_link_tag
   "forem", media: "all", "data-turbolinks-track" => true %>
2014-03-26T12:12:11.132603+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/act
ionpack-3.2.17/lib/sprockets/helpers/rails_helper.rb:151:in `rewrite_asset_path'

2014-03-26T12:12:11.132605+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/act
ionpack-3.2.17/lib/action_view/asset_paths.rb:27:in `compute_public_path'
2014-03-26T12:12:11.132587+00:00 app[web.1]: ActionView::Template::Error (forem.
css isn't precompiled):
2014-03-26T12:12:11.132599+00:00 app[web.1]:     8:     <%= forem_atom_auto_disc
overy_link_tag %>
```

The main thing to note is that it renders the `layouts/forem/default` instead of my `application` layout. Also in my layout I do not have this line:

```
<%= stylesheet_link_tag
   "forem", media: "all", "data-turbolinks-track" => true %>
```

**Comment by dsdewhir** [comment]
This same issue happens to me locally... the initializer makes the /forum views use my application layout, but once down into /forum/admin it reverts to the forem layout. Thin server and Rails 4.0.3:

Started GET "/forums/admin" for 127.0.0.1 at 2014-04-03 13:01:08 -0400
Processing by Forem::Admin::BaseController#index as HTML
  ←[1m←[36mUser Load (1.0ms)←[0m  ←[1mSELECT "users".\* FROM "users" WHERE "users
"."id" = 7 ORDER BY "users"."id" ASC LIMIT 1←[0m
  Rendered forem/admin/base/index.html.erb within layouts/forem/default (1.0ms)
Completed 200 OK in 65ms (Views: 61.0ms | ActiveRecord: 1.0ms)

**Comment by radar** [comment]
I don't understand how that's possible, given that they both use `Forem.layout`. Can you please provide us with an application that reproduces this issue, @dsdewhir?

**Comment by dsdewhir** [comment]
No, I'm overriding the /forums views to use my application layout, which does work.... but that is not being picked up once I get down to /forums/admin.

**Comment by bodrovis** [comment]
@radar You can use this brand new app https://github.com/bodrovis/SitePointForem to reproduce it, but for me it only happens on heroku. I've added you as a collaborator for that Heroku app, check your email. :)

**Comment by bodrovis** [comment]
Any luck with this?

**Comment by radar** [comment]
If there was any progress I would write about it here...

As it has been, I have been busy on Spree, preparing for my wedding in  a month, sleeping and many other things.

Patience is appreciated.

**Comment by bodrovis** [comment]
@radar Sorry, I did not mean to rush and all the stuff. Of course, you have a lot of thigs to do. Just let me know if there is any other info I can provide or help with.

**Comment by steveny** [comment]
Removing

```
def layout
  @@layout || "forem/default"
end
```

from lib/forem.rb seems to fix it for me.  I didn't dig in any further than that.

**Comment by steveny** [comment]
OK, so the admin base_controller.rb is wrapped in the module and picks up the above method.  application_controller.rb is not.  In any event, I was able to get it to work by:

Rails.application.config.to_prepare do
   Forem::ApplicationController.layout "application"
   Forem::Admin::BaseController.layout "application"
end

or

Forem.layout = "application"

**Comment by bodrovis** [comment]
@radar I can confirm that `Forem.layout = "application"` does fix this problem.

**Comment by radar** [comment]
@bodrovis Is it possible to still deploy that app to Heroku and see the breakage?

**Comment by bodrovis** [comment]
@radar Of course you can clone that app from heroku (I've added you to collaborators) and change the `Forem.layout = "application"` back to the `Forem::ApplicationController.layout "application"`

**Comment by acarr468** [comment]
The above fix works for me as well with rails 4.1

**Comment by djones** [comment]
Ensuring `config/initializers/forem.rb` is setup like this

``` ruby
Rails.application.config.to_prepare do
  Forem.layout = "application"
end
```

Fixed the issue for me.

**Comment by radar** [comment]
@djones Thanks. Isn't that what OP says? Can you still navigate to `/admin` and have it use the application layout correctly?
