### ISSUE TITLE
forem and zurb-foundation

### ISSUE THREAD

**Issue by Astr0surf3r** [rubysherpas/forem#553]
Hi Folks,

I customised my radar/forem views in the app using the zurb-foundation instead twitter-bootstrap and everything goes well but since I update the gem 

I simply replace

gem 'forem', :github => "radar/forem"

with

gem 'forem', :github => "radar/forem", :branch => "rails3"

and it doesn't work now that's the screenshot:

![screen shot 2014-03-27 at 4 31 57 pm](https://cloud.githubusercontent.com/assets/896968/2544897/836b513a-b608-11e3-8847-0e89cd0c9e99.png)

the head source is 

```
<head>
<title>Forem</title>
<link data-turbolinks-track="true" href="/assets/forem.css" media="all" rel="stylesheet" type="text/css" />
<script data-turbolinks-track="true" src="/assets/select2/select2.js?body=1" type="text/javascript"></script>
<script data-turbolinks-track="true" src="/assets/forem.js?body=1" type="text/javascript"></script>
<meta content="authenticity_token" name="csrf-param" />
<meta content="3232d+UXm44543tyraq232422323232bkCWptRUE=" name="csrf-token" />
</head>
```

thank you in advance for any tips

A

**Comment by bodrovis** [comment]
Could it be because now forem uses its own layout as default? See this wiki page https://github.com/radar/forem/wiki/Theming and this issue https://github.com/radar/forem/issues/552

**Comment by Astr0surf3r** [comment]
yeah! it seems work now! thanks!

**Comment by bodrovis** [comment]
@Astr0surf3r Don't you experience the same issue as described here https://github.com/radar/forem/issues/552 in production?
