### ISSUE TITLE
how can i read topic without log-in? 

### ISSUE THREAD

**Issue by humbroll** [rubysherpas/forem#555]
For customer(have no account), 
I want to authorize to them(customer) to read topic. 
Can I do that? 
Please any feed. 

Regards.

**Comment by bodrovis** [comment]
Unauthorized can read topics without having to log in https://github.com/radar/forem/blob/rails4/app/controllers/forem/topics_controller.rb#L4

**Comment by humbroll** [comment]
That's good thing. 
I retrieved Topic directly and make custom view. 
Thanks.
