### ISSUE TITLE
Race condition during parallel testing

### ISSUE THREAD

**Issue by GGuidice** [rubysherpas/forem#560]
I create a Singleton class and run parallel testing using Maven. 
I want the Singleton class to be instantiated only once. However, it is created every time when a test starts.
I use the keyword "synchronized" in Singleton class but it only prevent race condition within ONE test, not parallel tests. Is there any solution to parallel cases problem?
Here is the Singleton class definition:
![singleton](https://cloud.githubusercontent.com/assets/7460870/2855627/ef96e6b4-d15e-11e3-9368-e6aaf5e0fcc3.png)

Step definition:
![stepdef](https://cloud.githubusercontent.com/assets/7460870/2855643/43e2206c-d15f-11e3-9ba8-b16e013d4ffc.png)

Feature definition:

![feature](https://cloud.githubusercontent.com/assets/7460870/2859147/1fdb4810-d19b-11e3-823b-6f8dc7f38541.png)

And two test files start at the same time, each test is as follows:

![test1](https://cloud.githubusercontent.com/assets/7460870/2859146/0792ff1e-d19b-11e3-9331-4aa4eac38fe5.png)

Here is the result, as you can see, the Singleton object is created twice, one for each test run:

![result](https://cloud.githubusercontent.com/assets/7460870/2855907/a8eb0ae8-d162-11e3-8067-1b90328d9ce1.jpg)

Any idea to resolve this problem? Thanks a lot for your help.

**Comment by radar** [comment]
@GGuidice I fail to see at all how this relates to Forem. Did you mean to file this on another project?
