### ISSUE TITLE
Emoji and precompiling

### ISSUE THREAD

**Issue by bodrovis** [rubysherpas/forem#561]
I've created a brand new app with Rails 4.1.1. Firstly I got this problem: https://github.com/radar/forem/issues/550#issuecomment-42991605 but then I've tried to use some smiles in my test posts and started to get these errors:

```
Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( emoji/smile.png )` to `config/initializers/assets.rb` and restart your server
```

I believe that asking users to specify all the smiles for precompilation is not an option.

**Comment by radar** [comment]
@bodrovis: is this still an issue?

**Comment by bodrovis** [comment]
I believe this won't be an issue when the 596 will be merged. I will have to test this however because I hadn't used Forem for a while.

**Comment by radar** [comment]
Which part of #596? It is quite a large PR and I'm considering closing it and asking it to be split out into multiple PRs. Is it the emoji config inside `Forem::Engine` which needs doing for this?
