### ISSUE TITLE
Article about Forem

### ISSUE THREAD

**Issue by bodrovis** [rubysherpas/forem#570]
As promised I've published an article about Forem on Sitepoint http://www.sitepoint.com/forem-rails-forum-engine/ - if you find it suitable then maybe it would be a good idea to add this link somewhere in the Readme or wiki

**Comment by radar** [comment]
Thanks @bodrovis! I think it would be good to have a link to this on the wiki page here: https://github.com/radar/forem/wiki/Installing---Upgrading
