### ISSUE TITLE
Use more than one user_class?

### ISSUE THREAD

**Issue by SamLau95** [rubysherpas/forem#571]
Is it possible to use forem with more than one user_class? For past projects my user classes were subclassed from a base user class so this wasn't a problem. However, I'm working on a project now with separate Client and Admin models (devise is set up for each one) and want to let both Client and Admin make topics and posts with Admins having moderation rights. After setting `Forem.user_class = 'Client'` this is what I tried to let Admins be able to use the forum:

``` ruby
module ForemAdministrator
  extend ActiveSupport::Concern
  include Forem::DefaultPermissions

  included do
    def forem_admin?
      true
    end

    def forem_spammer?
      false
    end
  end
end
```

And I `include ForemAdministrator` in my Admin model. This allows me as an Admin to read all the pages, but I can't make posts as an Admin since in `post.rb` the line
`belongs_to :forem_user, :class_name => Forem.user_class.to_s, :foreign_key => :user_id`
only works with Clients. I also can't do topic creation and probably other actions as well. I was going to fork and make changes for my project but wanted to check just to make sure I didn't miss anything.

**Comment by radar** [comment]
No, sorry. Forem does not allow you to use more than one User class. If you would like this feature, please build a PR that adds it.

Thanks.
