### ISSUE TITLE
Sprockets::Rails::Helper::AssetFilteredError at / Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( forem.css )` to `config/initializers/assets.rb` and restart your server

### ISSUE THREAD

**Issue by defaye** [rubysherpas/forem#574]
On accessing http://localhost:3000/forums I'm getting the following error:

```
Sprockets::Rails::Helper::AssetFilteredError at /
Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( forem.css )` to `config/initializers/assets.rb` and restart your server
```

I have gone through your instructions on the main page. (As per: https://github.com/radar/forem#require-basic-forem-assets) as well as the other suggested additions to code.

 Besides manual `@import`s, my `application.css.scss` looks like:

```
/*
 *= require 'forem/base'
 *= require_self
 */
```

There is no `*= require_tree .` because I'm using bourbon (which cares about import order).

I really have no idea what I'm doing wrong. I tried the automatic suggestion in my `config/initializers/assets.rb` as `Rails.application.config.assets.precompile += %w( forem.css )` and tried variations like `forem`, `forem/base`.

Thanks

**Comment by bodrovis** [comment]
I'm also getting this but managed to fix that https://github.com/radar/forem/issues/550#issuecomment-42991605

**Comment by defaye** [comment]
@bodrovis it is possible that this line in my `config/initializers/assets.rb`: `Rails.application.config.assets.version = '1.0'` was preventing my assets being refreshed though I'm not sure. In any case, I removed that line and added `Rails.application.config.assets.precompile += %w( forem.css forem.js )` and all is well.

**Comment by bodrovis** [comment]
@defaye Okay, cool!
