### ISSUE TITLE
Disable "This post is currently pending review"

### ISSUE THREAD

**Issue by bennettl** [rubysherpas/forem#578]
When users post on the forum, I see the message "This post is currently pending review". I want posts/threads to be immediately visible to everyone and not in pending/review status when users post them. How do I achieve this? Thanks!

**Comment by radar** [comment]
Hi @bennettl, you can do this by disabling the [moderate_first_post](https://github.com/radar/forem/blob/cc6e884c64a0be5aa64647235ff604b42a04a51f/lib/forem.rb#L62-L65) feature:

(in `config/initializers/forem.rb`):

```
Forem.moderate_first_post = false
```

**Comment by bennettl** [comment]
Will this only affect first posts or also any subsequent replies as well? I don't want any posts/replies/threads to be moderated.

**Comment by radar** [comment]
This will only affect posts that appear after this change. If you want to move all posts to the proper state:

```
Forem::Post.update_all('state', 'approved')
```

**Comment by bennettl** [comment]
Does `Forem.moderate_first_post = false` apply to replies to threads as well?

**Comment by radar** [comment]
@bennettl Yes.
