### ISSUE TITLE
Redirect to return_path after signing in

### ISSUE THREAD

**Issue by LegendSzymon-P** [rubysherpas/forem#58]
It would be nice, if, when not signed in user tries to create topic is redirected to the sign in page, that then he would be redirected back to create form of a topic. For now, as far as I see, after signing in it redirects to the root_url.

**Comment by parndt** [comment]
So we'd want to use something like `redirect_back_or_default(root_path)`

**Comment by LegendSzymon-P** [comment]
I've digged up that Forem actually stores `return_to` url: https://github.com/radar/forem/blob/master/app/controllers/forem/application_controller.rb , in `session[:return_to]`, so, as for Devise, it is enough to overwrite `stored_location_for(resource)` in `ApplicationController` like this:

```
private
def stored_location_for(resource)
  session.delete(:return_to) || super(resource)
end
```

**Comment by parndt** [comment]
Patches gladly accepted! :-)

**Comment by LegendSzymon-P** [comment]
For now i've just created wiki page with that information: https://github.com/radar/forem/wiki/Redirect-to-return_to-path-after-signing-in-with-Devise

**Comment by radar** [comment]
I thought by doing `session[:return_to]` then Devise would return to that location? Maybe they've changed things since the last time I've looked.
