### ISSUE TITLE
when use rails 4.0.2

### ISSUE THREAD

**Issue by qazwsx9006** [rubysherpas/forem#585]
My rails version is 4.0.2

in my Gemfile

I add 
 "gem 'forem', :github => "radar/forem", :branch => "rails4""

than bundle install

and I have this problem:

<pre><code>
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (4.0.2)

  In Gemfile:
    forem (>= 0) ruby depends on
      rails (<= 4.1.4, >= 4.0.3) ruby
</code></pre>

I can't change rails version.
how could I solve this problem!?

**Comment by radar** [comment]
Why can't you change Rails versions?

**Comment by qazwsx9006** [comment]
because my boss :((

**Comment by radar** [comment]
Your boss is wrong.

Older versions of Rails may have security bugs and so by staying on those old versions you're leaving yourself vulnerable.

Upgrade.
