### ISSUE TITLE
Error NoMethodError in Forem::Moderation#index when click on Moderation tool(topic) in admin area

### ISSUE THREAD

**Issue by joomalungma** [rubysherpas/forem#586]
I have fresh Forem installed. 
Rails 4.1.1  and Forem i believe it's 1.0.0.beta1
I didn't do any special steps. Confirmed on two DB. Development DB with your installed data and on the production DB with Topic created by my own. 
[Gemfile](https://gist.github.com/joomalungma/42c9171973b058807ac2)
[Gemfile.lock](https://gist.github.com/joomalungma/187b043248d75661e635)
[Full Trace](https://gist.github.com/joomalungma/953a5888260fc09dd7b3)

The problem disappeared if I copy file 
_/vendor/bundle/bundler/gems/forem-b752c8ef3ac8/app/helpers/forem/topics_helper.rb_
to the folder
_/vendor/bundle/bundler/gems/forem-b752c8ef3ac8/app/helpers/forem/admin/_

**Comment by radar** [comment]
Hi @joomalungma, what is the exact error message? You've shown the error header and the stacktrace (which is great btw :D), but I don't know what the error message is. If I knew that, then I would know why adding `topics_helper` to the `admin` directory would help.

Please let me know that.

**Comment by joomalungma** [comment]
Hello, sorry my fault. The error is 
Showing /app/views/forem/posts/_post.html.erb where line #33 raised:
undefined method `post_time_tag' for #<#Class:0x0000010355b988:0x000001031013b0>

``` ruby
<div class='contents col-md-7'>
           <a href='#post-<%= post.id %>'>
             <%= post_time_tag(post) %>
           </a>
           <%= forem_format(post.text) %>
```

**Comment by radar** [comment]
Thanks @joomalungma. Could you please create a PR that applies this change that you mention, and also has a regression test for it? That would be great.

**Comment by joomalungma** [comment]
Hello @radar 
I can't confirm this problem in the 'dummy_app' to create test. I'm a new in ruby. Could you please suggest anything?  )

**Comment by joomalungma** [comment]
See here - Error in moderation page #607
