### ISSUE TITLE
Problem replying to posts or topics made by other users on Heroku

### ISSUE THREAD

**Issue by tannart** [rubysherpas/forem#587]
Both on my own forem based app and on the demo app, whenever I try to post a reply to another users post or topic I get the error message:

We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

Not sure if this is an issue with heroku or with forem, but I've checked the heroku logs as instructed and there seems to be nothing useful being returned.

**Comment by bodrovis** [comment]
This is definetely related to the app and `heroku logs` should return some kind of an error...

**Comment by tannart** [comment]
But I'm even getting the same error when I try to respond to someone elses post on the sample app at:
http://forem.herokuapp.com
It could well just be me being stupid though, I was wondering if anyone else was having success replying to other users?

**Comment by radar** [comment]
Hi @MacFarlaneBro, as @bodrovis suggests, please look in `heroku logs`. This should show an error. Please let us know what that error is.

**Comment by tannart** [comment]
Started POST "/forums/general-54e784f9-239e-4b76-aa47-ea553477d52a/topics/this-is-a-new-topic/posts" for 82.69.203.230 at 2014-08-19 08:15:12 +0000
Processing by Forem::PostsController#create as HTML
Processing by Forem::PostsController#create as HTML

Parameters: {"utf8"=>"✓", "authenticity_token"=>"93r3JX+sGlJwwScLL52DP1Eel1ZB2GjWjQ7+ObqUOso=", "post"=>{"text"=>"THis is bogus", "reply_to_id"=>"12"}, "commit"=>"Post Reply", "forum_id"=>"general-54e784f9-239e-4b76-aa47-ea553477d52a", "topic_id"=>"this-is-a-new-topic"}

Parameters: {"utf8"=>"✓", "authenticity_token"=>"93r3JX+sGlJwwScLL52DP1Eel1ZB2GjWjQ7+ObqUOso=", "post"=>{"text"=>"THis is bogus", "reply_to_id"=>"12"}, "commit"=>"Post Reply", "forum_id"=>"general-54e784f9-239e-4b76-aa47-ea553477d52a", "topic_id"=>"this-is-a-new-topic"}

Rendered forem/subscription_mailer/topic_reply.text.erb (6.8ms)
Sent mail to charliembrodie@gmail.com (7.4ms)
Rendered forem/subscription_mailer/topic_reply.text.erb (6.8ms)

Completed 500 Internal Server Error in 59ms
Sent mail to charliembrodie@gmail.com (7.4ms)
Completed 500 Internal Server Error in 59ms

Errno::ECONNREFUSED (Connection refused - connect(2)):

This is the output of the logs (minus the stack trace obviously), please let me know if you need any more information.

I'm not having this issue on my local server, just on heroku and as I said before I get the same "We're sorry, but something went wrong" message when trying to post a reply to another user on your sample forem application as well.

Thanks for the help!

**Comment by bodrovis** [comment]
@MacFarlaneBro https://stackoverflow.com/questions/11446094/heroku-errnoeconnrefused-connection-refused-connect2

**Comment by bodrovis** [comment]
https://stackoverflow.com/questions/20635438/post-and-errnoeconnrefused-connection-refused-connect2

**Heroku does not allow you to send emails using the internal SMTP. You need to use one of the Heroku add-on.**

I am not sure if this is still true though.

**Comment by tannart** [comment]
That's solved it! Thanks so much, not sure how I missed that error message.

If anyone else is having the same problem it's because Heroku does not provide an outgoing mail service by default, therefore when a user tries to reply to another user an email is sent to the user being replied to alerting them, without a default outgoing mail service the app has no way to handle this so just crashes.

However Heroku does allow the use of an external SMTP server, for example I used the free sendgrid addon, installed using the following command: `$ heroku addons:add sendgrid:starter` 

More information on configuring the sendgrid addon on heroku can be found here: https://devcenter.heroku.com/articles/sendgrid .

**Comment by radar** [comment]
Great :) I think Forem should probably raise a better exception here. A patch for that would be great :)
