### ISSUE TITLE
Restrict Forum Access To Members Only?

### ISSUE THREAD

**Issue by bennettl** [rubysherpas/forem#588]
I have a helper function that redirects users to the main page if they are not members, but I'm not sure how to apply this filter to the forem controller?

**Comment by radar** [comment]
Hi @bennettl,

You can use decorators for this. 

**app/decorators/controllers/forem/application_controller_decorator.rb**

``` ruby
Forem::ApplicationController.class_eval do
  before_filter :restrict_to_members_only
end
```
