### ISSUE TITLE
[closed] Forem incompatible with Rails 4.1.5

### ISSUE THREAD

**Issue by mib32** [rubysherpas/forem#590]
I found that i can't install forem gem because it is dependant on rails < 4.1.4.

**Comment by mib32** [comment]
i added pull request here https://github.com/radar/forem/pull/591

**Comment by frankie-loves-jesus** [comment]
@mib32 could you please update it to 4.2.0 beta so we can speed things up with Adequate Record as well?

http://weblog.rubyonrails.org/2014/8/20/Rails-4-2-beta1/

**Comment by mib32** [comment]
@frankie-loves-jesus sorry, but i can't test it with 4.2.0 beta since i don't have one

**Comment by mib32** [comment]
this should be closed since https://github.com/radar/forem/pull/591 is closed
