### ISSUE TITLE
Font sizing in reply_to view is much too large and overlaps

### ISSUE THREAD

**Issue by WeremyJalters** [rubysherpas/forem#592]
When replying to posts both in my app and the demo app, the font sizing is much to large (h2, I believe) and it overlaps. It's must larger than the fonts of the views where I create posts. Is there anything I,or you folks, could do about that?
![screen shot 2014-09-07 at 2 36 13 am](https://cloud.githubusercontent.com/assets/7084383/4177730/57028006-3659-11e4-9e88-b68b3fa314ed.png)

**Comment by bodrovis** [comment]
@WeremyJalters The Bootrstrap theme is partially broken so you either can tweak it for yourself or fix it and send pull request here.

**Comment by WeremyJalters** [comment]
I'm relatively new to rails and tweaking themes, but I'll give it a try. If anyone else solves the issue or has any guidance, please comment here..

**Comment by radar** [comment]
@WeremyJalters https://github.com/radar/forem-bootstrap is the theme that @bodrovis is talking about. All the code for the default Forem theme is there. I would recommend you look at that code and fix the classes used for the "byline" of the post.

**Comment by louiecaulfield** [comment]
I believe I fixed this in 5c45167433077755880f804de3159ca1ce8a9031
