### ISSUE TITLE
Formatters and code

### ISSUE THREAD

**Issue by louiecaulfield** [rubysherpas/forem#594]
When using a formatter - I'm trying to get things to work with Kramdown - the sanitazation after the parse step removes HTML tags and escapes greater and less than charachters inside code blocks.

The text in code blocks should be preserved.

**Comment by bodrovis** [comment]
@louiecaulfield There is a long story behing formatters: https://github.com/radar/forem/issues/512 and https://github.com/radar/forem/issues/359 

I have found that forem-redcarpet is the best choise for now.

**Comment by louiecaulfield** [comment]
After some digging into the code, I have concluded the same. 

I do think it would make forem quite a bit more adoptable if installing the redcarpet gem formatter was part of the setup procedure in the docs, a recommendation from the developer goes a long way. Besides that, it's the last one in the [list of formatters](https://github.com/radar/forem/wiki/Formatters). I don't think it would be bad to put it at the top of the list and tag it as recommended.

That all is of course if radar feels like recommending this formatter.
