### ISSUE TITLE
Forem is displayed without formatting

### ISSUE THREAD

**Issue by fchampreux** [rubysherpas/forem#598]
May you can help me for this issue (Sorry, I am not highly experienced in RoR programming):
I installed Forem+Devise based on Ilyas Bodrov tutorial (Excellent !)
All setup is successfull, and Forem features seem to work fine, but with absolutely **no formatting !**

I frequently had this warning:
_requiring 'emoji/railtie' is deprecated. Please manually add Emoji.images_path to your config.assets.paths._
Which I tried to correct without success based on following recommendations:

add to config/application.rb

>   config.assets.paths << Emoji.images_path
>   config.assets.precompile << "emoji/*_/_.png"

and add to config/initializers/assets.rb

>    Rails.application.config.assets.precompile += %w( emoji/smile.png ) 

(my code is available at https://github.com/fchampreux/ODQ_Web.git )
An advice would be much appreciated.
**PS: I am running Rails 4.1.5**

Thanks a lot,

Best regards,

Fred

**Comment by frankie-loves-jesus** [comment]
The problem is https://github.com/radar/forem/blob/rails4/lib/forem/engine.rb#L26. I think that and L27 shouldn't be there.

**Comment by fchampreux** [comment]
Actually, the file _assets/stylesheets/application.css_ should be renamed to **application.css.scss** to be processed by Bootstrap.
Newbie error, sorry for disturbing !

Best regards, and thanks for this useful engine !

Best regards,

Fred

**Comment by radar** [comment]
Aha :) Glad you were able to figure this one out for yourself @fchampreux :+1:
