### ISSUE TITLE
requiring 'emoji/railtie' is deprecated.

### ISSUE THREAD

**Issue by pierallard** [rubysherpas/forem#601]
Hi everyone

I just install forem for Rails 4 and get this warning when I run console or server :
requiring 'emoji/railtie' is deprecated. Please manually add Emoji.images_path to your config.assets.paths.

This message comes from https://github.com/github/gemoji/blob/master/lib/emoji/railtie.rb
In my opinion, this file is the origin :
lib/forem/engine.rb

(Contains "require 'emoji/railtie'")

Versions :
gemoji (2.1.0)

**Comment by radar** [comment]
Hi @pierallard, thanks for that. Could you please submit a patch to fix this issue?

**Comment by pierallard** [comment]
Hi @radar 
I try to to do a patch for it (first time).
I have issues for running tests

$ bundle exec rake forem:dummy_app
... some table creations ...
undefined method `table_name' for nil:NilClass/HOME/forem/spec/dummy/db/migrate/20140922080648_add_forem_admin.forem.rb:10:in`user_class'

The issue can be resolved with a simple replacement in lib/forem/engine.rb
-require 'emoji/railtie'
+require 'emoji'

Then everything works fine.

**Comment by radar** [comment]
No worries @pierallard :) I'll investigate that problem when I get a chance.
