### ISSUE TITLE
Forum works locally but doesn't show up in production

### ISSUE THREAD

**Issue by pavankat** [rubysherpas/forem#603]
Locally the forum shows up but in production it only shows the h1 when going to the forums route.

Is there a rake task that needs to be called in production?

My local set up uses postgres and my production app uses postgres.

Also, I'm using DigitalOcean and Cloud66 to deploy.

I didn't tinker with any of the settings.

**Comment by bodrovis** [comment]
@pavankat Some time ago I've written a tutorial to setup Forem, maybe it will help you: http://www.sitepoint.com/forem-rails-forum-engine/

**Comment by jengel3** [comment]
Can you provide your source?

**Comment by pavankat** [comment]
@bodrovis I did this:

`Rails.application.config.to_prepare do
  Forem.layout = "application"
end`

And then the page throws errors whenever I try to render links going to certain paths. 

undefined local variable or method `teacher_path' for #<#Class:...

**Comment by pavankat** [comment]
@Jake0oo0 it's in a private repository so it's tough to provide it all. Thanks for reaching out though.

**Comment by bodrovis** [comment]
@pavankat Please note that to use route helpers from your app inside Forem you have to use `main_app`, therefore your method probably be `main_app.teacher_path`. Forem's route should be used with `forem`, like `forem.forums_path`.

**Comment by pavankat** [comment]
@bodrovis thank you!!!

And I figured it out. There are no forums made in production. Doh!
