### ISSUE TITLE
simple_fields_for conversion to fields_for

### ISSUE THREAD

**Issue by pavankat** [rubysherpas/forem#606]
# This doesn't work:

`<%= fields_for :posts do |post| %>`
   `<%= render :partial => "forem/posts/form", :locals => { :f => post } %>`
 `<% end %>` 
### it generates

`<textarea id="posts_text" input_html="{:class=>&quot;field col-md-12&quot;}" name="posts[text]"></textarea>`
# This works and is what the views of forem generates:

`f.simple_fields_for :posts do |post|`
  `render :partial => "forem/posts/form", :locals => { :f => post }`
`end`
### It generates

`<textarea id="topic_posts_attributes_0_text" input_html="{:class=>&quot;field col-md-12&quot;}" name="topic[posts_attributes][0][text]"></textarea>`

**Comment by radar** [comment]
Is that code from within Forem or your own code?

**Comment by pavankat** [comment]
@radar the code that works is from Forem. The code that doesn't work is my own code. 

I'm trying to not use simple form so I can style it the way I'd like. Any help would be incredible.

**Comment by frankie-loves-jesus** [comment]
Sounds like you need to copy Forem's views into your own app (`rails g forem:views`) and then customize them.

**Comment by pavankat** [comment]
@frankie-loves-jesus I did. I ran 

rails g forem:views

and it made 

`f.simple_fields_for :posts do |post|`
 `render :partial => "forem/posts/form", :locals => { :f => post }`
`end`

I don't want to use simple_form 

I want to use form_for. But when I use form_for it generates html that's different than simple_fields_for and the form doesn't work.

How do I change my code up

`<%= fields_for :posts do |post| %>`
 `<%= render :partial => "forem/posts/form", :locals => { :f => post } %>`
 `<% end %>`

**Comment by knewter** [comment]
I have to say that this is absolutely not an issue with forem.  I'm fine with this being a place to discuss amongst yourselves, but having this show up in @radar's inbox as an issue is...pretty awful.  Closing it :)

**Comment by frankie-loves-jesus** [comment]
@pavankat simple_form should work fine. Are you able to reproduce the issue at http://runnable.com/U9Qwd84r1EkCqrKA/basic-forem-demo? Sounds like you got something else HTML escaping your forms.

**Comment by pavankat** [comment]
Hey my friend got it to work. I'll post the ruby that properly converts it when I get home.

**Comment by radar** [comment]
Thank you @knewter and @frankie-loves-jesus.

**Comment by pavankat** [comment]
@frankie-loves-jesus 

`<%= f.simple_fields_for :posts do |post|  %>`
    `<%= render :partial => "forem/posts/form", :locals => { :f => post } %>`
`<% end %>`

worked fine in the end. Thanks everyone for your help.

**Comment by radar** [comment]
Glad to see you got a solution @pavankat.
