### ISSUE TITLE
Feature: edit posts

### ISSUE THREAD

**Issue by nruth** [rubysherpas/forem#61]
Currently users (and admins) can't edit posts within a topic. This is pretty standard forum behaviour. 
It should be quite simple to do this the easy way: allowing users and admins to perform ordinary model updates. 

I imagine there are concerns about post versioning, e.g. letting people see how the post looked before it was edited?

**Comment by radar** [comment]
I believe this has been implemented now. Please open another issue if there's a problem / feature request for that.
