### ISSUE TITLE
posts controller hasn't index action

### ISSUE THREAD

**Issue by yahor** [rubysherpas/forem#613]
AbstractController::ActionNotFound: The action 'index' could not be found for Forem::PostsController
 error appears if user uses this route:
 forum_topic_posts GET    /:forum_id/topics/:topic_id/posts(.:format)              forem/posts#index

question: 
Why routes exists, but action is not?

**Comment by radar** [comment]
Probably an oversight. The `topics/show` page doubles as the `index` page for the posts. Could you please submit a PR that removes this route?

**Comment by yahor** [comment]
https://github.com/radar/forem/pull/615

**Comment by radar** [comment]
Fixed by #615.
