### ISSUE TITLE
Using permissions outside of forem

### ISSUE THREAD

**Issue by dalvallana** [rubysherpas/forem#621]
Hi guys!

I have a simple blog application besides the forem forums. I would like to leverage forem's moderators functionality in my blog, so, for example, I can allow certain forum moderators to create new posts in the blog and edit them. I've been trying to use some forem methods like the one in 'forem/application_controller': `forem_admin_or_moderator?(forum)`, but I'm not able to do it.

Has anybody tried to do something similar?

Thanks!

**Comment by dalvallana** [comment]
I made it work by adding a `before_filter :ensure_moderator_or_admin` to my posts_controller.rb, and defining the method:

```
def ensure_moderator_or_admin
  unless current_user.admin_or_moderator?
    redirect_to root_path, notice: "Access denied."
  end
end
```

And, in my User model, defining the method:

```
def admin_or_moderator?
  self.forem_admin? || (Forem::Membership.where("group_id = ? AND member_id = ?", certain_group, self.id)).any?
end
```

I'm aware this is inelegant and not the Rails way. But I'm new in this world, and I just don't know how to do it right.

I'm not gonna close this thread in case anyone can enlighten me with the right solution.

Thank you, guys!

**Comment by radar** [comment]
I've never heard of someone trying to do this before. I'm surprised that `Forem::Membership` doesn't have a helper method to find records for a specific group or member... It wouldn't be used anywhere in Forem atm, but it could be good for convenience's sake in the future.

I think the way that you've done it now is good enough :)

**Comment by dalvallana** [comment]
Thank you, Ryan!
