### ISSUE TITLE
Can I disable a friendly_id?

### ISSUE THREAD

**Issue by ryush00** [rubysherpas/forem#630]
My country using unicode language in title (such as Korean).

When I write the post, link seems unfriendly.

![Imgur](http://i.imgur.com/LtgVW5V.png)

So, I want to disable this friendly_id. Is it possible?

**Comment by radar** [comment]
Not easily unfortunately. The only thing I can recommend doing is forking forem and removing it, and then replacing it with stringex.

**Comment by ryush00** [comment]
Hmmm.... It seems very hardly...
Then, How to change it to number id (like "1","2","3")?

**Comment by radar** [comment]
If you want to change it to a number then just fork Forem and remove friendlyid.

**Comment by radar** [comment]
If you want to change it to a number then just fork Forem and remove friendlyid.
