### ISSUE TITLE
dependency on simple_form ~> 3.0.1 - 3.1.0 needed

### ISSUE THREAD

**Issue by tomg65** [rubysherpas/forem#637]
Hi,

I tried to integrate forem in an existing rails apllication (rails 4.1.9 ruby 2.1.3)
There is already a cms engine (https://github.com/AlchemyCMS/alchemy_cms) integrated that depends on simple_form 3.1.0.

So I can't install forem in this application.

Is it possible to upgrade the dependency in forem?

Thanks
Thomas

**Comment by radar** [comment]
I don't understand. Why can't you install Forem into this application?

**Comment by radar** [comment]
If all it is is the `simple_form` dependency in the gemspec, why not submit a patch to change it to something more like:

``` ruby
s.add_dependency 'simple_form', '~> 3.0'
```

I think that would seem pretty reasonable.

**Comment by tomg65** [comment]
bundler stops while showing a conflict message in combination with the other gem, which is dependent on simple_form 3.1
OK - changed the dependency in your gemspec. and made a pull request #639 
With this adaption bundle install works.

**Comment by radar** [comment]
Done already I believe.
