### ISSUE TITLE
undefined local variable or method `forem'

### ISSUE THREAD

**Issue by pavankat** [rubysherpas/forem#642]
I'm using the sitemap_generator gem and am running into an issue getting forem routes to work inside the sitemap.rb file.

These are the gems I'm using

```
gem 'forem', :git => 'git://github.com/radar/forem.git', :ref => '8b4999af3c702603414f6ba9efc1848a0cdb6dbe'

gem 'sitemap_generator', '~> 5.0.5'

```

This is my sitemap.rb file (located inside the config folder). It works for all the paths except the forem ones

```
SitemapGenerator::Sitemap.default_host = 'http://domain.com'
SitemapGenerator::Sitemap.create do
  add root_path, :changefreq => 'weekly', :priority => 0.9

  add new_contact_path, :changefreq => 'monthly'

  add about_path, :changefreq => 'weekly'

  add terms_conditions_path, :changefreq => 'weekly'

  add privacy_policy_path, :changefreq => 'weekly' 

  add press_path, :changefreq => 'weekly' 

  add faq_path, :changefreq => 'weekly' 

  add articles_path, :changefreq => 'weekly'

  Forem::Forum.find_each do |f|
    add forem.forum_path(f), :changefreq => 'weekly'
  end
end
```

**Comment by radar** [comment]
I don't know how we are supposed to fix this. It's a problem with generating a sitemap and nothing about forem.

Perhaps try Forem::Engine.routes.url_helpers instead of just forem?

**Comment by pavankat** [comment]
That's a good point Ryan. I'm closing this right now since it doesn't have to do with Forem. Thanks for the help.

**Comment by pavankat** [comment]
But it would be good to note for anyone else in this situation that this solved it:

`forem = Forem::Engine.routes.url_helpers`

Thanks @radar

**Comment by radar** [comment]
Glad to see the solution was a simple one :)
