### ISSUE TITLE
Moving Topics Around Forems

### ISSUE THREAD

**Issue by Buildzzz** [rubysherpas/forem#644]
Hi all,

I just updated the gem which included the new Position columns in Forem::Categories and Forem::Forum.  

Since the update, when my moderators want to move a topic from forum to forum, the order of the forums that show up as a list have changed and are now out of sync.  Is there a way as an admin I can reorder the forums and how they show up in the list?  

Best

**Comment by radar** [comment]
@Buildzzz Do you have a way to reproduce this problem in a new app? Positions of forums are managed in the admin backend.

**Comment by Buildzzz** [comment]
@radar When I go the admin area of the forem gem, there are three links:
- Manage Forums
- Manage Forum Categories
- Manage Groups

Going into Manage Forums and Manage Forum Categories, I see that I can edit the name and description, but do not see where I state the order of the forums.  

Am I going to the right location?

**Comment by radar** [comment]
It's on the forum form in the admin backend. Make sure you have upgraded to the latest forem.

**Comment by Buildzzz** [comment]
Hi @radar ,

Seems that my views were not updated when I updated the Gem.  Thanks for the help!
