### ISSUE TITLE
heroku demo site is getting "something went wrong"

### ISSUE THREAD

**Issue by kchsieh** [rubysherpas/forem#646]
When trying out the 'reply' function at (forem.herokuapp.com), keep getting error message:

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Comment by radar** [comment]
This is just because I've been really lazy and haven't set up any SMTP settings on the app. I'll fix that up this week since it's an easy fix.

**Comment by radar** [comment]
All good now.
