### ISSUE TITLE
problems with bundler and forem:install

### ISSUE THREAD

**Issue by Shomari** [rubysherpas/forem#651]
I'm not sure if this is a forem or bundler problem but I was having an issue running the forem installer. I had gem 'forem', :github => "radar/forem", :branch => "rails4" (running rails 4.1.10) in my gemfile as directed and ran bundler and everything works fine.

When I go to run forem:install I would always get this error:  `rescue in load_spec_files': https://github.com/radar/forem.git (at rails4) is not yet checked out. Run`bundle install` first. (Bundler::GitError).

The installer would still ask me what my user models were but wouldn't run any of the migrations or do anything else.  

I temporarily got around this problem by cloning the repo and pointing to my local copy in the gemfile and everything works fine.

**Comment by lkrubner** [comment]
I have a similar problem.

**Comment by radar** [comment]
Similar or the same?

**Comment by radar** [comment]
Please provide steps to reproduce this issue.

**Comment by hugobyrne** [comment]
Identical issue for me too. Like shomari above I cloned the Forem repo to local drive updated the Gemfile to point to it and then got this error:-

Copying over Forem migrations...
/usr/local/rvm/gems/ruby-2.2.0@rails4.2/gems/bundler-1.7.10/lib/bundler/source/git.rb:188:in `rescue in load_spec_files': https://github.com/stripe/stripe-ruby (at master) is not yet checked out. Run`bundle install` first. (Bundler::GitError)

So now the Forem install task was giving me the same error except this time referencing the Stripe gem (which was also pointed to Github).

I commented out the Stripe gem reference in my Gemfile and then the install ran fine.

**Comment by radar** [comment]
@gitpenguin Forem doesn't use Stripe. It could be an issue with bundler in your case.

Either way, I am closing this issue as nobody has provided accurate steps to reproduce a problem.

**Comment by jdurand** [comment]
I had the same problem as @gitpenguin; running the forem install script on an existing app raised a `Bundler::GitError` : 

```
/Users/jdurand/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler/source/git.rb:192:in `rescue in load_spec_files': git://github.com/radar/forem.git (at rails4) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
```

I managed to install forem by creating a patch from the result of the install on a fresh rails app and applying it to my existing app.

**Comment by radar** [comment]
@jdurand Do you have an app that reproduces this issue that I could take a look at?
