### ISSUE TITLE
Error in Creating New Topic Without Any Post

### ISSUE THREAD

**Issue by edmondchui** [rubysherpas/forem#657]
Branch: rails4

When I tried to create a new topic, I got the error

```
undefined method `user=' for nil:NilClass/Users/echui/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/forem-c3b763b5fb28/app/models/forem/topic.rb:143:in `set_first_post_user'
```

The root cause is that the filter `before_save  :set_first_post_user` is expecting a post

https://github.com/radar/forem/blob/rails4/app/models/forem/topic.rb#L141-L144

``` ruby
    def set_first_post_user
      post = posts.first
      post.user = user
    end
```

Is this a bug or a design issue?

**Comment by radar** [comment]
How are you trying to create this new topic? Please provide some steps to reproduce the issue on a new app.

**Comment by edmondchui** [comment]
Here is how I create a topic

``` ruby
# creates a valid Forem::User
user = User.create!
forum = Forem.create!
topic = Forem::Topic.create(subject: "New Topic", forum_id: forum.id, user_id: user.id, state: :approved)
```

**Comment by yan-hoose** [comment]
You are not including post text with `create` and since there is no post text, there will be no post and you'll get the exception. This works:

``` ruby
topic = Forem::Topic.create(subject: 'New Topic', forum_id: forum.id, user_id: u.id, posts_attributes: {'0' => {text: 'Post Text'}})
```

**Comment by radar** [comment]
What Yan-Hoose said.

**Comment by edmondchui** [comment]
Thanks @yan-hoose.

My intention is to create an empty topic to start with. That's why I didn't provide a post text. Is that a valid use case?

**Comment by yan-hoose** [comment]
You're welcome!

But I'm not sure if a topic with only a subject and without content is useful. A topic should have something in it or it would be meaningless. That is what Forem assumes, that you have a topic with a first post as the topic text.
