### ISSUE TITLE
Forum Categories

### ISSUE THREAD

**Issue by gabrielbaez** [rubysherpas/forem#66]
It would be nice if the forum had category support like  phpbb3 does.

**Comment by radar** [comment]
If you submit a pull request with code that does this then it would :)

**Comment by radar** [comment]
@gabrielbaez: Have you had a go at this yet? I think it would be good to have this feature in Forem and I'd be happy to provide feedback / guidance on any code you write for it.

**Comment by gabrielbaez** [comment]
sorry, I haven't had time been busy.

**Comment by gabrielbaez** [comment]
@radar I started to give this a crack  using fluxbb as a guide,  I have it working,  but I do not have the piece for  creating the category for the admin panel,  I can't seem to get  rake routes to  work.    here is a screen shot of the forum.

http://dl.dropbox.com/u/875374/forem/category.png

**Comment by radar** [comment]
Ok, that all seems fine... what's the issue with `rake routes`? Can you proceed without it?

**Comment by gabrielbaez** [comment]
It was throwing me off at first, since I'm used to using  that command to get the list of routes whenever I'm working on something,  but it did not stop me from making the categories admin section.

**Comment by gabrielbaez** [comment]
Feature has been implemented.
