### ISSUE TITLE
Force Moderation on All Posts

### ISSUE THREAD

**Issue by vkoves** [rubysherpas/forem#661]
Is there a way that I can force moderation for all posts, and disable the spam/approval process? I would like all posts to have to be approved by a moderator, and then user can individually be "approved" and "blacklisted" instead of it being done automatically. I tried some overrides to accomplish this, but that has not worked so far.

Any suggestions, or is it possible this will be added in the future?

**Comment by radar** [comment]
`Forem.moderate_first_post = false` in `config/initializers/forem.rb`.

**Comment by vkoves** [comment]
This doesn't work. After testing, it just disables all moderation, which is the opposite of what I want. This is also what you said [here](https://github.com/radar/forem/issues/578) when someone was trying to prevent moderation.

So is there any way I can prevent users from being "approved" and force every single post to be moderated?

**Comment by vkoves** [comment]
After digging through the code, this override let me do it:

```
 # We don't want forem auto moderating stuff, so let's do this
  Forem::Post.class_eval do
    def skip_pending_review
        approve! unless user && true #user.forem_moderate_posts?
    end
  end
```

Is there an official way that I am missing (didn't see one in the documentation)?

Thanks again, forem's been a real treat.

**Comment by radar** [comment]
Ah, I understand now. Yes you can override it like that to accomplish what you want.
