### ISSUE TITLE
Method to query a group of forums 'last_post_for(forem_user)'

### ISSUE THREAD

**Issue by Buildzzz** [rubysherpas/forem#667]
Hi,

I am currently displaying a group of forums (lets say for example 50 forums) and alongside each forum name, I'm calling 'last_post_for(forem_user)' to show the latest post in that forum.

The problem is that we have a lot of forums and a lot of visitors to the page.  This is causing a strain and I'm hoping to optimize my code. 

So instead of querying my database 50 times to get the latest post, is there a way to query all the latest posts for each of my forums in one query and then do an each loop to display the resulting data?

Your help is greatly appreciated.

**Comment by radar** [comment]
Did you figure it out?

**Comment by Buildzzz** [comment]
Hi Ryan,

No, I was going to take a crack at creating my own method to solve the
issue.  I wasn't sure if the gem already came with a premade solution?

Best,
Tim Zhu

**Comment by radar** [comment]
The gem doesn't come with a premade solution for querying multiple forums. If you could come up with one and share it with us, that would be appreciated :)

**Comment by Buildzzz** [comment]
Hi Ryan,

I would be happy to once I get it working on my end.

Best,
Tim Zhu

**Comment by Buildzzz** [comment]
Hmm...

lastposts = Forem::Post.joins('INNER JOIN "forem_topics" ON
"forem_posts"."topic_id" = "forem_topics"."id" WHERE
"forem_topics"."forum_id" IN ' + array_of_forum_ids + ' ORDER BY
forem_posts.created_at DESC').group(:forum_id, :id).select(:id,
:created_at, :topic_id, :user_id)

Gets us almost there.  The issue is that it returns all the posts from the
forums in that 'array_of_forum_ids'.  I'm struggling with how to only
return one Post for each of the forums in the 'array_of_forum_ids'.

Best,
Tim Zhu

**Comment by Buildzzz** [comment]
Hi Ryan,

After beating my head against the wall, I figured out a solution.  Not sure
where/how you would like for me to integrate it into the gem but here's the
method:

def lastpostforforums(array_of_forum_ids)

forumids = array_of_forum_ids

lastposts = Forem::Post.joins(:topic).where(topic_id:
Forem::Topic.where(forum_id: forumids, hidden: [false,
nil])).group("forem_topics.forum_id").maximum("forem_posts.created_at")

lastpostdetails = Forem::Post.joins(:topic, :forem_user).where(created_at:
lastposts.values).pluck("forem_topics.forum_id", "forem_topics.subject",
"forem_posts.created_at", "users.name")

end

FYI, the current lastpost method had a bug where it returns hidden topics.

Best,
Tim Zhu

**Comment by Buildzzz** [comment]
Actually, we need to return the topic id as well so we can use it in the
link_to.

Anyway, let me know if you want to try it out and how you would like me to
integrate to the gem.

Best,
Tim Zhu

**Comment by radar** [comment]
Regarding that bug: can you please file a new issue with steps to reproduce so I can look at it?

That would be awesome :)
