### ISSUE TITLE
uninitialized constant Forem::StateWorkflow

### ISSUE THREAD

**Issue by sintro** [rubysherpas/forem#677]
Almost every time I make change in source code of my project, which has last version of Forem and Rails 4.2.4 (last version), i get 
`uninitialized constant Forem::StateWorkflow`
Server restarting is solving this problem, but I need to do it every 2 minutes.
The problem was noticed already in this Issue: https://github.com/radar/forem/issues/675

**Comment by sintro** [comment]
Sometimes after refreshing the page with error, it changes to another error
`Unable to autoload constant Forem::Concerns::Viewable, expected [...]/gems/forem-b47e8ea42d3f/app/models/forem/concerns/viewable.rb to define it`

**Comment by cjbottaro** [comment]
Exact same issue here.  Subscribing.

**Comment by radar** [comment]
Why open a new issue for it when #675 was already opened?
