### ISSUE TITLE
"edit own posts" policy

### ISSUE THREAD

**Issue by eostrom** [rubysherpas/forem#678]
My client would like users to be able to edit their own posts, but not other people's. It looks like this is awkward to implement, because the authorization is done per forum, not per post. I could override `PostsController#authorize_edit_post_for_forum!` in a decorator, but it's called before `find_post`, which means my decorator has to duplicate that call.

Which is okay, I guess. But it would be nice if the controller authorized `edit` on `post` as well as `edit_post` on `forum`. I haven't thought through the implications, I'm just bringing up the idea.

Same for deleting posts.

**Comment by sintro** [comment]
Strange default policy... Really, every user can edit and delete every post in forem?

UPDATE

Wait, there are lines in update and destroy actions in PostController: 
`if @post.owner_or_admin?(forem_user) && @post.update_attributes(post_params)
        update_successful`
So, even if user will send POST through cURL or something else, he will not be able to edit or destroy other`s posts. I guess, in view`s there are similar check for @post.owner_or_admin? to show "Edit" button.

**Comment by eostrom** [comment]
No. By default, no one can edit any post. By adding methods on your user
class, you can enable some users to edit some posts. But you can't easily
make that decision for individual posts, only for forums.

It's a good setup for admin and moderator policies, just not for what we
have in mind.

**Comment by radar** [comment]
Patches welcome to fix this oversight.

**Comment by eostrom** [comment]
Thanks, @sintro, I hadn't noticed that. So my desired policy is actually the default, once I enable post editing. I'll close this issue; if someone else wants more flexible permissions, they can do it.
