### ISSUE TITLE
first and last topic posts are reversed 

### ISSUE THREAD

**Issue by idearise** [rubysherpas/forem#68]
An example can be seen on the heroku site. Compare the started by and latest post users for any of the topics that have more than one post:

http://forem.heroku.com/forums/1

Marcus started the following, and Bob is the latest user:
http://forem.heroku.com/forums/1/topics/10

I think it has to do with the scope methods that are all set for created_at DESC.

topic_listing.posts.first.user
link_to_latest_post(topic_listing.posts.last)

**Comment by radar** [comment]
I can confirm that this issue exists. Are you able to submit a patch that fixes it?

**Comment by radar** [comment]
I was attempting this just then and I realised it may be a little more complicated than it seems. Due to how we're stubbing out the user stuff in the engine this makes it really difficult. 

I think we should bite the bullet and make Devise provide the user functionality for the dummy application inside the engine. That's something that we (the forem team) will do. Then testing this functionality will be easier and we won't have this issue.

**Comment by STRd6** [comment]
See #30, may be related.

**Comment by radar** [comment]
#30 is absolutely related. Good patch there but needs a little bit more (as I commented). We should also have a test for this behaviour to ensure no accidental regressions.

**Comment by radar** [comment]
It's 5:40pm here currently, so excuse the mess buuutt... I pushed a `devise` branch up which has the beginnings of the Devise changeover to Forem. I am currently stuck on why it can't find the Devise::SessionsController when I run `bundle exec rspec spec/integration/posts_spec.rb` and so another pair of eyes or two would be good to have.

I'm off for the rest of the night. Let me know if you find anything.

**Comment by radar** [comment]
I lied about being off for the rest of the night, sorry!

Once #69's fixed then you will be able to easily write tests for this feature. If you'd like to help with that it would be much appreciated.

Thanks!

**Comment by radar** [comment]
Alright, #69's done. Please submit a patch based off current master to fix this post issue. It is now definitely much easier to test this kind of thing.

**Comment by radar** [comment]
I had some time spare on the train tonight and I've fixed this in 65a894f. Thanks for pointing out the issue!

**Comment by idearise** [comment]
Thanks! Sorry, a bit busy to do this yesterday.
