### ISSUE TITLE
Usernames not showing correctly

### ISSUE THREAD

**Issue by wemmick** [rubysherpas/forem#691]
I got Forem installed (great work, Ryan!) and it's mostly working properly, but my users' names don't seem to be coming through to the view correctly.  They show up as something like "#User:0x007f9944eae748"

My user model is "User" and the name field is "name".  Anything else I should be doing here?

**Comment by wemmick** [comment]
Ah, I see according to http://www.sitepoint.com/forem-rails-forum-engine/ that you need to add this to the user model:

```
def forem_name
  email
end
```

I didn't see this mentioned in the installation guide, so y'all might want to update it.

**Comment by sevenseacat** [comment]
It's listed in the README here: https://github.com/rubysherpas/forem#set-up-helper-methods-in-your-user-model
