### ISSUE TITLE
Partial naming collision

### ISSUE THREAD

**Issue by ghost** [rubysherpas/forem#71]
Hello,

Not a bug, just something to be aware of. I just ran into an error due to having a partial named _head.haml.html in my application.html.haml. It was then load app/views/forem/forums/_head.html.erb.

Maybe something like _forum_head.html.erb?

Thanks,

Albert

**Comment by parndt** [comment]
That's due to Rails' view inheritance.. it does make it interesting..

**Comment by docunext** [comment]
Aha - indeed I am using inherited views. Good catch, something I'll have to be mindful of in the future as I plan to leverage engines all over the place.

**Comment by radar** [comment]
Could you show us how you're referencing this partial in your layout? Could be that you need to give it a more absolute path.

**Comment by docunext** [comment]
Ah - yeah, that will also work. It was just:

```
= render :partial => 'head'
```

but it should have been application/head.

Thanks, great project by the way!!

**Comment by radar** [comment]
Rightio, glad you got this solved :)

Thanks for the super kind words!
