### ISSUE TITLE
rake routes & getting hold of the helpers in tests

### ISSUE THREAD

**Issue by nruth** [rubysherpas/forem#73]
I've been having some problems with the developer-accessibility of engine routes and route helpers, and would appreciate comments. 

If we can drop some stuff in the readme, or think of patches to forem or rails, I'd consider this a success.
1. I want to be able to list the forem routes, so I know which route helpers are available to me. That is to say, I want to be able to do rake:routes:forem or something like that.
2. I also want to be able to do visit forem.forums_path or similar in my capybara tests. Perhaps this can be done through Forem::Engine.route_helpers (I think I've got the wrong chain there) but it didn't seem to work when I did it.

I tried looking into the rails engines code and rake routes stuff, but got lost/frustrated quite quickly. I'd spend longer on it now but I am swamped with non-rails stuff at the moment, so thought I'd see if anyone had ideas.

**Comment by radar** [comment]
Fixed in @dabb3b62d7b4f648d8799499992b605f7e5cf6d5

**Comment by radar** [comment]
To visit the forem routes in your tests you will need to define a `forem` proxy object or follow a link. To define the proxy object, create a new file in your app at `spec/support/url_helpers.rb` and put this content in it:

``` ruby
module UrlHelpers
  def forem
    Forem::Engine.routes.url_helpers
   end
end

RSpec.configure do |c|
  c.include UrlHelpers, :type => :request
end
```

That will define a new `forem` method which will be available in any test located in `spec/integration` or `spec/requests`.

**Comment by nruth** [comment]
Great, thanks!
