### ISSUE TITLE
Rake 0.9.3 under 1.9.3-p0 fails.  Use rake exec instead.

### ISSUE THREAD

**Issue by shimms** [rubysherpas/forem#75]
> You have already activated rake 0.9.3.beta.1, but your Gemfile requires rake 0.9.2.2. Using bundle exec may solve this.

Raverting to 1.9.2-p290 resolves:

> rvm use 1.9.2-p290 --default
> bundle install
> rake forem:install:migrations 

Creates migrations as expected.

**Comment by parndt** [comment]
use bundle exec like it suggests. So instead of running `rake forem:install:migrations` run `bundle exec rake forem:install:migrations`

**Comment by radar** [comment]
Did you try using bundle exec for this like it recommends? Did it give the same error?

**Comment by shimms** [comment]
Yeah that fixed it - thanks for the quick reply.

**Comment by lsrojas74** [comment]
I follow instructions from http://stackoverflow.com/questions/6665949/how-do-you-activate-or-set-the-default-rake
so I make:

vim /usr/local/rvm/gems/ruby-1.9.3-p0/bin/rake

and you see:

#!/usr/local/rvm/rubies/ruby-1.9.3-p0/bin/ruby
#

# This file was generated by RubyGems.

#

# The application 'rake' is installed as part of a gem, and

# this file is here to facilitate running it.

#

require 'rubygems'

version = ">= 0"

if ARGV.first =~ /^_(.*)_$/ and Gem::Version.correct? $1 then
  version = $1
  ARGV.shift
end

#gem 'rake', version   CHANGE THIS LINE TO:
gem 'rake', '0.9.2.2'
load Gem.bin_path('rake', 'rake', version)

save the changes and from console execute: rake -V
and this must be the output: rake, version 0.9.2.2
(I 'm using this version with rails 3.2.3)

If you are using RubyMine go to file + invalidate caches, close project (if any => file + close project) and close the ide and open again. If you are starting a total new project delete the folder and start again
