### ISSUE TITLE
Quoting doesn't work with textile or markdown

### ISSUE THREAD

**Issue by jgadbois** [rubysherpas/forem#78]
The blockquote tag doesn't seem to be supported for either

**Comment by jgadbois** [comment]
Could you maybe add a blockquote method to the formatter API and format it via a helper?  I'd be happy to help if you like that approach.

**Comment by jgadbois** [comment]
I think this can be closed with the blockquote pull request you added

**Comment by knewter** [comment]
@radar @parndt someone want to close this issue?

**Comment by radar** [comment]
Done!
