### ISSUE TITLE
Private messaging?

### ISSUE THREAD

**Issue by dapz** [rubysherpas/forem#84]
Just thought that it would be really useful if Forem had private messaging.

**Comment by radar** [comment]
Would you be able to submit a patch that added this to Forem? It's a fairly regularly requested feature.

**Comment by dapz** [comment]
I can look into it in a couple of weeks. Assuming that nobody gets to
it before then.

On Sun, Nov 27, 2011 at 12:25 AM, Ryan Bigg
reply@reply.github.com
wrote:

**Comment by frankel** [comment]
I use has_mailbox gem for private message

**Comment by chooh** [comment]
+1 for `has_mailbox`

**Comment by gabrielbaez** [comment]
that gem does not seem to be maintained anymore,  https://github.com/fajrif/has_mailbox/issues/2

**Comment by radar** [comment]
Then perhaps we should do it ourselves.

**Comment by dapz** [comment]
This seems to be a good bet: https://github.com/LTe/acts-as-messageable

**Comment by danneu** [comment]
Private messages are conversations. Forem already has a threaded posts system in place. Aren't private conversations no different than a more private implementation of what the forum already uses to facilitate communication?

In that acts-as-messageable gem, you're just sending messages to models. 

```
@me.send_message(@you, "Hello"). 
```

There's no chain of replies to follow. It's like email before our software decided to thread our emails into conversations, or texting on my non-smartphone. As soon as you add `reply_to_id`, you're literally just reimplementing something Forem already has polished.

**Comment by radar** [comment]
I can see where you're coming from @danneu. How would you go about cleanly implementing this?

**Comment by danneu** [comment]
If the crude way would be to write conversation/message models that replicate topic/posts and repeat a bunch of logic, I guess the clean way would be to put that logic into a module that you'd mixin to topics/posts and conversations/messages. Sort of like what the above gems do. That's gotta be a lot of refactoring, though. 

On the other hand, if the choice is between using an above gem or manually copy and pasting topic/post logic into a PM system, neither one seems any DRYer than the other if they're just similar implementations of a similar concept. Even copy and pasting 

I'm no Rails wizard and I've never mixed in a module in my life, but that's what comes to mind.

**Comment by jgadbois** [comment]
What if you had the belong_to for Post be a polymorphic association that applied to Conversation and Topic?

**Comment by ghost** [comment]
+1 for adding this feature.

**Comment by knewter** [comment]
Would it be too dirty to implement PMs as a special forum, with each new (non-reply) PM opening a new thread in the forum with special permissions to that only the participants can view it?  Then you could conceivably expand it later so that you could invite more people into your private thread.  You would just need to add logic to hide the special forum from index views and modify the ACL bits.

Is this too 'hacky'?  It's definitely the sort of thing I would do regularly in this situation if it's just for me/a client.

**Comment by safarista** [comment]
Am kinda confused here. Are we talking **Private Messaging** like Facebook or **Private Forums?** If the former I would just use a lib like The one I curate `gem private_messages`

**Comment by safarista** [comment]
Cant edit the aboabove from my ipad. `gem simple-private-messages`

**Comment by danneu** [comment]
@safarista: I might have confused the discussion, but I was just pointing out that private messages are, in essence, just conversations that follow the same Topic/Post paradigm (the machinery already in place). But elegantly reusing code is not something I'm well-versed in.

**Comment by regedarek** [comment]
So, I would like to help with that issue, but i think it will be too dificult with mixin in forem modules, i`ll try add https://github.com/LTe/acts-as-messageable.

Or you could explain me more clearly danneu idea :)
https://github.com/radar/forem/issues/84#issuecomment-3404744

**Comment by parndt** [comment]
@danneu can you help @regedarek please?

**Comment by danneu** [comment]
@regedarek Looks good to me. I didn't mean to ostensibly stagnate this issue when I made the observation that private message conversations are conceptually just Topics that only recipients can see and participate in.

Lead the way.

**Comment by regedarek** [comment]
ok, I will take care of this from monday... using mailboxer gem

**Comment by aybabtme** [comment]
+1 I'd also like to see that.  I'm looking around for a forum app where to port a small community (out of php-world) and I'd like to use this app, but my people will not accept to switch to a PM-less forum...

I don't have the background to implement this myself, but I'll keep an eye on the project.

**Comment by radar** [comment]
@AntoineGrondin What do you need the messaging system to do?

**Comment by aybabtme** [comment]
The following, in my view, are 'must have'.
- Formatting as in usual posts.
- Forward/CC and BCC.
- Save copy of sent/received posts.
- Registered users only.

While those are 'nice to have'.
- Send e-mail to user when she receives a PM.
- 'Quote-to-PM' another user's post directly from the forums, to start a new PM with regard to that post.
- Searchable archives, by word, user, message-age.
- Ability to export archives.
- Ban PM from specific users.

**Comment by juozasg** [comment]
+1 on this feature and AntoineGrodnin's requirements! except banning/blocking particular users should be a must have imo and as far as search goes, it should be part of the larger search feature i think.

no comment on implementation

**Comment by Papipo** [comment]
What about https://github.com/ging/mailboxer

**Comment by radar** [comment]
@Papipo Already mentioned earlier in the thread by @regedarek, who said he would implement it and hasn't yet.

**Comment by regedarek** [comment]
I started implementing this. I think i push sample pull request on Sunday.

**Comment by radar** [comment]
No pull request yet :(

**Comment by MOZGIII** [comment]
Please do not add this at forem. Create a separate project for this. This should be aside of forum.

**Comment by MOZGIII** [comment]
By the way, it would be possible (I mean not just possible... logical? acceptable?) if you make the system modular, like omniauth, so we can add gems to get a feature.

**Comment by radar** [comment]
@MOZGIII What does that even mean?

Also: please qualify your reasonings for thinking that this should be a separate project from Forem. You can't just state your opinion without backing it up with reasons, man.

**Comment by hauleth** [comment]
I think, that PM is not a part of forum engine. It rather should be externally like @Papipo said.

**Comment by MOZGIII** [comment]
@radar I just want to have a choice of what pm system to use with forem, I do not need built in system for that (but I support creating a separate project for this functional). If you want t implement PM,please do it the way forem and PM system to not depend on each other in any way.

BTW, I am using my own implementation of messaging system, so I think I won't use other implementation and therefore do not want this functional to be built in this particular project. Just make another one for that.

**Comment by Papipo** [comment]
Actually I don't like the groups and admin stuff in forem at all. I rather use my own admin panel (activeadmin), and for authorization I am using cancan, so there is no point in having duplicate stuff.

Any big feature in forem which is not really tied to the forum itself should be in a separate engine. That way you might even use those engines but not forem, forem alone, or a combination of those.

Extracting the groups to a new engine would be a great step.

**Comment by MOZGIII** [comment]
@Papipo +1, can you share your activeadmin stuff?

**Comment by Papipo** [comment]
Sorry I don't have such thing because I'm not using forem groups. What I meant is that if I wanted to use any kind of groups, I would use my own solution or something like https://github.com/kristianmandrup/cantango, and I would manage them probably with activeadmin, which is my preferred admin panel, and I don't want to have two separate admin points.

**Comment by Papipo** [comment]
In fact I was going to use forem, but I think I will roll my own solution. I see many queries in the logs about forem groups which shouldn't be there, and I don't like that the subscription sends emails instead of letting me hook something else, like internal notifications/messages.

**Comment by parndt** [comment]
What about adding support for / fixing the things you mention before going and rolling your own? We would really appreciate the help.

**Comment by radar** [comment]
The queries for groups are there due to checks for permissions on forums. I don't think there are queries that run when they shouldn't. If there are, then Phil has already correctly suggested that we would love your help in eliminating these excessive queries.  

Also, please explain what you mean by internal messaging. Maybe we can work something out.  

## 

Ryan Bigg

**Comment by Papipo** [comment]
I would start by moving the groups stuff to its own engine. Forem might be aware of the features it adds and hook up if needed on initialization. In the end all what is needed for moderation is CanCan, which you can of course spice up with groups, but that's another story.

The same goes for notifications and messaging. It would be nice to have a notification engine based on mailboxer, which forem could take advantage of if needed, and any other future engine as well.

Remember that people like me don't need groups, which are some overhead and you want the system to be as modular as possible anyway.
And I have my own admin where I would like to add stuff to handle forem data. Having two different admin points makes no sense.

**Comment by safarista** [comment]
So basically forem would only have forums, posts and threads. And require
authAuth to be defined ie, authorisation and authentication somehow. I like
this.

**Comment by parndt** [comment]
I personally would love to see Forem as a robust base for many extensions that provide extra functionality that shouldn't go in the core. :+1:

**Comment by Papipo** [comment]
In fact I have never used django, but I really like their apps concept. They are like rails' mountable engines, but they have lots of them which are quite mature. Imagine that you grab a new app, throw in an authentication engine, forem, a search engine (no pun intended), etc and voilà.

Somehow it seems weird to me that nobody started something like this but for rails: http://www.djangopackages.com/categories/apps/

And please, don't tell me what people always says: "Rails makes it very easy to roll your own stuff". Yeah, I know, but I would like to reuse something else than devise and inherited_resources.

**Comment by parndt** [comment]
That actually sounds a lot like http://refinerycms.com

**Comment by Papipo** [comment]
How independent are the modules from each other in refinery?

**Comment by parndt** [comment]
The idea is that modules be 100% independent and use API style hooks
for communication.

**Comment by Papipo** [comment]
So I can use, let's say, the site search or calendar modules alone? (or together, but without the cms itself nor any other module)

**Comment by parndt** [comment]
Oh I get what you mean - every extension requires the 'refinerycms-core' module. Technically everything relies on refinerycms-core unless the extension needs pages, images, resources etc.
