### ISSUE TITLE
Uninitialized constant Forum

### ISSUE THREAD

**Issue by yfaway** [rubysherpas/forem#86]
Hello,

I just install the this library and I am able to create forum and categories. However, when I click on a forum, I got this error message:

NameError in Forem::ForumsController#show

uninitialized constant Forum

Rails.root: C:/projects/EcoSearch
Application Trace | Framework Trace | Full Trace

Request

Parameters:

{"id"=>"1"}

Could you please let me know what I am missing?

Thank you,

**Comment by radar** [comment]
It's working on the demo site: http://forem.heroku.com/forums/1. Is there anything that you've changed?

**Comment by yfaway** [comment]
No, not really. My application was in rails 3.0. Since forem requires 3.1, I upgraded it, then install forem. I follow the previous instructions to migrate the db (before you have the script rails g forem:install).

**Comment by radar** [comment]
Can you share the stacktrace for this error?

**Comment by yfaway** [comment]
All I get is this error in the log. Not very helpful. I am going to create a brand new rail app and try to integrate forem there to see if everything is alright.

2011-11-27 20:23:18] log_subscriber:110 in info -> Completed 500 Internal Server Error in 1571ms
2011-11-27 20:23:18] show_exceptions:133 in log_error ->
ameError (uninitialized constant Forum):

2011-11-27 20:23:18] log_subscriber:110 in info -> Rendered c:/programs/jruby-1.6.5/lib/ruby/gems/1.8/gems/actionpack-3
1.3/lib/action_dispatch/middleware/templates/rescues/_trace.erb (9.0ms)
2011-11-27 20:23:18] log_subscriber:110 in info -> Rendered c:/programs/jruby-1.6.5/lib/ruby/gems/1.8/gems/actionpack-3
1.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (3.0ms)
2011-11-27 20:23:18] log_subscriber:110 in info -> Rendered c:/programs/jruby-1.6.5/lib/ruby/gems/1.8/gems/actionpack-3
1.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (38.0ms)

**Comment by radar** [comment]
What does the full trace show? I gather that you can see this error on the screen?

**Comment by yfaway** [comment]
Radar, the screen shows the same thing. I tried again with a blank app, and I didn't get the same error. So there must be something wrong with that app. I will close this issue now.

Thanks,
