### ISSUE TITLE
Bugs in rails g forem:install

### ISSUE THREAD

**Issue by yfaway** [rubysherpas/forem#87]
Hi,

I notice the following issues with the installer:
1. For the question "What is your user class called? [User]", user might press Enter right away if the their model is User already. This generates a method missing error since the installer doesn't set the value of @user_class to User.
2. The migration ids for add_category_id_to_forums and add_forem_admin are the same -> migration error.

**Comment by radar** [comment]
I'm not seeing the method missing error. I see "uninitialized constant Forem::Generators::InstallGenerator::User " though. I'll see what I can do to fix this now.

**Comment by radar** [comment]
Alright I think I've fixed this one. Please give it another go and open another issue if it's still causing problems.
