### ISSUE TITLE
Abstract out ActiveRecord

### ISSUE THREAD

**Issue by nwmcsween** [rubysherpas/forem#94]
Currently forem relies on activerecord it should factor this out and use templates similar to padrino-admin(?) or a glue between different ORMs (I don't think this is possible). A bullet list of what needs to be converted for this to work would be appreciated.

**Comment by parndt** [comment]
@nwmcsween Are you happy to work on this?

**Comment by nwmcsween** [comment]
yes for datamapper, it looks relatively simple.

**Comment by radar** [comment]
My concern with this is that, if this is done incorrectly, future modifications to the models would need to be done across the different adapters. While I'm all for the change, I just don't see a clean way to do it right now.

Maybe you're seeing something I'm not. I look forward to seeing your code :)

**Comment by nwmcsween** [comment]
I'll give this a shot on the weekend, and I don't see any other way of becoming orm neutral without having seperate models

**Comment by knewter** [comment]
Any progress on this?  It's been floating with no updates for 5 months, so unless someone's willing to push it forward I'm considering closing it until someone is actively requesting the feature and offering to maintain the adapters for a limited period at least.

**Comment by parndt** [comment]
Can we look at orm_adapter

**Comment by parndt** [comment]
Please open a pull request if you want to tackle this!
